<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsDeal
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */

?>
<?php 
$deal_id = $this->getRequest()->getParam('deal_id');
$setting = $this->_objectManager->create('Ced\CsDeal\Model\Deal')->load($deal_id);
$_product = $this->_objectManager->create('Magento\Catalog\Model\Product')->load($setting->getProductId());
if($_product && $_product->getId()){
	$product_name=$_product->getName();
}
?>
<div class="vendor-dashboard">
<form id="deal_form" action="<?php echo $this->getUrl('csdeal/deal/save',array('deal_id'=>$this->getRequest()->getParam('deal_id'))); ?>" method="post" data-mage-init='{"validation": {}}' autocomplete="off">
	<div class="row">
		<div class="col-md-12" style="margin-top:10px;" />
			<div class="panel panel-default">
				<div class="panel-heading col-md-12 uptransform" style="line-height:31px;font-weight:bold;padding:4px 15px;font-size:17px;">
					<?php echo __('Edit Deal')?>
					<div class="buttons-set col-md-6 buttons_scb" style="float:right;text-align:right;margin-right:2px;">	
						<button onclick="dealdelete()" class="scalable btn-danger " type="button" id="deal_createdelete"><span>Delete</span></button>
						<button onclick="dealback()" class="scalable btn-warning" type="button" id="deal_createback"><span>Back</span></button>
						<button class="scalable btn-success " type="submit" id="deal_createsave"><span>Update Deal</span></button>
					</div>
					
					<div style="clear:both" /></div>
				</div>
				<div style="clear:both"></div>
				<div class="panel-body">
					<div class="vendor panel" style="padding:2%">
    <div id="deal-wrapper" class="deal-wrapper" >
	
	  <div class="fieldset">
		<ul class="form-list">
			<li class="fields">
				<label class="required" for="date_from"><?php echo __('Product Id'); ?></label>
                <div class="clear:both"></div>
				<div class="input-box">
                <input type="text" class="input-text required-entry" readonly="true" value="<?php echo $setting->getProductId(); ?>" id="product_id" name="product_id"/>
                </div>
                <input type="hidden" value="<?php echo $setting->getVendorId(); ?>" id="vendor_id" name="vendor_id"/>
			</li>
			<li class="fields">
				<label class="required" for="deal_product_name"><?php echo __('Product Name'); ?></label>
                <div class="clear:both"></div>
				<div class="input-box">
              
                <input type="text" class="input-text required-entry" readonly="readonly" value="<?php echo $product_name; ?>" id="deal_product_name" name="deal_product_name"/>
               
                </div>
			</li>
			
			<li class="fields">
				<label class="required" for="enable_status"><?php echo __('Deal Status'); ?></label>
				 <div class="clear:both"></div>
				<div class="input-box">
					<select id="enable_status" class="validate-select required-entry" name="status">
					<?php
					$status = $this->_objectManager->get('Ced\CsDeal\Model\Status')->toOptionArray();
					
					foreach ($status as $key => $value) {
						?>
						<option <?php if($key == $setting->getStatus()){?> selected="selected"<?php }?> value="<?php echo $key; ?>" ><?php echo $value; ?></option>	
						<?php 
					}
					 ?>
					</select>
				</div>
			</li>
			<li class="fields">
				<label class="required" for="deal_price"><?php echo __('Deal Price'); ?></label>
                <div class="clear:both"></div>
				<div class="input-box">
              
                <input type="text" class="input-text required-entry validate-number"  value="<?php echo $setting->getDealPrice(); ?>" id="deal_price" name="deal_price"/>
               
                </div>
			</li>
			<li class="fields">
				<label class="required" for="date_from"><?php echo __('Deal From'); ?></label>
				 <div class="clear:both"></div>
				<div class="input-box">
                 
                <input type="text" class="input-text required-entry" readonly="readonly" value="<?php echo $setting->getStartDate(); ?>" id="start_date" name="start_date"/>
               <img style="padding:7px;float:left; cursor: pointer;" src="<?php echo $block->getViewFileUrl('images/calendar.gif'); ?>" class="v-middle" id="from1" alt="Select Date"/>
                </div>
                <img style="" title="Select Date" id="date_select_from"  class="v-middle" alt="" src="<?php echo $this->getSkinUrl("images/calendar.gif");?> "/>
                <div class="clear:both"></div>
			</li>
			<li class="fields">
				<label class="required" for="date_to"><?php echo __('Deal To'); ?></label>
				 <div class="clear:both"></div>
				<div class="input-box">
				
                <input type="text"  class="input-text required-entry" readonly="readonly" value="<?php echo $setting->getEndDate(); ?>" id="end_date" name="end_date"/>
                <img style="padding:7px;float:left; cursor: pointer;" src="<?php echo $block->getViewFileUrl('images/calendar.gif'); ?>" class="v-middle" id="to1" alt="Select Date"/>
    		    </div>
    		    <img style="" title="Select Date" id="date_select_to" class="v-middle" alt="" src="<?php echo $this->getSkinUrl("images/calendar.gif");?> "/>
				<div class="clear:both"></div>
			</li>
			
		</ul>

						</div>
					</div>
				</div>
			</div>
	</div>
</div>
</form>
<script type="text/javascript">
require([
         "jquery",
         "mage/calendar"
    ], function($){
    	var dateToday = new Date();

        $("#start_date").calendar({
             buttonText:"<?php echo __('Select Date') ?>",
             minDate: dateToday,

        });
      });





    require([
             "jquery",
             "mage/calendar"
        ], function($){
        	var dateToday = new Date();
            $("#end_date").calendar({
                 buttonText:"<?php echo __('Select Date') ?>",
                 minDate: dateToday,

           });
          });
   

</script>
<script type="text/javascript">
    function dealback(){
        document.location.href='<?php echo $this->getUrl("csdeal/deal/listi"); ?>';
    }
    function dealdelete(){
        document.location.href='<?php echo $this->getUrl("csdeal/deal/delete",array('deal_id'=>$this->getRequest()->getParam('deal_id'))); ?>';
    }
</script>
<style>
   label.required em, span.required em {
    	display: none;
	}
	label.required::after, span.required::after {
	    color: red;
	    content: " *";
	    font-family: "Helvetica Neue",Verdana,Arial,sans-serif;
	    font-size: 12px;
	    font-weight: normal;
	}
</style>
<script type="text/x-magento-init">
{
    "#deal_form": {
    "validation": {}
    }
}
</script>
<script type="text/javascript">
require([
  'jquery',
  'mage/mage'
], function($){

var dataForm = $('#deal_form');
dataForm.mage('validation', {});
});
</script>
<script type="text/javascript">
require([
  'jquery',
  'mage/mage'
], function($){

		function save(){
			if(jQuery('#deal_form').validation('isValid') && jQuery('#deal_form').validation()) {
				document.getElementById("deal_form").submit();  
			}    
        }
        function dealback(){
            document.location.href='<?php echo $this->getUrl("csdeal/deal/listi"); ?>';
        }
        function dealdelete(){
            document.location.href='<?php echo $this->getUrl("csdeal/deal/delete",array('deal_id'=>$this->getRequest()->getParam('deal_id'))); ?>';
        }
});
					 
</script>
