<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Account Information') ?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ echo __('Contact Information') ?></span>
            </strong>
            <div class="box-content">
                <p>
                   
                </p>
            </div>
            <div class="box-actions">
               
                
            </div>
        </div>

            <div class="box box-newsletter">
                <strong class="box-title">
                    <span><?php /* @escapeNotVerified */ echo __('Newsletters') ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        
                            <?php /* @escapeNotVerified */ echo __('You subscribe to "General Subscription".') ?>

                            <?php /* @escapeNotVerified */ echo __('You don\'t subscribe to our newsletter.') ?>

                    </p>
                    <?php /* Extensions placeholder */ ?>
                   
                </div>
                <div class="box-actions">
                  
                </div>
            </div>

    </div>
</div>
