<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<!-- /.navbar-header -->
<ul class="nav navbar-top-links navbar-right in">
	<li class="dropdown">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
			<i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
		</a>
		<ul class="dropdown-menu dropdown-alerts">
			<li>
				<a href="<?php ?>" title="<?php ?>">
					<div>
						<i class="fa fa-bell fw"></i>
						<span class="pull-right text-muted small">..</span>
					</div>
				</a>
			</li>
			<li class="divider"></li>	
			<li>	
				<a href="#" title="<?php  ?>">
					<div>
						<i class="fa fa-bell fw"></i>
						<span class="pull-right text-muted small">..</span>
					</div>
				</a>
			</li>
			<li class="divider"></li>
			<li>
				<a href="<?php ?>" title="<?php  ?>">
					<div>
						<i class="fa fa-bell fw"></i>
						<span class="pull-right text-muted small">..</span>
					</div>
				</a>
			</li>
			<li class="divider"></li>
		</ul>
	</li>
</ul>