<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category Ced
 * @package Ced_Productfaq
 * @author CedCommerce Core Team
 * @copyright Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license http://cedcommerce.com/license-agreement.txt
 */
?>
<h2><a href="javascript:;" onclick="testing(event)" id="addScnt"><?php echo __('Add Another Input Box')?></a></h2>
<div id="p_scents">
    <p>
      <label><?php echo __('Title')?></label> <label for="title"><input type="text" id="title[quest1]title" size="20" name="title[quest1]title" value="" placeholder="Input Value" /></label>
      <label><?php echo __('Description')?></label> <label for="description"><textarea rows="4" id="description[desc1]description"  name="description[desc1]description" placeholder="Please Enter Description" column="4"></textarea>

  </label>
    </p>
</div>
