<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<?php  $params = $this->_objectManager->get('Ced\CsMarketplace\Model\Session')->getData('vorders_reports_filter');
?>
<?php // echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form
action="javascript:void( 0 );"
method="post"
id="report-form-validate" class="order-reports">
<div class="col-md-12">
	<h4 class="legend" ><?php echo __('Filter Report') ?>
	</h4>		
	<div style="clear:both"></div>
	<div class="form-group col-md-3 rtl-active">
		<label><?php echo __('Period') ?>:</label>
			<div class="input-box">
				<select id="period" class="select form-control"
				name="period">
				<option <?php echo isset($params['period']) && $params['period']=='day'?"selected":"";?> value="day"><?php echo __('Day'); ?></option>
				<option <?php echo isset($params['period']) && $params['period']=='month'?"selected":"";?> value="month"><?php echo __('Month'); ?></option>
				<option <?php echo isset($params['period']) && $params['period']=='year'?"selected":"";?> value="year"><?php echo __('Year'); ?></option>
			</select>
		</div>
	</div>
<div class="form-group col-md-3 rtl-active">
	<label ><?php echo __('Vendor Payment Status') ?>:</label>
		<div class="input-box">
			<select id="payment_state" name="payment_state" class="select form-control"
			>
			<option  <?php echo isset($params['payment_state']) && $params['payment_state']=="*"?> value="*"><?php echo __('All'); ?></option>
			<option  <?php echo isset($params['payment_state']) && $params['payment_state']=\Ced\CsMarketplace\Model\Vorders::STATE_OPEN?"selected":"";?> value="<?php echo \Ced\CsMarketplace\Model\Vorders::STATE_OPEN ?>"><?php echo __('Pending'); ?></option>
			<option  <?php echo isset($params['payment_state']) && $params['payment_state']==\Ced\CsMarketplace\Model\Vorders::STATE_PAID?"selected":"";?>  value="<?php echo \Ced\CsMarketplace\Model\Vorders::STATE_PAID ?>""><?php echo __('Paid'); ?></option>
			<option  <?php echo isset($params['payment_state']) && $params['payment_state']==\Ced\CsMarketplace\Model\Vorders::STATE_CANCELED?"selected":"";?> value="<?php echo \Ced\CsMarketplace\Model\Vorders::STATE_CANCELED ?>""><?php echo __('Cancelled'); ?></option>
		</select>
	</div>
</div>
<?php 
$url = $block->getViewFileUrl('iamges/calendar.gif');
?>
<div class="form-group col-md-3 rtl-active">
	<label class="required"><em>*</em><?php echo __('Start date') ?>:</label>
	<div class="input-box" id="inputbox">
		<input type="text" class="required-entry input-text validate-date form-control"  name="from"
		id="from" value="<?php echo isset($params['from']) && ($params['from']!="")?$params['from']:""; ?>"/>
	</div>
</div>
<div class="form-group col-md-3 rtl-active">
	<label class="required"><em>*</em><?php echo __('End date');  ?>:</label>
	<div class="input-box" id="inputbox">
		<input type="text" class="required-entry input-text validate-date form-control"  name="to"
		id="to" value="<?php echo isset($params['to']) && ($params['to']!="")?$params['to']:""; ?>"/>
	</div>
</div>
</div>
<script>
	require([
		"jquery",
		"mage/calendar"
		], function($){
			$("#from").calendar({
				buttonText:"<?php echo __('Select Date') ?>",
			});
		});
	require([
		"jquery",
		"mage/calendar"
		], function($){
			$("#to").calendar({
				buttonText:"<?php echo __('Select Date') ?>",
			});
		});
	</script>
	<div class="col-md-12">
		<div class="button-set text-right">
			<button class="button btn btn-warning uptransform" title="<?php echo __('Export') ?>" onClick="window.location='<?php echo $this->getUrl('*/*/ExportVordersCsv',array('_nosid'=>true))?>'" id="export_btn">
				<span><span><?php echo __('Export') ?></span></span>
			</button>
			<button class="button btn btn-info uptransform" title="<?php echo __('Show Report') ?>" onClick="filterVordersReports(0);" id="filter_butn">
				<span><span><?php echo __('Show Report') ?></span></span>
			</button>

		</div>
	</div>
</form>
<script type="text/javascript">
//<![CDATA[
require(["jquery"], function ($) {
	$(document).ready(function ()  { 
		$('#filter_butn').click(function () { 
			if ($('#report-form-validate').valid()) {
				return false;
			}
		}); 
	});
});
//]]>
function filterVordersReports(reset){
	if(reset==2){
		reset=0;
		jQuery('#activity-loading').show();
	}
	else{
		jQuery('#activity-loading').show();
	}
	var params ;
	var url1 = "<?php echo $this->getUrl('csmarketplace/vreports/filtervorders/')  ?>";
	params = jQuery("#report-form-validate").serialize();
	/* alert(params); */
	<?php 
	$urlParams['_nosid'] = true;
	if($this->_objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore(null)->isCurrentlySecure()){
		$urlParams['_secure'] = true;
	}
	$url =  $this->getUrl('csmarketplace/vreports/filtervorders',$urlParams); ?>
	jQuery.ajax({
		url: url1,
		data:{"data":params},
		type:"POST",
		success:function(transport){
			jQuery('#csmarketplace-vreports-vorders').html(transport);
			jQuery('#activity-loading').hide();
		}
	});
}
</script>
<style>
	label.required em, span.required em {
		display: none;
	}
	label.required::after, span.required::after {
		color: red;
		content: " *";
		font-family: "Helvetica Neue",Verdana,Arial,sans-serif;
		font-size: 12px;
		font-weight: normal;
	}
</style>
