<?php
 /**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsProduct
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\ConfigurableProduct\Block\Adminhtml\Product\Edit\Tab\Variations\Config\Matrix */

$productMatrix = $block->getProductMatrix();
$attributes = $block->getProductAttributes();

/* @noEscape */ echo $block->getVariationWizard([
    'attributes' => $attributes,
    'configurations' => $productMatrix,
    'configurableModal' => $block->getForm() . '.' . $block->getModal()
]);
?>
<script>
    require(['jquery', 'uiRegistry', 'underscore'], function ($, registry, _) {
        $('body').trigger('contentUpdated');
        $('.<?= /* @noEscape */ $block->getData('config/dataScope')?>[data-role=steps-wizard-main]').applyBindings();

        registry.async('<?= /* @noEscape */ $block->getData('config/nameStepWizard')?>')(function (component) {
            _.delay(component.open.bind(component), 500); // TODO: MAGETWO-50246
        })
    });
</script>
