<?php

/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category    Ced
  * @package     Ced_CsImportExport
  * @author  	 CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license      http://cedcommerce.com/license-agreement.txt
  */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Backend\Block\Widget\Form\Container */
 ?>
<div class="row">
	<div style="margin-top:10px;" class="col-md-12">
		<div class="panel panel-default">
			<?php /* @escapeNotVerified */ echo $block->getFormInitScripts() ?>
			<div style="font-weight:bold;padding:4px 15px;" class="panel-heading col-md-12 uptransform">
				<div style="line-height:31px;font-size:17px;padding-left:0;" class="col-md-12 panel_product_heading">

							<div class="page-actions-inner" data-title="Export">
								<div class="buttons-set col-md-12 buttons_scb" style="text-align:right;padding-right:0;">
									
								</div>
							</div>

				</div>
			</div>
			<div class="panel-body">
				<?php echo $block->getFormHtml() ?>
				<?php if ($block->hasFooterButtons()): ?>
					<div class="content-footer">
						<p class="form-buttons"><?php echo $block->getButtonsHtml('footer') ?></p>
					</div>
				<?php endif; ?>
			</div>
			
			<script>
			require([
				'jquery',
				'mage/backend/form',
				'mage/backend/validation'
			], function($){

				$('#edit_form').form()
					.validation({
						validationUrl: '<?php /* @escapeNotVerified */ echo $block->getValidationUrl() ?>',
						highlight: function(element) {
							var detailsElement = $(element).closest('details');
							if (detailsElement.length && detailsElement.is('.details')) {
								var summaryElement = detailsElement.find('summary');
								if (summaryElement.length && summaryElement.attr('aria-expanded') === "false") {
									summaryElement.trigger('click');
								}
							}
							$(element).trigger('highlight.validate');
						}
					});
			});
			</script>
		</div>
	<?php /* @escapeNotVerified */ echo $block->getFormScripts() ?>
	</div>
</div>