<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */
?>
<div class="col-md-8 col-md-offset-2">
    <div class="login-panel panel panel-default">
		<div class="panel-heading" style="text-align: center;font-weight:bold;">
			<h3 style="font-size:20px;" class="panel-title"><?php echo __('You are now logged out') ?></h3>
		</div>
		<div class="panel-body">
			<?php echo __('You have logged out and will be redirected to login page in 5 seconds.') ?>
		</div>
	</div>
</div>
<script>
require(["jquery", "mage/mage"], function($) {
   	$($.mage.redirect("<?php /* @escapeNotVerified */ echo $block->getUrl() ?>", "assign", 5000));
});
</script>
