<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMessaging
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

?>
<style>

    .page-title-wrapper {
        display: none;
    }

    .form-group {
        width: 103%;
    }

</style>
<?php


$vendor_id = $this->getRequest()->getParam('id');
$vendor = $this->_vendorFactory->load($vendor_id);
$vendor_email = $vendor->getEmail();
//echo $vendor_email;die;
$messages = $this->getCollection();
$vendors = $this->_vendorFactory->getCollection()->getData();
$admin_name = $this->_scopeConfig->getValue('trans_email/ident_general/name', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
//$vendors[] = ['entity_id'=> 0,'name'=>$admin_name];
$adminInboxCount = $this->_messagingHelper->getCustomerInboxCountForAdmin();
$vendorInboxCount = $this->_messagingHelper->getCustomerInboxCountForVendor();
?>

<div class="top_msg"></div>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header content-header-wrap">
        <h3>
            <?php echo __('Customer Vendor & Admin Conversation Area') ?>
        </h3>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="left-sidebar-wrap">
                <div class="box-header with-border box-folder">
                    <h3 class="box-title"><?php echo __('Folders') ?></h3>
                </div>
                <div class="box box-solid">

                    <div class="box-body no-padding">
                        <ul class="nav nav-pills nav-stacked">
                            <li><a
                                        href="<?php echo $this->getUrl('csmessaging/frontend/inbox');//Mage::getUrl('csvendorchat/frontend/inbox')?>"
                                        class=""><?php echo __('Vendor Inbox'); ?> <span
                                            class="label label-primary pull-right"><?php if ($vendorInboxCount > 0) {
                                            echo '(';
                                            echo $vendorInboxCount;
                                            echo ')';
                                        } ?></span></a></li>
                            <li>
                                <a href="<?php echo $this->getUrl('csmessaging/frontend/admininbox'); ?>"> <?php echo __('Admin Inbox'); ?>
                                    <span class="label label-primary pull-right"><?php if ($adminInboxCount > 0) {
                                            echo '(';
                                            echo $adminInboxCount;
                                            echo ')';
                                        } ?></span></a></li>
                            <li><a
                                        href="<?php echo $this->getUrl('csmessaging/frontend/sent');//Mage::getUrl('csvendorchat/frontend/sent')?>"
                                        class="sent-mail-tab"> Sent</a></li>

                        </ul>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
            <!-- /.col -->
            <div class="right-sidebar-wrap mail-compose">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title"><?php echo __('Compose New Message') ?></h3>
                        <div class="clear"></div>
                    </div>
                    <!-- /.box-header -->
                    <form method="post"
                          action="<?php echo $this->getUrl();//Mage::getBaseUrl()?>csmessaging/frontend/savechat"
                          enctype="multipart/form-data">
                        <div class="chhosevendors">
                            <?php if ($vendor_id == 0 && $vendor_id != '') { ?>
                                <input type="text" readonly="true" value="<?php echo $admin_name; ?>"/>
                            <?php } else { ?>
                                <select name="vendor_data" id="vendor_data">
                                    <option value=""><?php echo __('Select the Vendor') ?></option>

                                    <?php foreach ($vendors as $key => $value) {
                                        $vendor = $this->_vendorFactory->load($value['entity_id']);
                                        $vendor_email = $vendor->getEmail();
                                        $vendor_name = $vendor->getName();
                                        /*if ($value['entity_id'] == 0)
                                        {
                                            $vendor_name = $value['name'];
                                        }*/

                                        ?>
                                        <option value="<?php echo $value['entity_id'] ?>" <?php if ($value['entity_id'] == $vendor_id) { ?> selected="selected"<?php } ?>><?php echo $vendor_name ?></option>
                                    <?php } ?>
                                </select>
                            <?php } ?>
                        </div>

                        <input type="hidden" value="<?php echo $vendor_id ?>"
                               name="vendor_id"/>
                        <div class="form-group">
                            <input class="form-control" name="email_subject"
                                   placeholder="Subject:" id="vendor_subject" value=""/>
                        </div>

                        <div class="form-group">
                            <textarea id="compose-textarea" name="text_email" class="form-control"
                                      style="height: 200px;width:97%;" value=""></textarea>
                        </div>
                        <?php if ($this->_scopeConfig->getValue('ced_csmarketplace/csmessaging/customer_send_mail', \Magento\Store\Model\ScopeInterface::SCOPE_STORE)) { ?>
                            <div class="customer-to-vendor-email">
                                <input type="checkbox" name="sent_to_vendor" value="1"/>
                                <?php if ($vendor_id == 0 && $vendor_id != '') { ?>
                                    <label><?php echo __('Email this message to Admin') ?></label>
                                <?php } else { ?>
                                    <label><?php echo __('Email this message to Vendor') ?></label>
                                <?php } ?>
                            </div>

                        <?php } ?>
                        <div class="box-footer">
                            <div class="pull-right">

                                <button class="btn btn-primary" id="btn-chat" type="button" onclick="send()">
                                    <i class="fa fa-envelope-o"> <?php echo __('Send') ?></i>
                                </button>
                            </div>

                        </div>
                        <!-- /.box-footer -->
                    </form>
                </div>
                <!-- /.col -->
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<script>
    function send() {
        var text = jQuery("#compose-textarea").val();
        var vendor_subject = jQuery("#vendor_subject").val();
        var vendorremail = jQuery("#vendor_data").val();
        var vendorId = '<?php echo $vendor_id; ?>';
        if (!vendorremail && vendorId != 0 && vendorId != '') {
            alert('Please Specify The Recipient');
        }
        else if (!text) {
            alert('Message cannot be Empty');
        }
        else if (!vendor_subject) {
            alert('Subject cannot be Empty');

        }
        else {
            var btn = document.getElementById('btn-chat');
            btn.setAttribute('type', 'submit');
        }

    }
</script>