<style>

    .page-title-wrapper {
        display: none;
    }


</style>
<?php $chat_id = $this->getRequest()->getParam('id');
$chat = $this->_messagingFactory->create()->load($chat_id);
$originalDate = $chat->getTime();
$newDate = date("d-F-Y H:m:s", strtotime($originalDate));
$messages = $this->getinboxcollection();
$adminInboxCount = $this->_messagingHelper->getCustomerInboxCountForAdmin();
$vendorInboxCount = $this->_messagingHelper->getCustomerInboxCountForVendor();

?>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header content-header-wrap">
        <h3>
            <?php echo __('Customer Vendor & Admin Conversation Area') ?>
        </h3>

    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="left-sidebar-wrap">
                <div class="box-header with-border box-folder">
                    <h3 class="box-title">Folders</h3>
                </div>

                <div class="box box-solid">

                    <div class="box-body no-padding">
                        <ul class="nav nav-pills nav-stacked">
                            <li>
                                <a href="<?php echo $this->getUrl('csmessaging/frontend/customercompose')//Mage::getUrl('csvendorchat/frontend/customercompose')?>"
                                   class="btn btn-block margin-bottom">Compose</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->getUrl('csmessaging/frontend/inbox');//Mage::getUrl('csvendorchat/frontend/inbox')?>"><i
                                            class="fa fa-inbox"></i><?php echo __('Vendor Inbox'); ?> <span
                                            class="label label-primary pull-right"><?php if ($vendorInboxCount > 0) {
                                            echo '(';
                                            echo $vendorInboxCount;
                                            echo ')';
                                        } ?></span></a></li>
                            <li>
                                <a href="<?php echo $this->getUrl('csmessaging/frontend/admininbox'); ?>"> <?php echo __('Admin Inbox'); ?>
                                    <span class="label label-primary pull-right"><?php if ($adminInboxCount > 0) {
                                            echo '(';
                                            echo $adminInboxCount;
                                            echo ')';
                                        } ?></span></a></li>
                            <li>
                                <a href="<?php echo $this->getUrl('csmessaging/frontend/sent');//Mage::getUrl('csvendorchat/frontend/sent')?>"><i
                                            class="fa fa-envelope-o"></i> Sent</a></li>
                            <!--   <li><a href="#"><i class="fa fa-file-text-o"></i> Drafts</a></li>
                              <li><a href="#"><i class="fa fa-filter"></i> Junk <span class="label label-waring pull-right">65</span></a></li>
                              <li><a href="#"><i class="fa fa-trash-o"></i> Trash</a></li> -->
                        </ul>
                    </div><!-- /.box-body -->
                </div>
            </div><!-- /.col -->
            <div class="right-sidebar-wrap mail-read">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Read Mail</h3>
                        <div class="pull-right">
                            <a class="btn btn-box-tool action subscribe primary"
                               href="<?php echo $this->getUrl(); ?>csmessaging/frontend/customercompose?id=<?php echo $chat->getVendorId() ?>">Reply</a>
                            <a class="btn btn-box-tool action subscribe primary"
                               onClick="history.go(-1);return true;"><span></span><<</span>Back</a>
                        </div>
                        </br>
                        <div class="clear"></div>
                    </div>
                    <div class="box-body no-padding">
                        <div class="mailbox-read-info">
                            <h3><?php echo $chat->getSubject(); ?></h3></br>

                            <h5><?php //echo $chat->getReceiverEmail(); ?> <span
                                        class="mailbox-read-time pull-right"><?php echo $newDate; ?></span></h5><br>
                        </div><!-- /.mailbox-read-info -->
                        <!-- /.mailbox-controls -->
                        <div class="mailbox-read-message">
                            <?php echo $chat->getMessage() ?>
                        </div><!-- /.mailbox-read-message -->
                    </div><!-- /.box-body -->
                    <div class="box-footer">
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

