<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMessaging
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

$collection = $this->getCollection();
$adminInboxCount = $this->_messagingHelper->getCustomerInboxCountForAdmin();
$vendorInboxCount = $this->_messagingHelper->getCustomerInboxCountForVendor();
?>
<style>

    .page-title-wrapper {
        display: none;
    }


</style>


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header content-header-wrap ">
        <h3>
            <?php echo __('Customer Vendor & Admin Conversation Area') ?>
        </h3>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="left-sidebar-wrap">
                <div class="box-header with-border box-folder">
                    <h3 class="box-title">Folders</h3>
                </div>

                <div class="box box-solid">

                    <div class="box-body no-padding">
                        <ul class="nav nav-pills nav-stacked">
                            <li>
                                <a href="<?php echo $this->getUrl('csmessaging/frontend/customercompose');//Mage::getUrl('csvendorchat/frontend/customercompose')?>"
                                   class="btn btn-block margin-bottom compose-tab">Compose</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->getUrl('csmessaging/frontend/inbox');//Mage::getUrl('csvendorchat/frontend/inbox')?>"><?php echo __('Vendor Inbox'); ?>
                                    <span class="label label-primary pull-right"><?php if ($vendorInboxCount > 0) {
                                            echo '(';
                                            echo $vendorInboxCount;
                                            echo ')';
                                        } ?></span></a></li>
                            <li>
                                <a href="<?php echo $this->getUrl('csmessaging/frontend/admininbox'); ?>"> <?php echo __('Admin Inbox'); ?>
                                    <span class="label label-primary pull-right"><?php if ($adminInboxCount > 0) {
                                            echo '(';
                                            echo $adminInboxCount;
                                            echo ')';
                                        } ?></span></a></li>
                            <li class="active"><a
                                        href="<?php echo $this->getUrl('csmessaging/frontend/sent');//Mage::getUrl('csvendorchat/frontend/sent')?>"
                                        class="sent-mail-tab">Sent</a></li>

                        </ul>
                    </div><!-- /.box-body -->
                </div>
            </div><!-- /.col -->
            <div class="right-sidebar-wrap mail-send">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Sent Box</h3>
                        <?php echo $this->getPagerHtml(); ?>
                        <div class="clear"></div>
                    </div><!-- /.box-header -->
                    <div class="box-body no-padding">
                        <?php if (!$collection->count()): ?>
                            <p class="note-msg"><?php echo __('There are no sent items.') ?></p>
                        <?php else: ?>

                            <div class="table-responsive mailbox-messages">
                                <table class="table table-hover table-striped">
                                    <tbody>
                                    <?php if ($collection->getSize()): ?>
                                        <?php foreach ($collection as $msg => $value): ?>
                                            <tr>

                                                <!--                           <td class="mailbox-star"><a href="#"><i class="fa fa-star text-yellow"></i></a></td>
                                                 -->
                                                <td class="mailbox-name"><a
                                                            href="<?php echo $this->getUrl();//Mage::getBaseUrl()?>csmessaging/frontend/read?id=<?php echo $value['chat_id'] ?>"><?php echo $value['receiver_name'] ?></a>
                                                </td>
                                                <td class="mailbox-subject"><b><?php echo $value['subject'] ?></td>
                                                <td class="mailbox-subject"></b><?php echo substr($value['message'], 0, 16); ?>
                                                    ...
                                                </td>
                                                <td class="mailbox-attachment"></td>
                                                <td class="mailbox-date"><?php echo date("d-F-Y H:m:s", strtotime($value['time'])) ?></td>
                                            </tr>
                                        <?php endforeach ?>
                                    <?php endif; ?>
                                    </tbody>
                                </table><!-- /.table -->
                            </div><!-- /.mail-box-messages -->
                        <?php endif; ?>
                    </div><!-- /.box-body -->
                    <div class="box-footer no-padding">
                    </div>
                </div><!-- /. box -->
            </div><!-- /.col -->
            <div class="clear"></div>
        </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

