<?php
 /**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 *
 */
?>

<?php

      $this->_getSingtoneSession()->setCurrentPage($this->getCurrentUrl());

 ?>
<?php $check = $this->getShownPositions();?>

<?php $arrayButton = $this->makeArrayButton(); $temp = $arrayButton; ?>
<?php $numberShow = $this->getNumberShow();?>

<?php $countAll = 0;?>
<?php $countMain = 0;?>
<?php $count = 0;?>	

	<div id="magestore-popup">
        <div class="border-popup">
		<div id="sociallogin-close-popup" title="Close"></div>
		<div id="magestore-login-form">
			<h3 class="magestore-loign-h3"><?php echo $block->escapeHtml(__("Sign in")) ?></h3>
			<div id="sociallogin-forgot">
				<span class="sociallogin-forgot-content"><?php echo $block->escapeHtml(__('Please enter your email below and we will send you a new password.')) ;?></span>
			</div>
			<!-- formm Login -->
			<form id="magestore-sociallogin-form" class="magestore-login-form-popup"
			>
				<!-- email -->
				<div class="magestore-login-input-box">
					
					<div class="sociallogin-input-box">
					<label class="required login-label" for="email">
						<?php echo $block->escapeHtml(__('Email Address ')) ;?> 
					</label>
						<input id="magestore-sociallogin-popup-email" class="input-text required-entry validate-email" type="text" title="<?php echo $block->escapeHtml(__('Email Address')) ?>" value="" name="socialogin_email">
					</div>
				</div>
				<!-- password -->
				<div id="magestore-sociallogin-password" class="magestore-login-input-box">
					
					<div class="sociallogin-input-box">
					<label class="required login-label" for="pass">
						<?php echo $block->escapeHtml(__('Password ')) ;?> 
					</label>
						<input type="password" id="magestore-sociallogin-popup-pass" class="input-text required-entry validate-password" type="text" title="<?php echo $block->escapeHtml(__('Password ')) ;?> " value="" name="socialogin_password">
					</div>
				</div>
				<!-- image ajax -->
				<div id="progress_image_login" class="ajax-login-image" style="display: none">					
				</div>
				<!-- error invalid email -->
				<div id="magestore-invalid-email" class="magestore-invalid-email"></div>
				<!-- sumbit -->
				
				<div class="magestore-login-popup-button">
					<button id="magestore-button-sociallogin" class="button popup_click_btn" name="send" title="<?php echo $block->escapeHtml(__('Login'))?>" type="button">
						<span><span><?php echo $block->escapeHtml(__('Login'))?></span></span>
					</button>
					<div class="pass-register" >
					<a id="magestore-forgot-password" href="javascript:void(0);"><?php echo $block->escapeHtml(__('Forgotten?'))?></a>
					<span style="float: left">&nbsp; | &nbsp;</span>
					<a id="magestore-sociallogin-create-new-customer" href="javascript:void(0);"><?php echo $block->escapeHtml(__('Register Now')) ?></a>
					</div>
				</div>
			</form>		
			<!-- form forgot -->
			<form id="magestore-sociallogin-form-forgot" class="magestore-login-form-popup" style="display: none">
				<div class="magestore-login-input-box">
					
					<div class="sociallogin-input-box">
						<label class="required login-label" for="email">
							<?php echo $block->escapeHtml(__('Email Address '));?>
						</label>
						<input id="magestore-sociallogin-popup-email-forgot" class="input-text required-entry validate-email" type="text" title="Email Address" value="" name="socialogin_email_forgot">						
					</div>
				</div>
				<!-- image ajax -->
				<div id="progress_image_login_forgot" class="ajax-login-image" style="display: none">					
				</div>
				<!-- error invalid email -->
				<div id="magestore-invalid-email-forgot" class="magestore-invalid-email"></div>
				<!-- sumbit -->
				<div class="magestore-login-popup-button">	
				<button id="magestore-button-sociallogin-forgot" class="button popup_click_btn" title="<?php echo $block->escapeHtml(__('Send Password'));?>" type="button">
						<span><span><?php echo $block->escapeHtml(__('Send Password'))?></span></span>
					</button>				
					<a id="magestore-forgot-back" href="javascript:void(0);"><?php echo $block->escapeHtml(__('Back to Form Login')) ?></a>
					
				</div>
			</form>						
		</div>	
		
		<!-- create new user -->		
		<div id="magestore-create-user" style="display: none" >
			<h3 class="magestore-loign-h3"><?php echo $block->escapeHtml(__("Create New Account")) ?></h3>
			<form id="magestore-sociallogin-form-create" class="magestore-login-form-popup">		
				<ul class="form-list">
					<li class="fields">				
						<div class="name-firstname sociallogin-field form-group">
							<label class="required" for="firstname"><?php echo $block->escapeHtml( __('First Name '));?></label>
							<div class="input-box">
								<input id="socialogin.firstname" class="input-text required-entry" type="text" title="<?php echo $block->escapeHtml( __('First Name '));?>" value="" name="firstname">
							</div>
						</div>
						<div class="name-lastname sociallogin-field  form-group right">
							<label class="required" for="lastname"><?php echo $block->escapeHtml(__('Last Name '));?></label>
							<div class="input-box">
								<input id="socialogin.lastname" class="input-text required-entry" type="text" title="<?php echo $block->escapeHtml(__('Last Name '));?>" value="" name="lastname">
							</div>
						</div>
					</li>
					<li class="fields">
						<div class="sociallogin-field  form-group email">
							<label class="required" for="email"><?php echo $block->escapeHtml(__('Email '));?></label>
							<div class="input-box">
								<input id="socialogin.email" class="input-text required-entry validate-email" type="text" title="<?php echo $block->escapeHtml(__('Email '));?>" value="" name="email">
							</div>
						</div>
					</li>
					<li class="fields">
						<div class="form-group sociallogin-field">
							<label class="required" for="pass"><?php echo $block->escapeHtml(__('New Password '));?></label>
							<div class="input-box">
								<input id="socialogin.pass" class="input-text required-entry validate-password" type="password" title="<?php echo $block->escapeHtml(__('New Password '));?>" value="" name="pass">
							</div>
						</div>
						<div class="sociallogin-field  form-group  right">
							<label class="required" for="pass-confirm"><?php echo $block->escapeHtml(__('Confirm Password'));?></label>
							<div class="input-box">
								<input id="socialogin.pass.confirm" class="input-text required-entry validate-cpassword" type="password" title="<?php echo $block->escapeHtml(__('Confirm Password'));?>" value="" name="passConfirm">
							</div>
						</div>
					</li>
				</ul>
				<!-- image ajax -->
				<div id="progress_image_login_create" class="ajax-login-image" style="display: none">					
				</div>
				<!-- error invalid create ACC -->
				<div id="magestore-invalid-create" class="magestore-invalid-email"></div>
				<div class="magestore-create-popup-button">					
					
					<button id="magestore-button-sociallogin-create" class="button popup_click_btn" title="<?php echo $block->escapeHtml(__('Submit'));?>" type="button">
						<span><span><?php echo $block->escapeHtml(__('Submit'))?></span></span>
					</button>
					<a id="magestore-create-back" href="javascript:void(0);">
							<?php echo $block->escapeHtml(__('Back to Form Login') )?>
					</a>
				</div>
			</form>
		</div>
		<!-- end code create account -->
		<!-- social login -->
		<div id="magestore-login-social">
			<h3 class="magestore-loign-h3"><?php echo $block->escapeHtml(__("Sign in with"));?></h3>
			<!-- default -->
			<ul class="magestore-login-social">
			<?php foreach($arrayButton as $key => $button):?>	
				<?php $check =$button['check'];?>
				<?php if($check): unset($temp[$key]);?>					
					<li class="button popup"> <?php echo $button['button']?> </li>
					
					<script type="text/javascript">
									require([
									'prototype' 
									], function  () {
										
										if($('<?php echo $button['id'] ?>' ))
										$('<?php echo $button['id'] ?>').addClassName('visible');
									});
					</script>	
					<?php ++$countMain ;?>			
				<?php endif;?>
				<?php if($countMain == $numberShow){break;} ?>
			<?php endforeach;?>  		
			</ul>			
		</div>		
		
		<?php if(count($temp)):?>
			<?php $noEmpty = false;?>
			<?php foreach($temp as $tem):?>
			<?php if($tem['check']):?>
			<?php $noEmpty = true;?>
			<?php endif;?>
			<?php endforeach;?>
			<?php if($noEmpty):?>
			<!-- other login -->
			<div class="sociallogin-other"  style="text-align: right;">
				<div id="sociallogin-other-div-popup">
					<div id="sociallogin-other-div-popup-hover" style="float: right; display: block;">
						<a id="sociallogin-other-a-popup" style="text-decoration: none;"><span class="sociallogin-other-span"><?php echo __('Other Login') ?></span><span class="sociallogin-other-span-img-popup"></span></a>										
						
						<ul class="sociallogin-other-button-popup" id="sociallogin-other-button-popup" style="display:none;">
						<?php foreach($temp as $button):?>				
							<?php $check = $button['check']; ?>
							<?php if($check): $count ++;?>				
								<li class="button other-button"> <?php echo $button['button'] ?> </li>
								<script type="text/javascript">
									require([
									'prototype' 
									], function  () {
										
										$('<?php echo $button['id'] ?>').addClassName('non-visible');
									});
								</script>					
							<?php endif;?>			
						<?php endforeach;?>  
						</ul>
					</div>					
				</div>
			</div>	
				

			<?php endif; ?>
			<?php endif; ?>
        </div>
	</div>

	<script type="text/javascript">
	try{
		<?php if (in_array("popup", $this->getShownPositions())):?>
		require(['prototype',
			'Magestore_Sociallogin/js/lightbox'
			], function  () {
	
	});	
		<?php endif; ?>

	}catch(exception)
	{ 
		alert(exception);
	}		
	</script>
	
	<script type="text/javascript">
	require(['Magestore_Sociallogin/js/popuplogin','prototype' ], function( LoginPopup){
		Event.observe(window, 'load', function() {
			var options = {                 
	            login_url  : "<?php echo $block->escapeHtml($this->getPopupLoginUrl());?>",
	            send_pass_url : "<?php echo $block->escapeHtml($this->getPopupSendPass()) ;?>",
	            create_url : "<?php echo $block->escapeHtml($this->getPopupCreateAcc()) ;?>",
	            baseurl :"<?php echo $block->escapeHtml($this->getBaseUrl());?>"
	        };
	        Login = new LoginPopup(options);
		});
	});
	</script>

