<?php 
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_AdvanceConfigurable
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
$json = json_decode($block->getJsonConfig());
$configurable = $block->getsingleconfigurableoption();
$_product    = $block->getProduct();
if($block->isEnabled()){
if($_product->getShowMatrix()){
$attributes = $_product->getTypeInstance(true)->getConfigurableAttributesAsArray($_product);
$productAttributesOptions = $_product->getTypeInstance(true)->getConfigurableOptions($_product);
$previous = $this->getViewFileUrl('Ced_AdvanceConfigurable::images/new/previous.png');
$next = $this->getViewFileUrl('Ced_AdvanceConfigurable::images/new/next.png');
?>
<style>
element.style {
    -moz-user-select: none;
    max-height: 400px;
    overflow: auto;
    white-space: nowrap;
}
</style>
<form id="matrix-form" method="post">
<div class="product-matrix">
	<div id="error_message" class="error_message" style="display:none;color:red;"></div>
    <div class="prev" style="height: 42px;" id="prev">
                <img src="<?php echo $previous;?>" alt="Previous" id="tLeft" class="mnavs" width="20">
            </div>
    <div id="next" class="next" style="height: 42px;"><img src="<?php echo $next;?>" alt="Next"  class="mnavs" width="20"></div>
    
	<table id="my_table" data-tablesaw-mode="swipe" class="matrix-table">
		<tr class="heading-tr">
		<?php 
	foreach($configurable['attributes'] as $id => $attribute)
	{
		echo '<input type="hidden" value="'.$_product->getId().'" name="product">';
		echo '<input type="hidden" name="super_attribute" value="'.$id.'" />';
		foreach($attribute['options'] as $value)
		{
			echo '<td class="'.$value["label"].'">'.$value["label"].'</td>';
		}
	}
	?>
		</tr>
		<tr>
		<?php 
			foreach ($configurable['optionPrices'] as $key => $option) {
				$StockState = $objectManager->get('Magento\CatalogInventory\Api\StockStateInterface');
				$price = $objectManager->get('Magento\Framework\Pricing\Helper\Data')->currency($option["finalPrice"]["amount"],true,false);
				echo '<td><div class="div-lable">+'.$price.'</div>';
				echo '<input type="text" id="attr_'.$key.'" placeholder="'.$StockState->getStockQty($key).'" name="attr['.$configurable['index'][$key][$id].']" class="qty" min="0" max="'.$StockState->getStockQty($key).'" >';
				echo '<div class="qty-available">'.$StockState->getStockQty($key).'</div></td>';
			}

		?>
        
		</tr>
	</table>

	<div class="spinner" style="display:none;">
            <img alt="Loading..." src="<?php echo $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_STATIC) ?>frontend/Magento/luma/en_US/images/loader-1.gif">
    </div>
</div>
<div class="actions">
	    <button id="add" class="action primary tocart" title="Add to Cart" type="button">
	        <span>Add to Cart</span>
	    </button>
	    <div class="validation_message">
	    </div>
	</div>
</form>
<script>
require([
		'mage/url',
		'jquery'
	], function() {
		jQuery(".fieldset>div.configurable").remove();
		jQuery('.product-options-bottom').remove();	
	});
</script>
<?php }?>
<?php }?>
	
<script>
require([
         "jquery",
         'mage/mage'
    ], function(jQuery){
    	var validation = false;
    	var dataForm = jQuery('#matrix-form');
        jQuery("#add").click(function () {
        		jQuery('#my_table .qty').each(function(){
				    if(((jQuery.isNumeric(this.value)) && (this.value > 0) && (Math.floor(this.value) == this.value)))
				    {
				    	validation = true;
				    }
				   
				});
				if(validation == true){
					jQuery('.spinner').css('display','block');
					jQuery('.validation_message').html('<span style="color:green">Please wait. Adding item(s) to cart..</span>');
					jQuery('button').attr('disabled','disabled');
					var formData = jQuery('#matrix-form').serializeArray();
					jQuery.ajax({
						type: 'POST',
						url: '<?php echo $this->getUrl("advanceconfig/cart/add")?>',
						data: formData,
						success: function (data) {
		                	jQuery('.spinner').css('display','none');
							jQuery('button').prop("disabled", false);
							jQuery('.validation_message').hide();
			            }
					})
				}
				else
				{
					jQuery('.validation_message').html('<span style="red:green">Please specify valid options.</span>');
				}
      });

	jQuery('.qty').keyup(function(event){
	 	var max_qty = jQuery(this).attr('max');
	 	max_qty = parseInt(max_qty);
	 	if((this.value <= max_qty) && (this.value > 0) && (Math.floor(this.value) == this.value))
	 	{
	 		jQuery(this).css('border-color','green');
	 		jQuery('#error_message').hide();
	 		jQuery('.qty').not(this).prop('disabled',false);
	 		jQuery('#add').prop('disabled',false);
	 	}
	 	else if(!this.value){}
	 	else if((!jQuery.isNumeric(this.value)) || (this.value < 0) || (Math.floor(this.value) != this.value))
	 	{
	 		alert(this.value);
	 		jQuery('#error_message').html('Please enter positive value for quantity.');
	 		jQuery('#error_message').show();
	 		jQuery('.qty').not(this).attr('disabled','true');
	 		jQuery(this).css('border-color','red');
	 		jQuery('#add').attr('disabled','true');
	 	}
	 	else if(this.value == 0 )
	 	{
	 		jQuery(this).css('border-color','#c2c2c2');
	 		jQuery('#add').prop('disabled',false);
	 		jQuery('.qty').not(this).prop('disabled',false);
	 		jQuery('#error_message').hide();
	 	}
	 	else
	 	{
	 		jQuery(this).css('border-color','red');
	 		jQuery('#error_message').html('Requested quantity is not available. Maximum stock available is '+max_qty+' !');
	 		jQuery('#error_message').show();
	 		jQuery('.qty').not(this).attr('disabled','true');
	 		jQuery('#add').attr('disabled','true');
	 	}
	});
});
</script>	
<script>
require([
         "jquery",
         'mage/mage'
    ], function(jQuery){
        jQuery('#prev').fadeOut();
        var total = jQuery( "#my_table tr:first td" ).length;
         var current = 3;
    if(total <= 3){
    	jQuery('#next').hide();
    	jQuery('#prev').hide();
    }
    else{
	    jQuery('#prev').click(function(event){
	        //jQuery('#next').fadeOut();
	        jQuery('#next').fadeIn();
	        if(current > 3)
	        {
	            jQuery('#my_table').css('margin-left','+=165px');
	            current-=1;
	            if(current == 3)
	            {
	                jQuery('#prev').fadeOut();
	                jQuery('#next').fadeIn();
	            }
	        }
	        
	    });
	     jQuery('#next').click(function(event){
	        //jQuery('#prev').fadeOut();
	        jQuery('#prev').fadeIn();
	        if(current < total)
	        {
	            jQuery('#my_table').css('margin-left','-=165px');
	            current+=1;
	            if(current == total)
	            {
	                jQuery('#next').fadeOut();
	                jQuery('#prev').fadeIn();
	            }
	        }

	        
	        
	    });
 	}
});
</script>
<style type="text/css">
.product-info-main form {
  position: relative;
}
.product-matrix .prev {
  left: -31px;
  top: 74px;
}
.product-matrix .next {
  top: 74px;
  right: -31px;
}
</style>

