<?php 
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMultistepregistration
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

$vendorId = $this->request->get('id');
$collection = $this->getcollection();
$counter = 0;
$count = 0;
$vmodel = $this->vendorData;
$bar = 10;

if(!empty($collection)){
	$count=$collection->count();
}

if ($count > 0) { ?>
	
	<div class="col-md-offset-2 col-md-8 col-lg-offset-2 col-lg-8 col-sm-8 col-sm-offset-2">
	<div class="multistep-wrapper">
		<div class="register-panel panel panel-default">
			<div id="myProgress">
			  <?php foreach ($collection as $step_no) {?>
					<li id="bar_<?php echo $bar?>" class="waiting">
						<span tittle="<?php echo __($step_no->getStepLabel())?>">

						</span>
						<strong><?php echo __($step_no->getStepLabel())?></strong>
					</li>
				<?php $bar++; }?>
			</div>
		</div>
		
		<div class="register-panel panel panel-default form-section">
			<div class="panel-body">
				<div id="show_required"></div>
				<form action="<?php echo $block->getUrl('csmultistep/multistep/save');?>" method="post" id="vendor-validate" enctype="multipart/form-data">
					<input name='form_key' type='hidden' value= "<?php echo $block->getBlockHtml('form_key')?>"/>
					<input name="vendor_id" type="hidden" value="<?php echo $vendorId ?>"/>
					<input name="vendor[multistep_done]" type="hidden" value="<?php echo true ?>"/>
				<fieldset>
					<div class="panel panel-default">
						<?php
						$stepCount = 1; 

						foreach ($collection as $steps) {
							$attribute_coll = $this->getStepattributes($steps->getStepNumber());
							$attribute_count = 2;//$attribute_coll->count();

							?>
							<div id="step_<?php echo $stepCount?>" class="step" style='display: none'>
								<?php 
									if ($attribute_count >= 1) {
										if(!$attribute_coll)
											continue;
								    	foreach ($attribute_coll as $attr) {
											$inputType = $attr->getFrontend()->getInputType();
											$required_attr = $attr->getIsRequired();
											$attribute_class = $attr->getFrontendClass();
											
											if ($inputType == 'image') {
												$inputType = 'file';
											}
								?>
										<div class="input-box">
											<label class="<?php if ($required_attr){ /* echo "label_required"; */}?>"><?php echo $attr->getFrontend()->getLabel()?><span><?php if($required_attr){ echo "*";};?></span></label>
											<?php if ($inputType == 'select') {
												
												?>
												<select id="<?php echo $attr->getAttributeCode()?>"  name="vendor[<?php echo $attr->getAttributeCode()?>]" class="validate-select <?php if ($required_attr){ echo "required-entry".$stepCount; echo " required-entry";}?> <?php echo $attribute_class;?>">
													<?php $c = 1;  
													
													//foreach ($attr->getSource()->getAllOptions(false) as $opt) {
													foreach ($attr->getSource()->getAllOptions(true,true) as $key => $opt) {
														if($key == 0)
															continue;
														?>
														<option value="<?php echo $c;?>"  <?php if(isset($vmodel[$attr->getAttributeCode()]) && $opt['value'] == $vmodel[$attr->getAttributeCode()]){echo 'selected';}?> ><?php echo $opt->getText()?></option>
													<?php $c++;}?>
												</select>
											<?php  }
											else if ($inputType == 'multiselect') {
											?>
												<select id="<?php echo $attr->getAttributeCode()?>" name="vendor[<?php echo $attr->getAttributeCode()?>][]" class="select multiselect <?php if ($required_attr){ echo "required-entry".$stepCount; echo " required-entry";}?> <?php echo $attribute_class; ?>" multiple="multiple">
													<?php foreach ($attr->getSource()->getAllOptions(true,true) as $key=>$opt) {
															if($key == 0)
																continue;
															?>
														?>
														<option value="<?php echo $opt['value'];?>" <?php if(isset($vmodel[$attr->getAttributeCode()]) && $opt['value'] == $vmodel[$attr->getAttributeCode()]){echo 'selected';}?>><?php echo _($opt['label'])?></option>
													<?php }?>
												</select>
											<?php  }

											elseif($inputType == 'date'){
												?>
												<input type="text"  name="vendor[<?php echo $attr->getAttributeCode()?>]" id="<?php echo $attr->getAttributeCode()?>" 
													value="<?php if(isset($vmodel[$attr->getAttributeCode()])){echo $vmodel[$attr->getAttributeCode()];}?>" 
													title="<?php echo $attr->getFrontend()->getLabel() ?>" placeholder="<?php echo $attr->getFrontend()->getLabel() ?>" class="<?php if ($required_attr){ echo "required-entry".$stepCount; echo " required-entry";}?> <?php echo $attribute_class?> calendarInput"
													>
												<?php
											}	

											 else {?>
												<input mage-validate = {""}placeholder="<?php echo $attr->getFrontend()->getLabel() ?>" type="<?php echo $inputType?>" name="vendor[<?php echo $attr->getAttributeCode()?>]" id="<?php echo $attr->getAttributeCode()?>" 
													value="<?php if(isset($vmodel[$attr->getAttributeCode()])){echo $vmodel[$attr->getAttributeCode()];}?>" 
													title="<?php echo $attr->getFrontend()->getLabel() ?>"
													<?php if ($attr->getAttributeCode() == 'email' || $attr->getAttributeCode() == 'shop_url'){echo 'readonly';}?>
													class="<?php if ($required_attr){ echo "required-entry".$stepCount; echo "  required-entry";}?> <?php echo $attribute_class?> "
												/>
											<?php }?>
											
										</div>
									<?php } ?>
										<div class="buttons-set">
										<input type="button" <?php if($stepCount == 1){echo 'disabled';}?>  id="<?php echo $stepCount?>" class="uptransform button btn btn-success back" value="<?php echo __('Back') ?>"/>
										<button type="button" title="Log Out" style="float:left" class="uptransform button btn btn-success" onclick=" location.href = '<?php echo $block->getUrl('csmarketplace/account/logout/',array('_secure'=>true));?>'">Log Out</button>
										<?php
											if($stepCount == $count){
											?>
												<input type="submit" value = 'submit' id="step<?php echo $steps->getId()?>_next" class="uptransform button btn btn-success btnSubmit_form" value="<?php echo __('Submit') ?>"/>
											<?php 
											}else{
											?>
												<input type="button" id="<?php echo $stepCount?>" class="uptransform button btn btn-success next btnSubmit_form" value="<?php echo __('Next') ?>"/>											
											<?php 	
											}	
										?>
							    	</div>
								<?php 	}else{
									?>
									<div class="buttons-set">
										<input type="button" <?php if($stepCount == 1){echo 'disabled';}?>  id="<?php echo $stepCount?>" class="uptransform button btn btn-success back" value="<?php echo __('Back') ?>"/>
										<button type="button" title="Log Out" style="float:left" class="uptransform button btn btn-success" onclick=" location.href = '<?php echo $block->getUrl('csmarketplace/account/logout/',array('_secure'=>true));?>'">Log Out</button>
										<input type="button" id="<?php echo $stepCount?>" class="uptransform button btn btn-success next btnSubmit_form" value="<?php echo __('Next') ?>"/>
									</div>
									<?php 

								} 
									?>
							</div>
						<?php $stepCount++; }?>
					</div>					
				</fieldset>
				</form>
			</div>
		</div>
	</div>
	</div>

<?php }else { ?>
	<script type="text/javascript">location.href = '<?php echo $block->getBaseUrl().'marketplace/vendor/index';  ?>';</script>
<?php }?>
<script>
	var validationPassed = true;
</script>
<script type="text/javascript">
require(['jquery'], function($){ 
	var $ = jQuery.noConflict();
	var valid = true;
	if(jQuery('#step_1').length){
		var bar = 10;
		jQuery('#step_1').show();
		jQuery('#bar_10').removeClass('waiting');
		jQuery('#bar_10').addClass('active');
	}
	
	jQuery('.next').click(function() {
		valid = true;
		var id = parseInt(jQuery(this).attr('id'));
		jQuery(".error").remove();
		jQuery('.required-entry'+id).each(function () {
			jQuery(this).removeClass('validation-failed');
			if(!jQuery.trim(jQuery(this).val())) {
				jQuery(this).addClass('validation-failed');
			    	jQuery('<div class="validation-advice error" id="advice-required-entry-pass">This is a required field.</div>').
					insertAfter(this);
					valid = false;
		    }
		});
		

		var inputs = jQuery("#step_"+id+" :input");
		inputs.each(function(){
			//console.log(jQuery(this).attr('id'));
			if(jQuery(this).hasClass('validate-number')){
				var val = jQuery(this).val();
				var regexp = /^\d+\.\d{0,2}$/;	
				if(!regexp.test(val)){
					if(!/^\d*$/.test(val)){
						jQuery(this).addClass('validation-failed');
				    	jQuery('<div class="validation-advice error" id="advice-required-entry-pass">Enter A Valid Number.</div>').
						insertAfter(this);
						valid = false;
					}
				}
			}else if(jQuery(this).hasClass('validate-digits')){
				jQuery(this).removeClass('validation-failed');
				var val = jQuery(this).val();
				if(!/^\d*$/.test(val)){
					jQuery(this).addClass('validation-failed');
			    	jQuery('<div class="validation-advice error" id="advice-required-entry-pass">Enter Valid digits.</div>').
					insertAfter(this);
					valid = false;
				}
			}else if(jQuery(this).hasClass('validate-email')){
				jQuery(this).removeClass('validation-failed');
				//var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
				var re = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
				var val = jQuery(this).val();
				
				if(val != '' || val != null || val.length != 0){
				}else{
					if(!re.test(val)){
	    				jQuery(this).addClass('validation-failed');
				    	jQuery('<div class="validation-advice error" id="advice-required-entry-pass">Please Enter Valid Email.</div>').
						insertAfter(this);
						valid = false;
    				}	
				}
    			
			}else if(jQuery(this).hasClass('validate-url')){
				jQuery(this).removeClass('validation-failed');
				var regexUrl = '/^(http|https|ftp):\/\/(([A-Z0-9]([A-Z0-9_-]*[A-Z0-9]|))(\.[A-Z0-9]([A-Z0-9_-]*[A-Z0-9]|))*)(:(\d+))?(\/[A-Z0-9~](([A-Z0-9_~-]|\.)*[A-Z0-9~]|))*\/?$/i';
				
				var val = jQuery(this).val();
				if(!regexUrl.test(val)){
					jQuery(this).addClass('validation-failed');
			    	jQuery('<div class="validation-advice error" id="advice-required-entry-pass">Please Enter Valid Url.</div>').
					insertAfter(this);
					valid = false;
				}
			}else if(jQuery(this).hasClass('validate-alpha')){
				jQuery(this).removeClass('validation-failed');
				var regexAlpha = /^[a-zA-Z]+$/;
				var val = jQuery(this).val();
				if(!regexAlpha.test(val)){
					jQuery(this).addClass('validation-failed');
			    	jQuery('<div class="validation-advice error" id="advice-required-entry-pass">Please Enter Valid Alphabets.</div>').
					insertAfter(this);
					valid = false;
				}
			}else if(jQuery(this).hasClass('validate-alphanum')){
				jQuery(this).removeClass('validation-failed');
				var regexAlphanum = /^[a-zA-Z0-9]+$/;
				var val = jQuery(this).val();
				if(!regexAlphanum.test(val)){
					jQuery(this).addClass('validation-failed');
			    	jQuery('<div class="validation-advice error" id="advice-required-entry-pass">Please Enter Valid Alphabets And Numbers.</div>').
					insertAfter(this);
					valid = false;
				}
			}

		});


		if(valid) {
			var current = parseInt(jQuery(this).attr('id'));
			var next = current + 1;
			var bar_current = bar;
			var bar_next = bar_current + 1;
			bar = bar_next;
			
			jQuery('#step_'+next).show();
			jQuery('#step_'+current).hide();
			jQuery('#bar_'+bar_current).removeClass('active');
			jQuery('#bar_'+bar_next).removeClass('waiting');
			jQuery('#bar_'+bar_current).addClass('done');
			jQuery('#bar_'+bar_next).addClass('active');
		}
	});

	jQuery('.back').click(function() {
		var current = parseInt(jQuery(this).attr('id'));
		var prev = current - 1;
		bar_current = bar;
		bar_prev = bar_current - 1;
		bar = bar_prev;
		jQuery('#step_'+prev).show();
		jQuery('#step_'+current).hide();
		jQuery('#bar_'+bar_current).removeClass('active');
		jQuery('#bar_'+bar_prev).removeClass('done');
		jQuery('#bar_'+bar_current).addClass('waiting');
		jQuery('#bar_'+bar_prev).addClass('active');
	});	


	});
	
</script>
<script>
     require([
          "jquery",
          "mage/calendar"
     ], function($){
         $(".calendarInput").calendar({
              buttonText:"<?php echo __('Select Date') ?>",
         });
       });
</script>

<script>
/*require([
'jquery', 
'jquery/ui',
'jquery/validate',
'mage/translate'
], function($){ 
	$('.btnSubmit_form').click(function(event) {
		console.log('inside');
		$.validator.addMethod(
		'validate-digits', function (value) { 
		return (value !== '123'); // Validation logic here
		}, $.mage.__('Invalid digit'));
	}
});
*/
</script>
<script>/*
	require([
    'jquery',
    'mage/mage',
    'jquery/validate'
], function($){

    var dataForm = $('#form-validate');
    
    $('.next').click(function(event) {
    	event.preventDefault();
    	alert('clice');
    	$.validator.addMethod('validate-digits', function (value) { 
		return (value !== '123'); // Validation logic here
		}, $.mage.__('Invalid digit'));

    });

});*/
</script>

<script type="text/x-magento-init">
    {
        "#vendor-validate": {
            "validation": {}
        }
    }
</script>
<script>
/*
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#vendor-validate');
    var ignore = null;
	console.log('in validation');
    console.log(validationPassed);
    $('.btnSubmit_form').click(function(event) {
    	/* if($('#vendor-validate').valid()){
    		alert('valid');
    	}else{
    		alert('inva');
    	} */
     /* if($('#vendor-validate').validation('isValid') && $('#vendor-validate').validation()) {
          //$("#vendor-validate").submit();
          if($(this).val() == 'submit'){
          	$("#vendor-validate").submit();
          }else{
          	validationPassed = true;
          }
      } else {
      		
      		validationPassed = false;
          return false;
      }
    });
});*/

</script>

<style>
.csmultistep-multistep-index .page-wrapper {
  width: 100% !important;
}
.csmultistep-multistep-index .page-title-wrapper {
  text-align: center;
}
</style>

