<?php
 
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_GroupBuying
 * @author 		CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
 

?>
<style>
ul{
	list-style-type:none;
}
em{
	color:red;
}
</style>
<script type="text/javascript">
bkLib.onDomLoaded(function() {
        new nicEditor({fullPanel : true}).panelInstance('short_description');
  }); 
</script>
<?php

	$allowed_guest = $this->allowed_guest;	
	$data = $this->getRequest()->getParams('Data');


	if(!$this->_coreRegistry->registry('gift_price')){
		$product = $this->_objectManager->get('Magento\Catalog\Model\Product')
					->load($this->getRequest()->getParam('id'));
						
		$data['product'] = $this->getRequest()->getParam('id');
		$data['price'] = $product->getFinalPrice();
	}
	if($data['product']){
		if($this->_coreRegistry->registry('gift_price')){
			$data['price'] = $this->_coreRegistry->registry('gift_price');
		}	
		$_storeBaseUrl = str_replace('index.php/', '', $this->getBaseUrl());
?>
<?php $email=$block->getcustomer();?>
<form id="myform" action="" method="post" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
	<div class="fieldset">
		<h2 class="legend"><?php echo __('Invite Friends !'); ?></h2>
		<ul class="form-list">
			<input type="hidden" name="original_product_id" value="<?php echo $data['product']; ?>">
			<input type="hidden" name="price" value="<?php echo trim($data['price']); ?>">
			<li class="fields">
				<label class="required" for="receiver_name"><em>*</em><?php echo __(' Group Admin Name'); ?></label>
				<div class="input-box">
					<input id="receiver_name" class="required-entry" type="text" name="receiver_name" value=""  maxlength="100">
				</div>
			</li>
			<li class="fields" >
				<label> <?php echo __('Group Admin Email'); ?></label>
				<div class="input-box" id="gift_email_suggets">
					<input id="gift_receiver_email" class="input-text validate-email required-entry" type="text" name="gift_receiver_email" value="<?php echo $email ;?>"  autocomplete="off" readonly/>
				</div>
			</li>
			<li class="control">
				<div class="input-box">
				<input id="notify_customer" class="checkbox" type="checkbox" value="1" title="Notify Receiver" name="notify_customer">
				</div>
				<label for="notify_customer"> <?php echo __('Notify Admin'); ?></label>
			</li>
			<li class="fields">
				<label class="required" for="show_contribution_to_guest"><em>*</em><?php echo __('Show Contribution To Friends'); ?></label>
				<div class="input-box">
					<select id="show_contribution_to_guest" class="required-entry" name="show_contribution_to_guest">
						<option value="0"><?php echo __('No'); ?></option>
						<option value="1"><?php echo __('Yes'); ?></option>
					</select>
				</div>
			</li>
			
		</ul>
	</div>
	<div class="fieldset">
		<h2 class="legend"><?php echo __('Invite The Guest '); ?></h2>
		<ul class="form-list">
			<li class="fields"> 
				<div id="TextBoxesGroup">
					<div id="user" class="guest_count">
						<span><?php echo __('Name'); ?></span>
						<input type="text" name="uname[]" />
						<span><?php echo __('Email Address'); ?></span>
						<input type="text" name="email[]" class="validate-email"/>
					</div>
				</div>
				<br>
				<span id="add">+ ADD ANOTHER EMAIL</span>
				<br>
			</li>
			<li class="fields">
				<label for="gift_msg"><?php echo __('Gift Message'); ?></label>
				<div class="input-box" style="width: 300px;">
					<textarea  id="short_description" class="input-text short_description textarea" cols="5" rows="2" name="gift_msg" ></textarea>
				</div>
			</li>
		</ul>
		<button class="button"><span><?php echo __('Submit'); ?></span></button>
		<div id="display_msg" style="color:green;"></div>
	</div>
</form>
<?php } else { ?>
	<div><?php echo __('You have not select any product for Group Buy. Please Select product'); ?> </div>
<?php } ?>

<script type="text/x-magento-init">
    {
        "#myform": {
            "validation": {}
        }
    }
</script>

<script>

require([
         "jquery",
         'mage/mage'
    ], function(gGift){
    	var dataForm = jQuery('#myform');
    	var guest_count = '<?php echo $allowed_guest; ?>';
    	var counter = 1;
        gGift("#add").click(function () {
			var x = document.getElementsByClassName("guest_count").length;
			if(guest_count > x){
				var newTextBoxDiv = gGift(document.createElement('div')).attr("id", 'user' + counter).attr("class","guest_count");
			
			newTextBoxDiv.html('<br>'+'<span>Name </span> '+'<input type="text" name="uname[]" />'
			+ ' <span>Email Address </span> '+ '<input type="text" name="email[]" />'+
			'<a onclick="removeDiv(' + counter+')"><img src="<?php echo $this->getViewFileUrl('Ced_GroupBuying::images/new/del_icon.png');?>"></a>'+'<br>');
				
			newTextBoxDiv.appendTo("#TextBoxesGroup");
			counter++;
			}
			else{
				alert('Maximum allowed guest are '+guest_count);
			}
			
		 });

        var req = null;
		gGift("#gift_receiver_email").keyup(function(){
			var string = gGift("#gift_receiver_email").val();
			if (req != null) req.abort();
			if(string.length > 2){
				req = gGift.ajax({
					type: "POST",
					url: "<?php echo $this->getBaseUrl().'groupgift/registry/getcustomer'?>",
					data: {email: string},
					success: function(html){
						gGift(".eml_sugg").remove();
						var newDiv = gGift(document.createElement('div')).attr("class", "eml_sugg").attr("style", "border: 1px solid #bbafa0;");
						newDiv.html(html);				
						newDiv.appendTo("#gift_email_suggets");
					}
				});
			}else{
				gGift(".eml_sugg").remove();
			}	
		});

		gGift('#myform').submit(function(event) {
			
			var innerPane = document.getElementById('display_msg');	
			//nicEditors.findEditor('short_description').saveContent();	
			if(jQuery('#myform').validation('isValid') && jQuery('#myform').validation()) {
				gGift('button').attr('disabled','disabled');
				innerPane.innerHTML = "Your Data is Being processed..";
				var formData = gGift(this).serializeArray();
				event.preventDefault();
				gGift.ajax({
				type: 'POST',
				url: '<?php echo $this->getBaseUrl().'groupbuying/registry/submit'?>',
				data: formData,
				})
				.success (function(result){
					location.reload();
				}); 
			} else {
				return false;
			}
		});


      });

	
	function removeDiv(id) {
		jQuery("#user" + id).remove();
	} 

	function pickval(id) {
		jQuery("#gift_receiver_email").val(id);
		jQuery(".eml_sugg").remove();
	}	
   
</script>
<script>
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#myform');
    var ignore = null;

    dataForm.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        }).find('input:text').attr('autocomplete', 'off');

});
</script>
<?php die;?>
