<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMultistepregistration
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

$_htmlId      = $this->getElement()->getHtmlId();
$_htmlClass   = $this->getElement()->getClass();
$_htmlName    = $this->getElement()->getName();
$_readonly    = $this->getElement()->getReadonly();
$collection   = $this->getSteps();

$_counter = 0;
?>
<tr>
    <td class="label"><?php echo $this->getElement()->getValue() ?></td>
    <td colspan="10" class="grid questions">
        <table id="attribute-options-table" class="data border custominsight-options" cellspacing="0" cellpadding="0"><tbody>
            <tr class="headings">
                <th><?php echo $this->__('Step Number') ?></th>
                <th><?php echo $this->__('Step Label') ?></th>
                <th class="last"><button id="add_new_option_button" title="Add Option" type="button" class="scalable add" ><span><span><span><?php echo $this->__('Add Option') ?></span></span></span></button></th>
            </tr>

<?php if(!empty($collection)){ 
  
    foreach ($collection->getData() as $_item):?>

<tr class="option-row custominsight-options-row" id="options-row-<?php echo $_counter?>">
    <td>
        <input name="<?php echo $_htmlName; ?>[label][option_<?php echo $_counter ?>][step_number]" value="<?php echo $_item['step_number'] ?>" class="input-text" type="text">
    </td>

    <td>
        <input name="<?php echo $_htmlName; ?>[label][option_<?php echo $_counter ?>][step_label]" value="<?php echo $_item['step_label'] ?>" class="input-text" type="text">
    </td>
    <td class="a-left" id="delete_button_container_option_<?php echo $_counter ?>'">
        <input name="<?php echo $_htmlName; ?>[label][option_<?php echo $_counter ?>][id]" value="<?php echo $_item['id'] ?>" type="hidden">
        <input id="delete-row-<?php echo $_counter ?>" type="hidden" class="delete-flag" name="<?php echo $_htmlName; ?>[delete][option_<?php echo $_counter ?>]" value=""/>
        <button id='<?php echo "btnDeleteRow-".$_counter?>' class='btnDeleteRow' title="Delete" type="button" class="scalable delete delete-option"><span><span><span>Delete</span></span></span></button>
    </td>
</tr>
<?php 
      $_counter++;
    endforeach;} 
?>
</tbody></table>

<script type="text/javascript">

//<![CDATA[
var _form_html_row = '<tr class="option-row [module]-options-row" id="options-row-{{id}}"><td><input name="<?php echo $_htmlName; ?>[label][option_{{id}}][step_number]" value="" class="input-text" type="text"></td><td><input name="<?php echo $_htmlName; ?>[label][option_{{id}}][step_label]" value="" class="input-text" type="text"></td><td class="a-left" id="delete_button_container_option_{{id}}"><input id="delete-row-{{id}}" type="hidden" class="delete-flag" name="<?php echo $_htmlName; ?>[delete][option_{{id}}]" value=""/><button id="btnDeleteRow-{{id}}" class="btnDeleteRow" onclick="remove({{id}})" title="Delete" type="button" class="scalable delete delete-option"><span><span><span>Delete</span></span></span></button></td></tr>';

var _options_counter = <?php echo $_counter?>;
require(['jquery'], function($){
    $('#add_new_option_button').on('click', function(){
        $('#attribute-options-table').append(_form_html_row.replace(/\{\{id\}\}/ig, _options_counter));
        _options_counter++;
    });
    
    $(document).on("click", ".btnDeleteRow", function(){
        var btnId = this.id; // button ID 
        var count =  btnId.split('-')[1];
        var userConfirmation = confirm('<?= __("This Action Will Delete The Attribute On Saving"); ?>');
        if(!userConfirmation)
            return;
        if(count !== null && typeof count != undefined){
            
            console.log($('#options-row-'+count));
            $('#options-row-'+count).remove();
            //$(this).closest("#options-row-"+count).remove();

        }
    });
});


//]]>
</script>
    </td>
</tr>

