<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<?php
/* @var $block \Magento\Customer\Block\Widget\Name */
$prefix = $block->showPrefix();
$middle = $block->showMiddlename();
$suffix = $block->showSuffix();
?>
<?php if ($prefix || $middle || $suffix && !$block->getNoWrap()): ?>
    <div class="field required fullname <?php echo $block->getContainerClassName() ?>">
        <label for="<?php echo $block->getFieldId('firstname') ?>" class="label">
            <span><?php echo __('Name') ?></span>
        </label>
        <div class="input-box">
            <fieldset class="fieldset fieldset-fullname">
                <div class="fields">
                <?php endif; ?>
                <?php if ($prefix): ?>
                    <div class="field field-name-prefix<?php if ($block->isPrefixRequired()) echo ' required' ?>">
                        <div class="input-box">
                            <?php if ($block->getPrefixOptions() === false): ?>
                                <input placeholder="<?php echo $block->getStoreLabel('prefix') ?>" type="text" id="<?php echo $block->getFieldId('prefix') ?>"
                                name="<?php echo $block->getFieldName('prefix') ?>"
                                value="<?php echo $block->escapeHtml($block->getObject()->getPrefix()) ?>"
                                title="<?php echo $block->getStoreLabel('prefix') ?>"
                                class="input-text <?php echo $block->getAttributeValidationClass('prefix') ?>" <?php echo $block->getFieldParams() ?> <?php if ($block->isPrefixRequired()) echo ' data-validate="{required:true}"' ?>>
                            <?php else: ?>
                                <label class="label" for="<?php echo $block->getFieldId('prefix') ?>">
                                    <span><?php echo $block->getStoreLabel('prefix') ?></span>
                                </label>
                                <select id="<?php echo $block->getFieldId('prefix') ?>"
                                    name="<?php echo $block->getFieldName('prefix') ?>"
                                    title="<?php echo $block->getStoreLabel('prefix') ?>"
                                    class="<?php echo $block->getAttributeValidationClass('prefix') ?>" <?php echo $block->getFieldParams() ?> <?php if ($block->isPrefixRequired()) echo ' data-validate="{required:true}"' ?> >
                                    <?php foreach ($block->getPrefixOptions() as $_option): ?>
                                        <option value="<?php echo $_option ?>"<?php if ($block->getObject()->getPrefix() == $_option): ?> selected="selected"<?php endif; ?>>
                                            <?php echo __($_option) ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="field field-name-firstname required">
                    <div class="input-box">
                        <input placeholder="<?php echo $block->getStoreLabel('firstname') ?>" type="text" id="<?php echo $block->getFieldId('firstname') ?>"
                        name="<?php echo $block->getFieldName('firstname') ?>"
                        value="<?php echo $block->escapeHtml($block->getObject()->getFirstname()) ?>"
                        title="<?php echo $block->getStoreLabel('firstname') ?>"
                        class="input-text form-control <?php echo $block->getAttributeValidationClass('firstname') ?>" <?php echo $block->getFieldParams() ?> <?php if ($block->getAttributeValidationClass('firstname') == 'required-entry') echo ' data-validate="{required:true}"' ?>>
                    </div>
                </div>
                <?php if ($middle): ?>
                    <?php $isMiddlenameRequired = $block->isMiddlenameRequired(); ?>
                    <div class="field field-name-middlename<?php echo $isMiddlenameRequired ? ' required' : '' ?>">
                        <div class="input-box">
                            <input placeholder="<?php echo $block->getStoreLabel('middlename') ?>" type="text" id="<?php echo $block->getFieldId('middlename') ?>"
                            name="<?php echo $block->getFieldName('middlename') ?>"
                            value="<?php echo $block->escapeHtml($block->getObject()->getMiddlename()) ?>"
                            title="<?php echo $block->getStoreLabel('middlename') ?>"
                            class="input-text form-control <?php echo $block->getAttributeValidationClass('middlename') ?>" <?php echo $block->getFieldParams() ?> <?php echo $isMiddlenameRequired ? ' data-validate="{required:true}"' : '' ?>>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="field field-name-lastname required">
                    <div class="input-box">
                        <input placeholder="<?php echo $block->getStoreLabel('lastname') ?>" type="text" id="<?php echo $block->getFieldId('lastname') ?>"
                        name="<?php echo $block->getFieldName('lastname') ?>"
                        value="<?php echo $block->escapeHtml($block->getObject()->getLastname()) ?>"
                        title="<?php echo $block->getStoreLabel('lastname') ?>"
                        class="input-text form-control <?php echo $block->getAttributeValidationClass('lastname') ?>" <?php echo $block->getFieldParams() ?> <?php if ($block->getAttributeValidationClass('lastname') == 'required-entry') echo ' data-validate="{required:true}"' ?>>
                    </div>
                </div>
                <?php if ($suffix): ?>
                    <div class="field field-name-suffix<?php if ($block->isSuffixRequired()) echo ' required' ?>">
                        <div class="input-box">
                            <?php if ($block->getSuffixOptions() === false): ?>
                                <input placeholder="<?php echo $block->getStoreLabel('suffix') ?>" type="text" id="<?php echo $block->getFieldId('suffix') ?>"
                                name="<?php echo $block->getFieldName('suffix') ?>"
                                value="<?php echo $block->escapeHtml($block->getObject()->getSuffix()) ?>"
                                title="<?php echo $block->getStoreLabel('suffix') ?>"
                                class="input-text <?php echo $block->getAttributeValidationClass('suffix') ?>" <?php echo $block->getFieldParams() ?> <?php if ($block->isSuffixRequired()) echo ' data-validate="{required:true}"' ?>>
                            <?php else: ?>
                                <label class="label" for="<?php echo $block->getFieldId('suffix') ?>">
                                    <span><?php echo $block->getStoreLabel('suffix') ?></span>
                                </label>
                                <select id="<?php echo $block->getFieldId('suffix') ?>"
                                    name="<?php echo $block->getFieldName('suffix') ?>"
                                    title="<?php echo $block->getStoreLabel('suffix') ?>"
                                    class="<?php echo $block->getAttributeValidationClass('suffix') ?>" <?php echo $block->getFieldParams() ?> <?php if ($block->isSuffixRequired()) echo ' data-validate="{required:true}"' ?>>
                                    <?php foreach ($block->getSuffixOptions() as $_option): ?>
                                        <option value="<?php echo $_option ?>"<?php if ($block->getObject()->getSuffix() == $_option): ?> selected="selected"<?php endif; ?>>
                                            <?php echo __($_option) ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if ($prefix || $middle || $suffix && !$block->getNoWrap()): ?>
                </div>
            </fieldset>
        </div>
    </div>
<?php endif; ?>