<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMessaging
 * @author       CedCommerce Core Team <connect@cedcommerce.com >
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

$collection = $this->getCollection();
$inboxCount = $this->_messagingHelper->getVendorInboxCountForCustomer();
?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h3>
            <?php echo __('Vendor Customer Conversation Area'); ?>
        </h3>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-3 mail-box-left">

                <div class="box box-solid">
                    <div class="box-header with-border">
                        <h3 class="box-title"><?php echo __('Folders'); ?></h3>
                    </div>
                    <div class="box-body no-padding">
                        <ul class="nav nav-pills nav-stacked">
                            <li>
                                <a href="<?php echo $this->getUrl('csmessaging/customer/customer');?>"
                                   class=""><?php echo __('Compose'); ?></a>
                            </li>
                            <li class="active"><a
                                        href="<?php echo $this->getUrl('csmessaging/customer/inbox');?>"><i
                                            class="fa fa-inbox"></i><?php echo __('Inbox'); ?><span
                                            class="label label-primary pull-right"><?php if ($inboxCount > 0) {
                                            echo $inboxCount;
                                        } ?></span></a></li>
                            <li>
                                <a href="<?php echo $this->getUrl('csmessaging/customer/sent');?>"><i
                                            class="fa fa-envelope-o"></i><?php echo __('Sent'); ?></a></li>
                        </ul>
                    </div><!-- /.box-body -->
                </div>
            </div><!-- /.col -->
            <div class="col-md-9 mail-box-right mail-box-sent">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title"><?php echo __('Inbox'); ?></h3>
                        <div class="clear"></div>
                        <!--  <div class="box-tools pull-right">
                           <div class="has-feedback">
                             <input type="text" class="form-control input-sm" placeholder="Search Mail"/>
                             <span class="glyphicon glyphicon-search form-control-feedback"></span>
                           </div> -->
                    </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <?php if (!$collection->count()): ?>
                    <p class="note-msg"><?php echo __('There are no messages for the vendor by the customers.') ?></p>
                <?php else: ?>
                    <div class="table-responsive mailbox-messages">
                        <table class="table table-hover table-striped">
                            <tbody>
                            <?php if ($collection->getSize()): ?>
                                <?php foreach ($collection as $msg => $value): ?>
                                    <?php
                                    $customerName = $this->getName($value['sender_email']);
                                    ?>
                                    <tr>

                                        <!--                           <td class="mailbox-star"><a href="#"><i class="fa fa-star text-yellow"></i></a></td>
                                         -->
                                        <td class="mailbox-name"><a
                                                    href="<?php echo $this->getUrl();//Mage::getBaseUrl()?>csmessaging/customer/read?id=<?php echo $value['chat_id'] ?>"><?php echo $customerName ?></a>
                                        </td>
                                        <td class="mailbox-subject">
                                            <b><?php echo $value['subject'] ?></b><?php echo substr($value['message'], 0, 16); ?>
                                            ...
                                        </td>
                                        <td class="mailbox-attachment"></td>
                                        <td class="mailbox-date"><?php echo date("d-F-Y H:m:s", strtotime($value['time'])) ?></td>
                                        <td class="inbox_view_msg"><a
                                                    href="<?php echo $this->getUrl();//Mage::getBaseUrl()?>csmessaging/customer/read?id=<?php echo $value['chat_id'] ?>">View</a>
                                        </td>
                                    </tr>
                                    <?php
                                endforeach; ?>
                            <?php endif; ?>
                            </tbody>
                        </table><!-- /.table -->
                    </div><!-- /.mail-box-messages -->
                <?php endif; ?>
            </div><!-- /.box-body -->
        </div>
</div><!-- /. box -->
<div>
    <?php echo $block->getPagerHtml(); ?> <!-- this is render next prev link -->
</div>


<!-- Page Script -->
<script>
    jQuery(function ($) {
        //Enable iCheck plugin for checkboxes
        //iCheck for checkbox and radio inputs
        jQuery('input[type="checkbox"]').iCheck({
            checkboxClass: 'icheckbox_flat-blue',
            radioClass: 'iradio_flat-blue'
        });

        //Enable check and uncheck all functionality
        jQuery(".checkbox-toggle").click(function () {
            var clicks = $(this).data('clicks');
            if (clicks) {
                //Uncheck all checkboxes
                jQuery("input[type='checkbox']", ".mailbox-messages").iCheck("uncheck");
            } else {
                //Check all checkboxes
                jQuery("input[type='checkbox']", ".mailbox-messages").iCheck("check");
            }
            jQuery(this).data("clicks", !clicks);
        });

        //Handle starring for glyphicon and font awesome
        jQuery(".mailbox-star").click(function (e) {
            e.preventDefault();
            //detect type
            var $this = jQuery(this).find("a > i");
            var glyph = $this.hasClass("glyphicon");
            var fa = $this.hasClass("fa");

            //Switch states
            if (glyph) {
                $this.toggleClass("glyphicon-star");
                $this.toggleClass("glyphicon-star-empty");
            }

            if (fa) {
                $this.toggleClass("fa-star");
                $this.toggleClass("fa-star-o");
            }
        });
    });
    jQuery(document).ready(function () {

        jQuery.ajax({
            url: "<?php echo $this->getUrl();//Mage::getBaseUrl()?>csmessaging/index/newmsgs",
            type: "POST",
            data: {},
            success: function (response) {
                if (response > 0) {
                    jQuery('.messaging_addon').next().css('color', 'red');
                    jQuery('.vendor_msg').next().css('color', 'red');
                    jQuery(".vendor_msg").parent().append('(');
                    jQuery(".vendor_msg").parent().append(response);
                    jQuery(".vendor_msg").parent().append(')');
                }
            }
        });
        jQuery.ajax({
            url: "<?php echo $this->getUrl();//Mage::getBaseUrl()?>csmessaging/frontend/customer_newmsgs",
            type: "POST",
            data: {},
            success: function (response) {

                if (response > 0) {
                    jQuery('.messaging_addon').next().css('color', 'red');
                    jQuery('.customer_msg').next().css('color', 'red');
                    jQuery(".customer_msg").parent().append('(');
                    jQuery(".customer_msg").parent().append(response);
                    jQuery(".customer_msg").parent().append(')');
                }
            }
        });
    });
</script>
