<?php



/**

 * CedCommerce

 *

 * NOTICE OF LICENSE

 *

 * This source file is subject to the End User License Agreement (EULA)

 * that is bundled with this package in the file LICENSE.txt.

 * It is also available through the world-wide-web at this URL:

 * http://cedcommerce.com/license-agreement.txt

 *

 * @category    Ced

 * @package     Ced_CsMarketplace

 * @author      CedCommerce Core Team <connect@cedcommerce.com>

 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)

 * @license      http://cedcommerce.com/license-agreement.txt

 */

?>

<div class="row">

<div class="col-md-12 ced-transactions-details" style="margin-top:10px;">

	<?php echo $block->getFormHtml(); ?>

</div>

<p class="back-link" ><a class="back-link" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><small>&laquo; </small><?php echo __('Back') ?></a></p>

</div>
