<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category Ced
 * @package Ced_Productfaq
 * @author CedCommerce Core Team
 * @copyright Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license http://cedcommerce.com/license-agreement.txt
 */
?>
<?php 
$_product = $block->getProduct();
$productid=$_product->getId();
$faqs=$block->getCollection();

?>
<a href="javascript:;" id="ask_us" class="various"><?php echo __("Doesn't find your answer??ASK US")?></a>
<div class="clear"></div>
 <div class="toolbar top">
 	<?php echo $block->getPagerHtml(); ?>
 </div>
 <div class="accordion product_faqs"> 
 	<?php foreach ($faqs as $faq)
    	{
			if($faq->getData('is_active')=='1')
				{
	?>
 						<li>
	 						<span class="faq_title"><?php echo $title=$faq->getData('title') ?></span>
	 						<span class="faq_date">Posted On:<?php echo $faq->getData('publish_date')?></span>
	 						<div class="clear"></div>
 						</li>
	          			<div class="pane" style="display:none">
		          			<div class="posted_by">
		          				<div class="posted_by_img"></div>
		          				<div class="posted_by_text">Posted By:<?php echo $faq->getData('posted_by')?></div>
		          					<div class="clear"></div>
		          			</div>
			      			<p>
			         			<?php echo $faq->getData('description') ?>
			      			</p>
			      			<div class="grid">
								<?php $questionid= $faq->getData('id');
                 					  $userip=$_SERVER['REMOTE_ADDR'];
                 					  $test=$this->getLikesCount($questionid);
                 					  $count=0;
                 					  $ips=null;
                					  foreach ($test as $data)
                     					{
	                     					$count=$data['likes'];
	                     					$ips=$data['user_ip'];
                     					}
	                     					$ips=unserialize($ips);
			     							if (strpos($ips,$userip) !== false) 
                    							{  
           						?>
                  				<input type="button" value="unlike"  data-item="<?php echo $faq->getData('id'); ?>" data-productid="<?php echo $productid ?>" class="button_like" id="linkeBtn<?php echo $faq->getData('id'); ?>" />
	        					<?php   } else { ?>
	                  			<input type="button" value="like"  data-item="<?php echo $faq->getData('id'); ?>" data-productid="<?php echo $productid ?>" class="button_like" id="linkeBtn<?php echo $faq->getData('id'); ?>" />
	        					<?php    }  ?>
                      			<span id="count<?php echo $faq->getData('id'); ?>" <?php if($count=='0') {?> class="has_value" <?php }?>><?php if($count>0) echo $count; ?></span><br>
                  			</div>
                  			<div class="clear"></div>
                  		</div>
			  			 	<?php   ?>

			<?php } $count=0; } ?>
 </div>
 
 <?php /*Ask Us Form Start Here*/?>
 <div id="myDiv" style="display:none" class="ask_us_popup">
 	<div class="close_askus">
 	<a href="javascript:;" id="close_pop" class="various">X</a>
 	</div>
 	<div class="ask_question" style="display:none">
 	<form action="" id="formId" method="post">
	 	<label for="name"><?php echo __('Name')?><span class="required">*</span></label>
	    <input type="text" name="name" id="name" class="input-text required-entry ask_question" />
	    <label for="emailid"><?php echo __('Email')?><span class="required">*</span></label>
	    <input type="text" name="email" id="emailid" class="input-text required-entry ask_question" />
	    <label for="question"><?php echo __('Question')?><span class="required">*</span></label>
	    <textarea rows="4" id="question" placeholder="Please Enter your question ..." class="input-text required-entry ask_question" cols="6" name="textOpt"></textarea>
	    <input id="productid" value="<?php echo $productid; ?>"  type="hidden">
	     <button class="button" type="button" onclick="SubmitRequest();"><?php echo __('Ask Us')?></button>
	   </form>
    </div>
    <div class="response" id="response"></div>
 </div>
 <div style="display:none" class="ask_us_popup_overlay"></div>
 <?php /*Ask Us Form End Here*/?>
 
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->
 <script type="text/javascript">

 /*Script for Accordian style start*/
	require(["jquery"], function ($) {
 var accor=jQuery;
 	 accor(function () {
		    //  Accordion Panels
		    accor(".accordion li").click(function () {
		    	accor(this).next(".pane").slideToggle("slow").siblings(".pane:visible").slideUp("slow");
		    	accor(this).toggleClass("current");
		    	accor(this).siblings("li").removeClass("current");
		    });
		});

 	/*Script for Accordian style end*/
 	
 	/*Script for Like/dislike  start*/
 	accor('.button_like').click(function(){
   	 var ip="<?php echo $_SERVER['REMOTE_ADDR']?>";
   	 var val =  accor(this).val();
 	     var questionid= accor(this).attr('data-item');
 	     var productid= accor(this).attr('data-productid');
 	     if(val=='like')
 	     {
 	    	 var url="<?php echo $block->getUrl('faq/productfaq/like') ?>";
   	 accor.post(url, {id:questionid,productid:productid,ip:ip},function(data)
   		        {
   	            if(data)
   	            {
   	                accor("#linkeBtn"+questionid).val(data.like);
   	                accor("#count"+questionid).text(data.count);
   	             accor("#count"+questionid).removeClass('has_value');
   	            }
   	            
   	        })
 	     }
 	     else
 	     {
 	    	 var url="<?php echo $this->getUrl('faq/productfaq/unlike') ?>";
       	 accor.post(url, {id:questionid,productid:productid,ip:ip},function(data)
       		        {
       	            if(data)
       	            {
       	            	accor("#linkeBtn"+questionid).val(data.unlike);
       	            	if(data.count!=0){
       	            	accor("#count"+questionid).text(data.count);
       	            	accor("#count"+questionid).removeClass('has_value');
       	            	}
       	            	else{
       	            		accor("#count"+questionid).text('');
       	            		accor("#count"+questionid).addClass('has_value');
           	            	}
       	            }
       	        })
     	 }
    });
 	/*Script for Like/Dislike end*/

      /*Script for displaying ask us form start */  
      accor('#ask_us').click(function(e){
				e.preventDefault();
				accor("#myDiv").css("display", "block");
				accor(".ask_us_popup_overlay").css("display", "block");
				accor(".ask_question").css("display", "block");
      });
      /*Script for displaying ask us form end */
              
      /*Script for hiding ask us form start */
        accor('#close_pop').click(function(e){
  				e.preventDefault();
  				jQuery("#formId")[0].reset();
  				document.getElementById('response').innerHTML='';
  				accor("#myDiv").css("display", "none");
  				accor(".ask_us_popup_overlay").css("display", "none");
        });
	  });
        /*Script for hiding ask us form end */

     /*Script for submitting ask us form data start*/
        function SubmitRequest()
        {
            var accor=jQuery;
          var name=document.getElementById('name').value;
          var email=document.getElementById('emailid').value;
          var question=document.getElementById('question').value;
          var productid=document.getElementById('productid').value;
          if(validate_form()){
             var url="<?php echo $this->getUrl('faq/productfaq/save') ?>";
             accor.ajax({
                 type : "POST",                 
                 cache : false,
                 url: url,
                 data: {product: productid, email: email, question: question,name:name},
                 success:function(data){
                 accor(".ask_question").css("display", "none");
                 document.getElementById('response').innerHTML=data;
                 }
             });
          }
        }
        /*Script for submitting ask us form data end*/

        /*Script for validating ask us form data start*/
       function validate_form()
       {
    	   var accor=jQuery;
           var name=document.getElementById('name');
           var email=document.getElementById('emailid');
           var question=document.getElementById('question');
           if(name.value=='undefined' || name.value==null || name.value=="")
               {
                alert('Name is a required field');
                return false;
               }
          
           if(email.value=='undefined' || email.value==null || email.value=="")
               {
                   alert('Email is a required field');
                   return false;
               }
           if(question.value=='undefined' || question.value==null || question.value=="")
           {
               alert('Question is a required field');
               return false;
           } 
           var mailformat = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;  
           if(email.value.match(mailformat))  
               {  
                   return true;
               } 
           else
               {
                   alert('Invalid Email Format');
                   return false;
               }
           return true;
          }
    
     /*Script for validating ask us form data end*/

    function clearContents(element) {
      element.value = '';
    }
 </script>

