<?php
/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category    Ced
  * @package     Ced_CsOrder
  * @author   	 CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license      http://cedcommerce.com/license-agreement.txt
  */
// @codingStandardsIgnoreFile

?><?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$register = $objectManager->get('Magento\Framework\Registry');
$order = $register->registry('current_vorder');
$vendorId =$order->getVendorId();// $objectManager->get('Magento\Customer\Model\Session')->getVendorId();
$vProducts = $objectManager->get('Ced\CsMarketplace\Model\Vproducts');
?>
<?php $_order = $block->getOrder() ?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
            <tr class="headings">
                <th class="col-product"><span><?php /* @escapeNotVerified */ echo __('Product') ?></span></th>
                <th class="col-status"><span><?php /* @escapeNotVerified */ echo __('Item Status') ?></span></th>
                <th class="col-price-original"><span><?php /* @escapeNotVerified */ echo __('Original Price') ?></span></th>
                <th class="col-price"><span><?php /* @escapeNotVerified */ echo __('Price') ?></span></th>
                <th class="col-ordered-qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></th>
                <th class="col-subtotal"><span><?php /* @escapeNotVerified */ echo __('Subtotal') ?></span></th>
                <th class="col-tax-amount"><span><?php /* @escapeNotVerified */ echo __('Tax Amount') ?></span></th>
                <th class="col-tax-percent"><span><?php /* @escapeNotVerified */ echo __('Tax Percent') ?></span></th>
                <th class="col-discont"><span><?php /* @escapeNotVerified */ echo __('Discount Amount') ?></span></th>
                <th class="col-total last"><span><?php /* @escapeNotVerified */ echo __('Row Total') ?></span></th>
            </tr>
        </thead>
        <?php $_items = $block->getItemsCollection();?>
        <?php $i = 0; foreach ($_items as $_item):?>
            <?php if ($_item->getParentItem() || $vProducts->getVendorIdByProduct($_item->getProductId())!= $vendorId) {
                continue;
            } else {
                $i++;
            }?>
            <?php $vproducts=$objectManager->create('Ced\CsMarketplace\Model\Vproducts')->getCollection()->addFieldTofilter('product_id', $_item->getProductId())->addFieldTofilter('vendor_id', $vendorId)->getData(); ?>
            <?php if(sizeof($vproducts)>0): ?>
              <tbody class="<?php /* @escapeNotVerified */ echo $i%2 ? 'even' : 'odd' ?>">
                <?php echo $block->getItemHtml($_item) ?>
                <?php echo $block->getItemExtraInfoHtml($_item) ?>
            </tbody>
              <?php else: $i++;?>
            <?php endif ?>
            
        <?php endforeach; ?>
    </table>
</div>
