<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<?php $helper = $block->getObjectManager()->get('Ced\CsMarketplace\Helper\Data'); ?>
<div class="pull-right hidden-xs">
	<b><?php echo __('Version'); ?></b> <?php echo $helper->getMarketplaceVersion(); ?>
</div>
<?php echo $helper->getVendorFooterText(); ?>