<?php 

 /**
  * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category    Ced
  * @package     Ced_Blog
  * @author      CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license      http://cedcommerce.com/license-agreement.txt
  */

?>

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
</head> 
<?php

$data = $this->getRequest()->getParams();

if(isset($data['grid_record_id']))
{
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $collection = $objectManager->create('Magento\Eav\Model\ResourceModel\Entity\Attribute\Collection');
    foreach($collection->getData() as $val)
    {
	   if($val['attribute_code']=='ip_address')
	{

		$entity_type_id= $val['entity_type_id'];
	}
}

$collection = $objectManager->get('Magento\Eav\Model\ResourceModel\Entity\Attribute\Collection')->setEntityTypeFilter($entity_type_id);

foreach($collection->getData() as $data)
{
	if($data['attribute_code']==$val['attribute_code'])
	{
		$values=json_decode($val['frontend_class']);
	}
}

if(isset($values)){
    foreach($values as $val1)
    {
	   $ar[$val1]=$val1;

    } 
}

?>

<fieldset id="attribute_block" class="fieldset" style="display: none">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Manage Options (values of your attribute)') ?></span></legend>
    <div id="manage-options-panel" >
        <table class="admin__control-table">
            <thead>
                <tr id="attribute-options-table">
                    <th class="col-draggable"></th>
                    <th class="col-default control-table-actions-th"><?php /* @escapeNotVerified */ echo __('Is Default') ?></th>
                    <?php $storelist = $block->getStores();
                    foreach ($storelist as $_store): ?>
                        <th><?php /* @escapeNotVerified */ echo __($_store->getName()) ?></th>
                    <?php endforeach;
                    $storetotal = count($storelist) + 3;
                ?>
                    <th class="col-delete">&nbsp;</th>
                </tr>
            </thead>
            <tbody data-role="options-container" class="ignore-validate"></tbody>
            <tfoot>
                <tr>
                    <th colspan="<?php /* @escapeNotVerified */ echo $storetotal; ?>" class="col-actions-add">
                        <button id="add_new_option_button" title="<?php /* @escapeNotVerified */ echo __('Add Option'); ?>" type="button" class="action- scalable add">
                            <span><?php /* @escapeNotVerified */ echo __('Add Option'); ?></span>
                        </button>
                    </th>
                </tr>
            </tfoot>
        </table>
        <input type="hidden" id="option-count-check" value="" />
    </div>
    <script id="row-template" type="text/x-magento-template">
         <tr>
            <td class="col-draggable">
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()): ?>
                    <div data-role="draggable-handle" class="draggable-handle" title="<?php /* @escapeNotVerified */ echo __('Sort Option'); ?>"></div>
                <?php endif; ?>
                <input data-role="order" type="hidden" name="option[order][<%- data.id %>]"  value="<%- data.sort_order %>" <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()): ?> disabled="disabled"<?php endif; ?>/>
            </td>
            <td class="col-default control-table-actions-cell">
                <input class="input-radio" type="<%- data.intype %>" name="default[]" value="<%- data.id %>" <%- data.checked %><?php if ($block->getReadOnly()):?>disabled="disabled"<?php endif;?>/>
            </td>
            <?php foreach ($block->getStores() as $_store): ?>
            <td class="col-<%- data.id %>"><input name="option[value][<%- data.id %>][<?php /* @escapeNotVerified */ echo $_store->getId() ?>]" value="<%- data.store<?php /* @escapeNotVerified */ echo $_store->getId() ?> %>" class="input-text<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID): ?> required-option<?php endif; ?>" type="text" <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()):?> disabled="disabled"<?php endif;?>/></td>
            <?php endforeach; ?>
            <td id="delete_button_container_<%- data.id %>" class="col-delete">
                <input type="hidden" class="delete-flag" name="option[delete][<%- data.id %>]" value="" />
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()):?>
                    <button id="delete_button_<%- data.id %>" title="<?php /* @escapeNotVerified */ echo __('Delete') ?>" type="button"
                        class="action- scalable delete delete-option"
                        >
                        <span><?php /* @escapeNotVerified */ echo __('Delete') ?></span>
                    </button>
                <?php endif;?>
            </td>
        </tr>
    </script>
   <?php
    if(isset($ar))
    {
	   	$i=0;
	   	foreach($ar as $key=>$val)
	   	{
	   		$values[$i] = array('checked'=>'','intype'=>'','id'=>'','sort_order'=>'','store0'=>$val,'store1'=>$val,'store2'=>$val);
	   		$i++;
	   	}
    } else {
     		$values[] = array('checked'=>'','intype'=>'','id'=>'','sort_order'=>'','store0'=>'','store1'=>'','store2'=>'');	
    }
    ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Catalog/js/options": {
                    "attributesData": <?php /* @escapeNotVerified */if(isset($values)) echo json_encode($values); /* else{ if(isset($new))echo json_encode($new);} */  ?>,
                    "isSortable":  <?php echo (int)(!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()) ?>,
                    "isReadOnly": <?php echo (int)$block->getReadOnly(); ?>
                }
            }
        }
    </script>
    <script type="text/javascript">
    jQuery(document).ready(function (){
    		var val=jQuery("#page_backend_type").val()
    		if(val == 'Dropdown')
    		{
    			jQuery("#attribute_block").css("display", "block");
            	}
    		}); 
    </script>
</fieldset>

