<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_RequestToQuote
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

?>

<?php
$product_id=$block->getProductId();
$vendor_id=$block->getVendor($product_id);
$product_name=$block->getProduct()->getName();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productCollection = $objectManager->create('\Magento\Catalog\Model\Product')->load($product_id);
$session = $objectManager->get('\Magento\Customer\Model\Session');
$login = $session->isLoggedIn();
$custGroups = $block->getAllowedCustomerGroups();
$hideGroups = $block->getAddtoCartCustomers();
if(empty($login)){
    $groupId =  '0';
}
else{
    $groupId =  $session->getCustomer()->getGroupId();
}

if (in_array($groupId, $hideGroups)){ 
        $hideto = "yes";
    }
    else{
        $hideto = "no";
    }

 ?>

<input type="hidden" id="hidecart" value="<?php echo $hideto;  ?>" />

<?php $buttonTitle = __('Add to Quote'); 
        ?>
<?php if (in_array($groupId, $custGroups)){ ?>

    <?php if($block->getProductType() == 'simple'){ ?>
    <div style="clear: both;"></div>
    <div class="box-tocart cart-to-quote">
        <div class="fieldset">
            <div class="actions">
                <?php if(empty($login)){ ?>
                    <a href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo __('Try login to request a quote for the product') ?></a>
                <?php }else{ ?>
                    <button class="button btn btn-info uptransform action primary" title="<?php echo __('Get Quote for the Product') ?>" type="button" id="sendquote" name="submit" >
                        <span><span><?php echo __('Get Quote for the Product') ?></span></span>
                    </button>
                <?php } ?>
            </div>
        </div>
    </div>

    <?php } ?>
<?php } ?>

<div id="message-content" style="display:none;">
    <div class="panel-body">
        <form action="<?php echo $this->getUrl('requesttoquote/quotes/save') ?>" method="POST" name="quote-form" id="quoteform">
            <input type="hidden" name="product_id" value="<?php echo $product_id ?>">
            <input type="hidden" name="vendor_id" value="<?php echo $vendor_id ?>">
             <input type="hidden" name="product_name" value="<?php echo $product_name ?>">
            <div class="fieldset">      

                <div class="form-group col-12">
                    <label><?php echo __('Enter Quantity');?></label>
                    <div class="input-box">
                        <input type="text" id="quote_qty" name="quote_qty" class="required required-entry validate-number validate-greater-than-zero"/>
                        <span class="required"></span>
                    </div>
                </div>
                <div class="form-group col-12">
                    <label><?php echo __('Enter Quoted Price');?></label>
                    <div class="input-box">
                        <input type="text" id="quote_price" name="quote_price" class="contact_input_fields required-entry validate-greater-than-zero"/>
                        <span class="required"></span>
                    </div>
                </div>
                
                 <!-- <div class="form-group col-12">
                    <div class="input-box">
                        <input type="submit" id="submit" name="submit" />
                    </div>
                </div> -->
            </div>
        </form>
    </div>
</div>

<script>
        require([
                 'jquery',
                 'mage/mage'
             ], function($){

                 var dataForm = $('#quoteform');
                 var ignore = null;
                 dataForm.mage('validation', {
                         ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
                     }).find('input:text').attr('autocomplete', 'off');
             });
</script>

<script>
require([
    'jquery',
    'Ced_RequestToQuote/js/jquery.form',
], function($){
$("#sendquote").click(function(){
        var id = $(this).prev().val();
        var flag =false;
        var flag2=true;
        var path = '<?php echo $this->getUrl('requesttoquote/quotes/save'); ?>';
        require(['jquery','Magento_Ui/js/modal/modal'], function ($,modal) {
             var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'Please Enter Your Quote Details',
                    buttons: [{
                        text: $.mage.__('Send'),
                        id: 'quote_submit',
                        click: function () {
                           $('#quoteform').ajaxForm({
                                        success:function(e){
                                            $('.modal-footer button').attr('disabled','disabled');
                                            $(".modal-footer").append("<div style='color:green'>Please wait! Saving quote data..</div>");
                                            window.location = "<?php echo $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>";
                                            
                                        },
                                        error:function(e){
                                            window.location = "<?php echo $this->getUrl('customer/account/login'); ?>";
                                        }
                                    }).submit();
                           $('#quoteform').submit(function(e){
                                flag =true;
                                flag2=false;
                            });

                           if(flag){
                                this.closeModal();
                            }
                        }
                    }]
                };
                
                var popup = modal(options, $('#message-content'));

                $('#message-content').modal('openModal');

            }); 
    });
    
    $('document').ready( function(){
        var hide = $('#hidecart').val(); 
                    if(hide == 'yes'){
                        
                        $('#product-addtocart-button').remove();                       
                    }
    })
});
</script>
<style>
.cart-to-quote{
    float: left;
    display: inline-block;
    clear: both;
}
.product-info-stock-sku{
    float: right;
}
.product-info-main .product-info-price .product-info-stock-sku {
  float: right;
  width: auto !important;
}
.product-info-main .product-info-price .price-box {
  float: left;
  width: auto;
}
</style>