<?php
/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category    Ced
  * @package     Ced_CsSubAccount
  * @author      CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license      http://cedcommerce.com/license-agreement.txt
  */
?>
<div class="vendor-login-wrapper">
    <div class="login-panel panel panel-default">
		<div class="panel-body sign-up-form-body-wrap" id="sign-up-form-body">
			<?php echo $block->getChildHtml() ?>
		</div>
	</div>
</div>

<style>
.vendor-login-tab, .vendor-sign-up-tab
{
	width: 100% !important;
}
.panel-body.sign-up-form-body-wrap
{
	display: block !important;
}
#submit_button_id
{
	width: 100%;
}
</style>