<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>

<?php
	$vendors = $block->getLoadedVendorCollection();
	$helper =$this->helper('Ced\CsMarketplace\Helper\Tool\Image');
	$helper_data=$this->helper('Ced\CsMarketplace\Helper\Data');
	//echo $this->getCurrentStoreId();die;
	$title =$helper_data->getStoreConfig('ced_vshops/general/vshoppage_title',$this->getCurrentStoreId())?$helper_data->getStoreConfig('ced_vshops/general/vshoppage_title',$this->getCurrentStoreId()):"CsMarketplace";
	$width = (int)$helper_data->getStoreConfig('ced_vshops/general/list_image_width',$this->getCurrentStoreId());
	$height = (int)$helper_data->getStoreConfig('ced_vshops/general/list_image_height',$this->getCurrentStoreId());
	$width = $width?$width:135;
	$height = $height?$height:135;
	$img=$helper_data->getStoreConfig("ced_vshops/general/vshoppage_banner",$this->getCurrentStoreId())?"ced/csmarketplace/".$helper_data->getStoreConfig("ced_vshops/general/vshoppage_banner",$this->getCurrentStoreId()):'';
	$width=800;
	$height=200;
?>
<?php if($this->helper('Ced\CsMarketplace\Helper\Acl')->isEnabled()) { ?>  
	<div style="text-align:center;" class="page-title category-title">
		<h1><?php echo $title?></h1>
	</div>
   	<p class="category-image">
		<img id="product-collection-image-1"
                     src="<?php echo $helper->init($img,'csbanner')->keepAspectRatio(false)->resize($width,$height)?>"
                     alt="CsMarketplace Banner" height="100%" width="100%" />
   	</p>
    <div class="category-description std">
        <?php echo $helper_data->getStoreConfig('ced_vshops/general/vshoppage_about',$this->getCurrentStoreId()); ?>
    </div>
	<?php if(!$vendors->count()): ?>
	<div class="remove_vendors_wrap">
		<p class="note-msg"><?php echo __('Sorry!! No vendor available.') ?></p>
		<span class="currently_search">
			<a class="remove" href="<?php echo $this->getUrl('csmarketplace/vshops/index') ?>">
				<?php echo __('X');?>
			</a>
		</span>
		<div class="cleared"><div>
	</div>
	<?php else: ?>
	<div class="vendor_list_page">
		<div class="search_vendor" style="float: left;">
			<span>
				<?php echo $this->getChildHtml('country_filter'); ?>
			</span>
		</div>
		<div class="category-products" style="float: right;">
			<div>
				<?php echo $this->getToolbarHtml(); ?>
				<?php // List mode ?>
				<?php if($this->getMode()!='grid'): ?>
				
				<?php $_iterator = 0; ?>
				<?php // Vendor Logo 
						$width = (int)$helper_data->getStoreConfig('ced_vshops/general/list_image_width',$this->getCurrentStoreId());
						$height = (int)$helper_data->getStoreConfig('ced_vshops/general/list_image_height',$this->getCurrentStoreId());
						$width = $width?$width:135;
						$height = $height?$height:135;
				?>
				<ul class="products-list csmarketplace-vendors-list" id="csmarketplace-vendors-list">
				<?php foreach ($vendors as $vendor):?>
				<?php // echo $helper->init($vendor->getData('company_logo'))->keepAspectRatio(false)->resize($width,$height);?>
					<li class="item<?php if( ++$_iterator == sizeof($vendors) ): ?> last<?php endif; ?>">
					
					   <a href="<?php echo $vendor->getVendorShopUrl() ?>" title="<?php echo $this->stripTags($vendor->getPublicName(), null, true) ?>" class="product-image vendor-logo-image"><img src="<?php echo $helper->init($vendor->getData('company_logo'))->keepAspectRatio(false)->resize($width,$height); ?>" alt="<?php echo $this->stripTags($vendor->getPublicName(), null, true) ?>" /></a>
						 <!--  <h2 class="product-name csmarketplace-vendor-name"><a href="<?php echo $vendor->getVendorShopUrl() ?>" title="<?php echo $this->stripTags($vendor->getPublicName(), null, true) ?>"><?php echo $vendor->getPublicName() ?></a></h2>-->
						<?php /* if($vendor->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($vendor, 'short') ?>
						<?php endif; */ ?>
						<?php // Vendor description ?>
						<div class="product-shop">
							<div class="f-fix">
								<div class="product-primary">
									<?php $vendorNameStripped = $this->stripTags($vendor->getName(), null, true); ?>
									<h2 class="product-name"><a href="<?php echo $vendor->getVendorShopUrl() ?>" title="<?php echo $vendorNameStripped; ?>"><?php echo $vendor->getPublicName(); ?></a></h2>
									<?php //if($vendor->getRatingSummary()): ?>
									<?php echo $this->getReviewsSummaryHtml($vendor) ?>
									<?php //endif; ?>
	
								</div>
								<div class="desc std">
									<div><?php echo $vendor->getAbout(); ?></div>
									<a href="<?php echo $vendor->getVendorShopUrl() ?>" title="<?php echo $vendorNameStripped ?>" class="link-learn"><?php echo __('Go to Shop') ?></a>
								</div>
							</div>
						</div>
					</li>
				<?php endforeach; ?>
				</ul>
				<script type="text/javascript">decorateList('csmarketplace-vendors-list', 'none-recursive')</script>
	
				<?php else: ?>
				<?php // Grid Mode ?>
				<?php $_collectionSize = $vendors->count() ?>
				<?php $_columnCount = $this->getColumnCount(); ?>
				<?php 
					// Vendor Logo
						$width = (int)$helper_data->getStoreConfig('ced_vshops/general/grid_image_width',$this->getCurrentStoreId());
						$height = (int)$helper_data->getStoreConfig('ced_vshops/general/grid_image_height',$this->getCurrentStoreId());
						$width = $width?$width:135;
						$height = $height?$height:135;
				?>
				<?php $i=0; foreach ($vendors as $vendor): ?>
					<?php $vendorNameStripped = $this->stripTags($vendor->getName(), null, true); ?>
					<?php //print_r($vendor->getData());?>
					<?php if ($i++%$_columnCount==0): ?>
					<div>
						<ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col csmarketplace-vendors-grid">
						<?php endif ?>
							<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
								<a href="<?php echo $vendor->getVendorShopUrl() ?>" title="<?php echo $this->stripTags($vendor->getPublicName(), null, true) ?>" class="product-image vendor-logo-image"><img src="<?php echo $helper->init($vendor->getData('company_logo'))->resize($width,$height); ?>" alt="<?php echo $this->stripTags($vendor->getName(), null, true) ?>" /></a>
								<h2 class="product-name csmarketplace-vendor-name"><a href="<?php echo $vendor->getVendorShopUrl() ?>" title="<?php echo $this->stripTags($vendor->getPublicName(), null, true) ?>"><?php echo $vendor->getPublicName() ?></a></h2>
								<?php //if($vendor->getRatingSummary()): ?>
								<?php echo $this->getReviewsSummaryHtml($vendor) ?>
								<?php //endif; ?>
								
								 <div class="product-info">
								 <a href="<?php echo $vendor->getVendorShopUrl() ?>" title="<?php echo $vendorNameStripped; ?>" class="link-learn"><?php echo __('Go to Shop') ?></a>
								 </div>
							</li>
						<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
						</ul>
					</div>
					<?php endif ?>
				<?php endforeach ?>
				<script type="text/javascript">/* decorateGeneric($$('ul.csmarketplace-vendors-grid'), ['odd','even','first','last']) */</script>
				<?php endif ?>
			</div>
			
		</div>
		<div style="clear: both;"></div>
		<div class="page_limiter">
				<?php echo $this->getToolbarHtml(); ?>
		</div>
	</div>
	<?php endif; ?>
<?php } ?>

<script>
require([
		'mage/url',
		'jquery'
	], function() {
		jQuery(".page_limiter>div>div.limiter").removeClass("limiter").addClass('limiter1');	
		jQuery(".page_limiter>div>div.modes").removeClass("modes").addClass('modes1').css('display','none');
		jQuery(".page_limiter>div>div.sorter").removeClass("sorter").addClass('sorter1').css('display','none');	
	});
</script>
<style>
a, .alink {
    color: #1979c3;
    font-size: 15px;
    text-decoration: none;
}
.products-grid.products-grid--max-5-col.csmarketplace-vendors-grid >li{
float:left;
margin:2px;
list-style:none;
}
h1{
font-size:25px;
}
.product-image.vendor-logo-image > img {
    width: 200px;
}
.category-products {
    width: 950px;
}
.form-list > li, ol > li {
    margin-bottom: 1rem;
    margin-top: 0rem;
    width: 250px;
}
li{
	list-style:none;
}
.page-layout-1column .toolbar-products {
    position: inherit;
    margin-left:40px;
    }
 .page_limiter{
 	margin-left:300px;
 }
.field.limiter1 {
    margin-left: 800px;
}
.page-title-wrapper {
    display: none;
}
</style>