<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsTableRateShipping
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<?php
/**
 * @see \Ced\CsMarketplace\Block\Adminhtml\Vendor
 */
?>
 <button onClick="document.location.href='<?php echo $this->getUrl('cstablerateshipping/rates/add')?>'">Add New Rate</button>
<?php echo $block->getGridHtml() ?>
