<?php
$po_data = $block->getPoData();
$customer_data = $block->getCustomerData();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
$quoteData = $block->getQuoteData();
$address = $block->getCustomerAddress();
?>
<section class="admin__page-section order-addresses">
        <div class="admin__page-section-title">
            <span class="title"><?php echo __("Shipping & Handling Information");?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-billing-address">
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo __('Shipped To');?></span>
                </div>
                <address class="admin__page-section-item-content"><?php echo $customer_data->getName();?><br>

                    <?php echo $address['street'];?><br>
                    <?php echo $address['city'];?>, <?php echo $address['state'];?>, <?php echo $address['pincode'];?>
                    <?php echo $address['country'];?><br>
                    <?php echo __("Telephone :");?>
                    <?php echo $address['telephone'];?>

                </address>
            </div>
            <div id="order-billing_method" class="admin__page-section-item order-billing-method">
                <div class="admin__page-section-title">
                    <span class="title"><?php echo __("Shipping Method");?></span>
                </div>
                <div id="order-billing_method_form">
                    <dl class="admin__payment-methods">
                        <dt class="admin__field-option">
                            <span class="no-display">
                                <input id="p_method_free" value="free" name="payment[method]" class="admin__control-radio" checked="checked" type="radio">
                            </span>
                            <label class="admin__field-label" for="p_method_free"><?php echo $quoteData->getShipmentMethod() ;?></label>
                        </dt>
                        <dd class="admin__payment-method-wapper"></dd>
                    </dl>
                </div>
                <div class="admin__page-section-item-content">
                    <strong><?php echo __("Shipment Amount");?></strong>
                    <span class="price"><?php echo $priceHelper->currency($quoteData->getShippingAmount(), true, false);?></span>
                </div>
            </div>
        </div>
    </section>