<?php 

/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category  Ced
  * @package   Ced_CsVendorProductAttribute
  * @author    CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license      http://cedcommerce.com/license-agreement.txt
  */
 
?>
<?php echo $block->getFormHtml() ?>
<script>
require(['jquery', "mage/mage"], function(jQuery){

    jQuery('#<?php /* @escapeNotVerified */ echo $block->getFormId();?>').mage('form').mage('validation');

});
</script>
<script>
window.onload = function() {
	  var btn = document.getElementsByClassName('save-attribute-set');
	  btn[0].onclick=function(){
		var textField = document.getElementById('attribute_set_name');
		var index1 = textField.className.indexOf("mage-error");
		var index2 = textField.className.indexOf("valid");
		if(index1 == -1 && index2 != -1) {
			document.getElementById("set-prop-form").submit();
		}
	};
};

/* function setLocation(url)
{
	window.location.href=url;
} */
</script>
