<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<?php
$vorder = $this->_objectManager->get('Magento\Framework\Registry')->registry('current_vorder');
$_order  = $this->getOrder();
$_source = $this->getSource();
$_fullInfo  = $this->getFullTaxInfo();
?>
<?php if($vorder->getBaseTaxAmount()){?>
<tr class="0">
    <td style="padding-bottom:3px; padding-left: 9px; padding-right: 9px; padding-top: 3px" align="right" class="a-right" colspan="3">
        <div class="summary-collapse">
        <?php if ($this->helper('tax')->displayFullSummary()): ?>
            <?php echo Mage::helper('sales')->__('Total Tax') ?>
        <?php else: ?>
            <?php echo Mage::helper('sales')->__('Tax') ?>
        <?php endif;?>
        </div>
    </td>
    <td style="padding-bottom:3px; padding-left: 9px; padding-right: 9px; padding-top: 3px" align="right" class="a-right" colspan="3">
        <?php echo $this->displayAmount($vorder->getPurchaseTaxAmount(), $vorder->getBaseTaxAmount()); ?>
    </td>
    <?php }?>
</tr>
