<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_RequestToQuote
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info */ ?>
<?php 
        
      $quoteId = $block->getQuoteId();
      $customer_id = $block->getCustomerId();
	  $customer_email = $block->getCustomer($customer_id)->getEmail();
      $customer_name = $block->getCustomer($customer_id)->getName(); 
      $address = $block->getCustomerAddress();
      $quotes = $block->getItems();
      $quoteData = $block->getQuoteData();
      $products = $block->getProductId();
      $vendor_id = $block->getVendorId();

?>

<form method="POST" action="<?php echo $block->getPOUrl();?>">
    <div class="page-main-actions">    
        <div class="page-actions-placeholder" style=""></div>
            <div class="page-actions" data-ui-id="page-actions-toolbar-content-header"><div class="page-actions-inner" data-title="#000000021"><div class="page-actions-buttons">
                <button id="back" title="Back" type="button" class="action-default scalable back" onclick="setLocation('<?php echo $block->getBackUrl();?>')">
                    <span>Back</span>
                </button>
                <button id="order-view-cancel-button" title="Cancel" type="button"  onclick="setLocation('<?php echo $block->getCancelUrl();?>')">
                    <span>Cancel</span>
                </button>
            </div>
        </div>
        </div>
    </div>
    <section id="order-form_account" class="admin__page-section order-account-information">
        <input  name="quote_id" value="<?php echo $quoteId;?>" type="hidden">
                
    	<div class="admin__page-section-title head-account">
    	    <span class="title"><?php echo __("Account Information");?></span>
    	    <div class="actions"></div>
    	</div>
    	<div id="customer_account_fieds" class="admin__page-section-content">
            <fieldset class="fieldset admin__fieldset " id="main">    
        		
        		<div class="admin__field field field-group_id  required _required" data-ui-id="billing-address-fieldset-element-form-field-group-id">
                    	<label class="label admin__field-label" for="group_id" data-ui-id="billing-address-fieldset-element-select-order-account-group-id-label">	<span><?php echo __("Customer Group");?></span>
                    	</label>
            			<div class="admin__field-control control">
                			<input id="email" name="" data-ui-id="billing-address-fieldset-element-text-order-account-email" value="<?php echo $block->getCustomerGroup($customer_id);?>" class="validate-email admin__control-text input-text admin__control-text" type="text" disabled="disabled">
                        </div>
            	</div>

    		    <div class="admin__field field field-email " data-ui-id="billing-address-fieldset-element-form-field-email" style="width: 35%;">
    		        
                    <label class="label admin__field-label" for="email" data-ui-id="billing-address-fieldset-element-text-order-account-email-label"><span><?php echo __("Customer Email");?></span>
                    </label>
    		        <div class="admin__field-control control">
    		            <input id="email" name="customer_email" data-ui-id="billing-address-fieldset-element-text-order-account-email" value="<?php echo $customer_email;?>" class="validate-email admin__control-text input-text admin__control-text" type="text" readonly>
    		        </div>
    		    </div>  

                <div class="admin__field field field-email " data-ui-id="billing-address-fieldset-element-form-field-email" style="width: 35%;">
                    
                    <label class="label admin__field-label" for="email" data-ui-id="billing-address-fieldset-element-text-order-account-email-label"><span><?php echo __("Customer Name");?></span>
                    </label>
                    <div class="admin__field-control control">
                        <input id="email" name="customer_email" data-ui-id="billing-address-fieldset-element-text-order-account-email" value="<?php echo $customer_name;?>" class="validate-email admin__control-text input-text admin__control-text" type="text" readonly>
                    </div>
                </div>   
            </fieldset>    
        </div>
    </section>

    <section class="admin__page-section order-addresses">
        
        <div class="admin__page-section-title">
            <span class="title"><?php echo __("Address And Shipping Information");?></span>
        </div>
        
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-billing-address">
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo __("Customer Address Information");?>
                    </span>
                </div>
                <address class="admin__page-section-item-content"><?php echo $customer_name;?><br>
                        <?php echo $address['street'];?>
                    <br>
                        <?php echo $address['city'];?>, <?php echo $address['state'];?> - <?php echo $address['pincode'];?>  
                    <br>
                        <?php echo $address['country'];?> 
                    <br>
                        T: <?php echo $address['telephone'];?> 
                </address>
            </div>
            <div class="admin__page-section-item order-shipping-address">
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo __('Shipping Information');?></span>
                </div>
                <div class="admin__page-section-item-content">
                    <div class="shipping-description-wrapper">
                        <div class="shipping-description-title">
                            Shippment Method Selected:<?php echo $quoteData->getShipmentMethod();?>
                        </div>
                        <div class="shipping-description-content">
                            Total Shipping Charges: 
                            <?php 
                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
                            $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
                            ?>                           
                            <span class="price"><?php echo $priceHelper->currency($quoteData->getShippingAmount(), true, false);?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title">Items Ordered</span>
        </div>
        <div class="admin__table-wrapper">
            <table class="data-table admin__table-primary edit-order-table" id ="edit-order-table">
                <thead>
                    <tr class="headings">
                        <th class="col-product"><span><?php echo __("Product"); ?></span></th>
                        <!-- <th class="col-status"><span><?php echo __("Item Status"); ?></span></th> -->
                        <th class="col-price-original"><span><?php echo __("Actual Price"); ?></span></th>
                        <th class="col-price"><span><?php echo __("Quoted Price"); ?></span></th>
                        <th class="col-price"><span><?php echo __("Updated Unit Price"); ?></span></th>
                        <th class="col-ordered-qty"><span><?php echo __("Quoted Qty"); ?></span></th>
                        <th class="col-ordered-qty"><span><?php echo __("Updated Quote Qty"); ?></span></th>
                        <th class="col-subtotal"><span><?php echo __("Subtotal"); ?></span></th>
                        <th class="col-total last"><span><?php echo __("Row Total"); ?></span></th>
                    </tr>
                </thead>
                
                <tbody class="even">
                <input id="noofproducts" type="hidden" name="noofproducts" value="<?php echo $block->getNoOfProducts();  ?>">

                    <?php 
                        $total = 0;
                        foreach ($quotes->getData() as $value) {
                        $product_id = $value['product_id'];
                        $product = $block->getProduct($product_id);
                        $unitprice = $block->getProductIndividualPrice($product_id); ?>
                        <input id="product[<?php echo $product_id;  ?>]" value="<?php echo $product_id;  ?>" type="hidden">
                        <tr>
                            <td class="col-product">
                                <div id="order_item_2_title" class="product-title"><?php echo $product->getName();  ?>
                                </div>
                                <div class="product-sku-block">
                                    <span><?php echo __("SKU:"); ?></span> <?php echo $product->getSku();  ?>
                                </div>
                            </td>
                            
                            <td class="col-price-original"><span><?php echo $block->getCurrencyCode();  ?></span><span class="price"><?php echo $product->getPrice();  ?></span>
                            </td>

                            <td class="col-price">
                                <div class="price-excl-tax">
                                <span><?php echo $block->getCurrencyCode();  ?></span>                
                                    <span class="price"><?php echo $value['updated_price'];  ?></span>
                                </div>
                            </td>

                            <td class="col-price">
                                <div class="price-excl-tax">
                                <?php 
                                    $max_price = $value['updated_price'];
                                ?>
                                <span><?php echo $block->getCurrencyCode();  ?></span>             
                                    <input max="<?php echo $max_price;?>" id="updateprice[<?php echo $product_id;  ?>]" class="input-text admin__control-text qty-input po-price-updated common numbersOnly" name="quoteproducts[<?php echo $product_id;  ?>]" value="<?php echo $value['unit_price'];  ?>" readonly type="text">
                                </div>
                            </td>


                            <td class="col-ordered-qty">
                                <table class="qty-table">
                                    <tbody>
                                        <tr>
                                            <th><?php echo __("Quantity to PO"); ?> :</th>
                                            <?php 

                                                if($value['remaining_qty']){
                                                    $max = $value['remaining_qty'];
                                                    $poed_qty = $value['quote_updated_qty'] - $value['remaining_qty'];
                                                }elseif($value['remaining_qty'] === '0'){
                                                    $max = 0;
                                                    $poed_qty = $value['quote_updated_qty'];
                                                }else{
                                                    $max = $value['quote_updated_qty'];
                                                    $poed_qty = 0;
                                                }
                                            ?>
                                            <td class="col-qty-invoice">
                                                <input max="<?php echo $max;?>" id="quantity_to_po[<?php echo $product_id;  ?>]" class="input-text admin__control-text qty-input qty-field-po common numbersOnly" name="quoteproducts[<?php echo $product_id;  ?>]" value="<?php echo $max  ?>" type="text">
                                            </td>
                                        </tr>
                                        <tr>
                                            <th><?php echo __(" Quantity Already POed"); ?> :</th>
                                            <td><b><?php echo $poed_qty;  ?></b></td>
                                        </tr>                                   
                                    </tbody>
                                </table>
                            </td>
                            <td class="col-price">
                                <div class="price-excl-tax">                
                                    <span class="price" id="quote_qty"><?php echo $value['quote_updated_qty'];  ?></span>
                                </div>
                            </td>
                            <td class="col-qty">
                                <div class="price-excl-tax">
                                <span><?php echo $block->getCurrencyCode();  ?></span>
                                   <input class="input-text admin__control-text qty-input subtotal-po numbersOnly" name="subtotal[<?php echo $product_id;  ?>]"  type="text"  readonly value="<?php echo $value['unit_price'] * $max;  ?>">
                                </div>
                            </td>

                            <td class="col-subtotal">
                                <div class="price-excl-tax"> 
                                <span><?php echo $block->getCurrencyCode();  ?></span>              
                                   <input id="rowtotal" class="input-text admin__control-text qty-input row-total common numbersOnly" name="row_total[<?php echo $product_id;  ?>]"  type="text" value="<?php echo $value['unit_price'] * $max;  ?>" readonly>
                                </div>
                            </td>
                        </tr>
                    <?php 
                        $total += $value['unit_price'] * $max;
                        }

                    ?>             
                </tbody>
            </table>
        </div>
    </section>

    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?php echo __("Purchase Order Total");?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-totals">
                <table class="data-table admin__table-secondary order-subtotal-table">
                    <tfoot>
                        <tr class="col-0">
                            <td class="label">
                                <strong><?php echo __("Grand Total");?></strong>
                            </td>
                            <td>
                                <span><?php echo $block->getCurrencyCode();?></span>
                                <span><input type="text" id="grandtotalofpo" name="grandtotalofpo" readonly value="<?php echo $quoteData->getShippingAmount() + $total;?>" /></span>
                            </td>
                        </tr>
                        <tr class="col-3">
                            <td class="label">
                                <strong><?php echo __("Total Due");?></strong>
                            </td>
                            <td>
                                <span><?php echo $block->getCurrencyCode();?></span>
                                <span><input type="text" id="totaldue" name="totaldue" readonly value="<?php echo $quoteData->getShippingAmount() + $total;?>" /></span>
                            </td>                            
                        </tr>
                    </tfoot>
                    <tbody>
                        <tr class="col-0">
                            <td class="label"><?php echo __("Subtotal");?></td>
                            <td>
                                <span><?php echo $block->getCurrencyCode();?></span>
                                <span><input type="text" id="subtotalofpo" name="subtotalofpo" readonly value="<?php echo $total?>" /></span>

                            </td>
                        </tr>   
                        <tr class="col-1">
                            <td class="label"><?php echo __("Shipping & Handling");?></td>
                            <td>
                                <span><span class="price" id="shiping_and_handling"><span><?php echo $block->getCurrencyCode();?></span><?php echo $quoteData->getShippingAmount();?></span></span>
                                    <input type="hidden" id="shipprice" value="<?php echo $quoteData->getShippingAmount();?>">
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="actions">
                    <button title="Submit Order" type="submit" class="action primary" data-ui-id="widget-button-0">
                        <span><?php echo __("Submit Purchase Order");?></span>
                    </button>
                </div>
            </div>
        </div>    
    </section>  
</form>

<script type="text/javascript">

    require(['jquery'], function($) {
        
        $("#edit-order-table").on('keyup', '.qty-field-po',function(){    
            var data =new Array();
            var shipping = $('#shipprice').val();
              var qty = $(this).val();
               var price = $(this).parents('tr').find('.po-price-updated').val();   
                     $(this).parents('tr').find('.subtotal-po').val(qty*price);
                     $(this).parents('tr').find('.row-total').val(qty*price);      
              $(this).parents('table').find('input.common').each( function(index){
                    data.push($(this).val());
                });
              var sum=0;
              for(var i=0;i<data.length;i+=3){
                   sum += parseFloat(data[i+2]);
              }
              var total = parseFloat(sum)+parseFloat(shipping);
              $('#subtotalofpo').val(sum.toFixed(2));
              $('#grandtotalofpo').val(total.toFixed(2));
              $('#totaldue').val(total.toFixed(2));


        });
                     

       /* $("#edit-order-table").on('keyup', '.po-price-updated',function(){    
            var data =new Array();
            var shipping = $('#shipprice').val();
            var price = $(this).val();
            var qty = $(this).parents('tr').find('.qty-field-po').val();
            $(this).parents('tr').find('.subtotal-po').val(qty*price);      
            $(this).parents('tr').find('.row-total').val(qty*price);   
                    
            $(this).parents('table').find('input.common').each( function(index){
                data.push($(this).val());
            });
              
          var sum=0;
          for(var i=0;i<data.length;i+=3){
             
               sum += parseFloat(data[i+2]);
          }
            var total = parseFloat(sum)+parseFloat(shipping);
            $('#subtotalofpo').val(sum.toFixed(2));
            $('#grandtotalofpo').val(total.toFixed(2));
            $('#totaldue').val(total.toFixed(2));
        });*/

        $(".numbersOnly").keydown(function (e) {
        // Allow: backspace, delete, tab, escape, enter and .
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                 // Allow: Ctrl+A, Command+A
                (e.keyCode === 65 && (e.ctrlKey === true || e.metaKey === true)) || 
                 // Allow: home, end, left, right, down, up
                (e.keyCode >= 35 && e.keyCode <= 40)) {
                     // let it happen, don't do anything
                     return;
            }
        // Ensure that it is a number and stop the keypress
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });
        
    });



</script>

<style>
    .admin__page-section-item.order-totals {
        float: none;
        width: 70%;
    }
    .admin__table-primary th, .admin__table-primary td{
        padding: 10px 8px;
    }
</style>
<script type="text/javascript">
require([
'jquery', 
'jquery/ui', 
'jquery/validate',
'mage/translate'
], function($){ 

    $('.qty-field-po').keyup(function(){
        if (parseInt($(this).val()) > parseInt($(this).attr('max'))){
            $(this).val($(this).attr('max'));
        }
    });
});
 </script>