<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_RequestToQuote
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

?>

<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
    $poId = $block->getPoIncrementId();
    $created = $block->getCreatedAt();
    $customer_id = $block->getCustomerId();
    $customer_email = $block->getCustomer($customer_id)->getEmail();
    $customer_name = $block->getCustomer($customer_id)->getName();
    $address = $block->getCustomerAddress();
    $po = $block->getItems();
    $quoteData = $block->getQuoteData();
    $poData = $block->getPoData();
    $products = $block->getProductId();
    $vendor_id = $block->getVendorId();
    $subtotal = 0;

?>
<div id="container" class="main-col">
    <section class="admin__page-section order-view-account-information">
        <div class="admin__page-section-title">
            <span class="title"><?php echo __("PO Information");?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-information">
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo '# '.$poId; ?></span>
                </div>
                <div class="admin__page-section-item-content">
                    <table class="admin__table-secondary order-information-table">
                        <tbody><tr>
                            <th><?php echo __("PO Date");?></th>
                            <td><?php echo $created;?></td>
                        </tr>
                        <tr>
                            <th><?php echo __("PO Status");?></th>
                            <td><span id="order_status"><?php echo $block->getStatus(); ?></span></td>
                        </tr>

                        </tbody></table>
                </div>
            </div>

            <div class="admin__page-section-item order-account-information">
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo __("Account Information");?></span>
                    <div class="actions"></div>
                </div>
                <div class="admin__page-section-item-content">
                    <table class="admin__table-secondary order-account-information-table">
                        <tbody><tr>
                            <th><?php echo __("Customer Name");?></th>
                            <td>
                                <span><?php echo $customer_name;?></span>
                            </td>
                        </tr>
                        <tr>
                            <th><?php echo __("Email Id");?></th>
                            <td><?php echo $customer_email;?></td>

                        </tr>
                        <tr>
                            <th><?php echo __("Customer Group");?></th>
                            <td><?php echo $block->getCustomerGroup($customer_id)?></td>
                        </tr>
                        </tbody></table>
                </div>
            </div>
        </div>
    </section>

    <section class="admin__page-section order-addresses">
        <div class="admin__page-section-title">
            <span class="title"><?php echo __("Shipping & Handling Information");?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-billing-address">
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo __('Shipped To');?></span>
                </div>
                <address class="admin__page-section-item-content"><?php echo $customer_name;?><br>

                    <?php echo $address['street'];?><br>
                    <?php echo $address['city'];?>, <?php echo $address['state'];?>, <?php echo $address['pincode'];?>
                    <?php echo $address['country'];?><br>
                    <?php echo __("Telephone :");?>
                    <?php echo $address['telephone'];?>

                </address>
            </div>
            <div id="order-billing_method" class="admin__page-section-item order-billing-method">
                <div class="admin__page-section-title">
                    <span class="title"><?php echo __("Shipping Method");?></span>
                </div>
                <div id="order-billing_method_form">
                    <dl class="admin__payment-methods">
                        <dt class="admin__field-option">
                            <span class="no-display">
                                <input id="p_method_free" value="free" name="payment[method]" class="admin__control-radio" checked="checked" type="radio">
                            </span>
                            <label class="admin__field-label" for="p_method_free"><?php echo $quoteData->getShipmentMethod() ;?></label>
                        </dt>
                        <dd class="admin__payment-method-wapper"></dd>
                    </dl>
                </div>
                <div class="admin__page-section-item-content">
                    <strong><?php echo __("Shipment Amount");?></strong>
                    <span class="price"><?php echo $priceHelper->currency($quoteData->getShippingAmount(), true, false);?></span>
                </div>
            </div>
        </div>
    </section>
    

    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title">Items Invoiced</span>
        </div>

        <div id="invoice_item_container" class="admin__page-section-content">
            <div class="admin__table-wrapper">
                <table class="data-table admin__table-primary order-invoice-tables">
                    <thead>
                    <tr class="headings">
                        <th class="col-product"><span><?php echo __("Product ");?></span></th>
                        <th class="col-price"><span><?php echo __("Original Price ");?></span></th>
                        <th class="col-price"><span><?php echo __("Quoted Price ");?></span></th>
                        <th class="col-price"><span><?php echo __("PO Price ");?></span></th>
                        <th class="col-qty"><span><?php echo __("Quoted Qty ");?></span></th>
                        <th class="col-qty"><span><?php echo __("PO Qty ");?></span></th>
                        <th class="col-qty"><span><?php echo __("Remaining Qty ");?></span></th>
                        <th class="col-total last"><span><?php echo __("PO Row Total");?></span></th>
                    </tr>
                    </thead>
                    <tbody class="even">
                    <?php foreach ($poData->getData() as $value) {
                        $product_id = $value['product_id'];
                        $product = $block->getProduct($product_id);
                        $unitprice = $block->getProductIndividualPrice($product_id);
                        $remainingQty = $block->getRemainingData($product_id);
                        if(!$remainingQty)
                            $remainingQty = 0;
                        $subtotal += $value['po_price'];
                        //print_r($value);die("dfkshf0");
                        ?>
                    <tr>
                        <td class="col-product">
                            <div id="order_item_1_title" class="product-title"><?php echo $product->getName();  ?>
                                    </div>

                            <div class="product-sku-block">
                                <span>SKU:</span> <?php echo $product->getSku();  ?>    </div>

                        </td>
                        <td class="col-price">

                            <div class="price-excl-tax">

                                <span class="price"><span><?php echo $block->getCurrencyCode();  ?></span><span class="price"><?php echo $product->getPrice();  ?></span></span>
                            </div>
                        </td>
                        <td class="col-price">

                            <div class="price-excl-tax">

                                <span class="price"><span><?php echo $block->getCurrencyCode();  ?></span><span class="price"><?php echo $value['quoted_price'];  ?></span></span>
                            </div>
                        </td>
                        <td class="col-qty"><?php echo $block->getCurrencyCode();  ?><?php echo $value['po_price'];  ?></td>
                        <td class="col-qty"><?php echo $value['quoted_qty'];  ?></td>
                        <td class="col-qty"><?php echo $value['product_qty'];  ?></td>
                        <td class="col-qty"><?php echo $remainingQty;  ?></td>
                        <td class="col-qty"><?php echo $priceHelper->currency($value['po_price'], true, false);  ?></td>

                    </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title">Order Total</span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-totals">
                <div class="admin__page-section-item-title">
                    <span class="title">Order Totals</span>
                </div>
                <table class="data-table admin__table-secondary order-subtotal-table">
                <tfoot>
                    <tr class="col-0">
                        <td class="label">
                            <strong><?php echo __('Grand Total');?></strong>
                        </td>
                        <td>
                            <strong><span class="price"><?php echo $priceHelper->currency($block->getGrandTotal(), true, false);  ?></span></strong>
                        </td>
                    </tr>
                </tfoot>
                <tbody>
                    <tr class="col-0">
                        <td class="label"><?php echo __('Subtotal');?></td>
                        <td>
                            <span><span class="price"><?php echo $priceHelper->currency($subtotal, true, false);?></span></span>
                        </td>
                    </tr>
                    <tr class="col-1">
                        <td class="label"><?php echo __('Shipping &amp; Handling');?></td>
                            <td>
                                <span><span class="price"><?php echo $priceHelper->currency($quoteData->getShippingAmount(), true, false);?></span></span>
                            </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</section>
    <script>
        require([
            'jquery',
            'mage/backend/form',
            'mage/backend/validation'
        ], function($){

            $('#edit_form').form()
                .validation({
                    validationUrl: '',
                    highlight: function(element) {
                        var detailsElement = $(element).closest('details');
                        if (detailsElement.length &amp;&amp; detailsElement.is('.details')) {
                            var summaryElement = detailsElement.find('summary');
                            if (summaryElement.length &amp;&amp; summaryElement.attr('aria-expanded') === "false") {
                                summaryElement.trigger('click');
                            }
                        }
                        $(element).trigger('highlight.validate');
                    }
                });

        });
    </script>
</div>