<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author 		CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<?php 
$element = $this->getElement();
$category_ids = array();
?>
<input class="category_ids" name="<?php echo $element->getName();?>" id="<?php echo $element->getHtmlId()?>" type="hidden" value="<?php  echo $this->getIdsString();?>"/>
<div id="<?php echo $element->getHtmlId()?>_tree" class="tree"></div>

