<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */

?>
<div class="vendor-forgpass-wrapper">
	<div class="forgot-panel panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><?php echo __('Forgot Your Password?') ?></h3>
		</div>
		<div class="panel-body">
			<form class="form password forget"
			  action="<?php echo $block->getForgotPasswordPostUrl(); ?>"
			  method="post"
			  id="form-validate"
			  data-mage-init='{"validation":{}}'>
			
			<fieldset>
					<h2 class="legend"><?php echo __('Retrieve your password here') ?></h2>
					<p><?php echo __('Please enter your email below and we will send you a new password.') ?></p>
					<div class="input-box">
						<input placeholder="<?php echo __('Email Address') ?>" type="text" name="email" alt="email" id="email_address" class="form-control input-text required-entry validate-email" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}" />
					</div>
					 <?= $block->getChildHtml('form_additional_info') ?>
				</fieldset>
				<div class="buttons-set">
					<p class="back-link"><a href="<?php echo $block->getLoginUrl(); ?>"><small>&laquo; </small><?php echo __('Back to Login') ?></a></p>
					<button type="submit" title="<?php echo __('Submit') ?>" class="button"><span><span><?php echo __('Submit') ?></span></span></button>
				</div>
			</form>
		</div>
	</div>
</div>
