<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<?php if($this->getCollection()->getSize()): ?>

    <?php if($this->getUseContainer()): ?>
    <div class="row"> 
    <div style="text-align:center;">
    <?php endif ?>
    <?php if($this->getShowAmounts()): ?>
    <div class="col-md-4 left-pager">    
    <p class="amount">
        <?php if($this->getLastPageNum()>1): ?>
            <?php echo __('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
        <?php else: ?>
            <strong><?php echo __('%s Item(s)', $this->getTotalNum()) ?></strong>
        <?php endif; ?>
    </p>
    </div>
    <?php endif ?>
    <?php if($this->getLastPageNum()>1): ?>
    <div class="col-md-4 center-pager pages">
    <div class="paging_simple_numbers" >
        <ul  class="pagination" style="margin:0;">
        <?php if (!$this->isFirstPage()): ?>
            <li class="paginate_button previous" >
                <a class="previous<?php if(!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif;?>" href="<?php echo $this->getPreviousPageUrl() ?>" title="<?php echo __('Previous') ?>">
                    <?php if(!$this->getAnchorTextForPrevious()): ?>
                        <img src="<?php echo $this->getSkinUrl('images/ced/csmarketplace/pager_arrow_left.gif') ?>" alt="<?php echo __('Previous') ?>" class="v-middle" />
                    <?php else: ?>
                        <?php echo $this->getAnchorTextForPrevious() ?>
                    <?php endif;?>
                </a>
            </li>
            <?php else:?>
             <li class="paginate_button previous disabled" style="background-color:grey;">
                <a class="previous<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>" href="#" title="<?php echo __('Next') ?>">
                    <?php if(!$this->getAnchorTextForNext()): ?>
                        <img src="<?php echo $this->getSkinUrl('images/ced/csmarketplace/pager_arrow_left.gif') ?>" alt="<?php echo __('Next') ?>" class="v-middle" />
                    <?php else: ?>
                        <?php echo $this->getAnchorTextForNext() ?>
                    <?php endif;?>
                </a>
            </li>    
        <?php endif;?>

        <?php if ($this->canShowFirst()): ?>
            <li class="paginate_button " aria-controls="dataTables-example"><a class="first" href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
        <?php endif;?>

        <?php if ($this->canShowPreviousJump()): ?>
            <li class="paginate_button" ><a class="previous_jump" title="" href="<?php echo $this->getPreviousJumpUrl() ?>">...</a></li>
        <?php endif;?>

        <?php foreach ($this->getFramePages() as $_page): ?>
            <?php if ($this->isPageCurrent($_page)): ?>
                <li class="paginate_button active"><a href="#"><?php echo $_page ?></a></li>
            <?php else: ?>
                <li class="paginate_button " ><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
            <?php endif;?>
        <?php endforeach;?>
        <?php if ($this->canShowNextJump()): ?>
            <li class="paginate_button " ><a class="next_jump" title="" href="<?php echo $this->getNextJumpUrl() ?>">...</a></li>
        <?php endif;?>

        <?php if ($this->canShowLast()): ?>
          <li class="paginate_button " ><a class="last" href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
        <?php endif;?>

        <?php if (!$this->isLastPage()): ?>
            <li class="paginate_button next" >
                <a class="next<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>" href="<?php echo $this->getNextPageUrl() ?>" title="<?php echo __('Next') ?>">
                    <?php if(!$this->getAnchorTextForNext()): ?>
                        <img src="<?php echo $this->getSkinUrl('images/ced/csmarketplace/pager_arrow_right.gif') ?>" alt="<?php echo __('Next') ?>" class="v-middle" />
                    <?php else: ?>
                        <?php echo $this->getAnchorTextForNext() ?>
                    <?php endif;?>
                </a>
            </li>
        <?php else:?>
             <li class="paginate_button next disabled" style="background-color:grey;" >
                <a class="next<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>" href="#" title="<?php echo __('Next') ?>">
                    <?php if(!$this->getAnchorTextForNext()): ?>
                        <img src="<?php echo $this->getSkinUrl('images/ced/csmarketplace/pager_arrow_right.gif') ?>" alt="<?php echo __('Next') ?>" class="v-middle" />
                    <?php else: ?>
                        <?php echo $this->getAnchorTextForNext() ?>
                    <?php endif;?>
                </a>
            </li>
        <?php endif;?>
        </ul>
    </div>
    </div>
    <?php else: ?>
         <div class="col-md-4 center-pager"></div>
    <?php endif; ?>
    <?php if($this->getShowPerPage()): ?>
    <div class="col-md-4 right-pager">
    <div class="limiter">
        <label><?php echo __('Show') ?></label>
        <select onchange="setLocation(this.value)">
        <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
            <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                <?php echo $_limit ?>
            </option>
        <?php endforeach; ?>
        </select> <?php echo __('per page') ?>
    </div>
    </div>
    <div style="clear:both"></div>
    <?php endif ?>


    <?php if($this->getUseContainer()): ?>
    </div>
    </div>
    <?php endif ?>
<?php endif ?>
