<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

?>
<?php 
$helper = $this->helper('Ced\CsMarketplace\Helper\Tool\Image');
$logo = $helper->getStoreConfig("ced_loginsignup/header/logo",$this->getCurrentStoreId())?"ced/csmarketplace/".$helper->getStoreConfig("ced_loginsignup/header/logo",$this->getCurrentStoreId()):'';
$logoImage = $helper->getResizeImage($logo, 'logo', 190, 45);
?>

<div class="ced_vendor_header">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="pull-left">
					<div class="v_header_logo">
						<?php if($logo):?>
							<a href="<?php echo $this->getBaseUrl(); ?>" target="_blank">
								<img src="<?php echo $logoImage ?>" alt="vendor panel logo">
							</a>
						<?php else:?>
							<img src="<?php echo $block->getViewFileUrl('images/demo.png'); ?>" alt="vendor panel logo">
						<?php endif;?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-title">
    <h1><?php echo __('Change Account Password') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $action ?>" method="post" id="form-validate">
    <div class="fieldset">
        <h2 class="legend"><?php echo __('Change Account Password') ?></h2>
        <ul class="form-list">
            <li>
                <label for="current_password" class="required"><em>*</em><?php echo __('Current Password') ?></label>
                <div class="input-box">
                    <input type="password" title="<?php echo __('Current Password') ?>" class="input-text required-entry" name="current_password" id="current_password" />
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="password" class="required"><em>*</em><?php echo __('New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo __('New Password') ?>" class="input-text required-entry validate-password" name="password" id="password" />
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation" class="required"><em>*</em><?php echo __('Confirm New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo __('Confirm New Password') ?>" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo __('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->getUrl('customer/account') ?>"><small>&laquo; </small><?php echo __('Back') ?></a></p>
        <button type="submit" title="<?php echo __('Save Password') ?>" class="button"><span><span><?php echo __('Save Password') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
 //   var dataForm = new VarienForm('form-validate');
//]]>
</script>
<div class="ced_vendor_footer">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="ced_vendor_footer_links">
					<ul>
						<li>
							<a href="<?php echo $this->getBaseUrl(); ?>">
								<?php echo __('Home') ?>
							</a>
							|
						</li>
						<li>
							<a href="<?php echo $this->getBaseUrl().'contact'; ?>">
								<?php echo __('Contact') ?>
							</a>
							|
						</li>
						<!--<li>
							<a href="<?php //echo $this->getBaseUrl().'#'; ?>">
								<?php //echo __('faq') ?>
							</a>
						</li>-->
					</ul>
				</div>
				<p>&copy; 2018 - cedcommerce.com (site name) vendor Portal</p>
			</div>
		</div>
	</div>
</div>