<?php 
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */
?>
<?php 
$helper = $this->helper('Ced\CsMarketplace\Helper\Tool\Image');
$logo = $helper->getStoreConfig("ced_loginsignup/header/logo", $this->getCurrentStoreId()) ? "ced/csmarketplace/".$helper->getStoreConfig("ced_loginsignup/header/logo",$this->getCurrentStoreId()) : ''; 
$logoImage = $helper->getResizeImage($logo, 'logo', 335, 106); 
$footerContent = $helper->getStoreConfig("ced_csmarketplace/general/footer_content",$this->getCurrentStoreId());
$isfooterEnable = $helper->getStoreConfig("ced_csmarketplace/general/enable_footer",$this->getCurrentStoreId());
?>


<div class="ced_vendor_header">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="pull-left">
					<div class="v_header_logo">
						<?php if($logo):?>
							<a href="<?php echo $this->getBaseUrl(); ?>" target="_blank">
								<img src="<?php echo $logoImage ?>" alt="vendor panel logo">
							</a>
						<?php else:?>
							<a href="<?php echo $this->getBaseUrl(); ?>" target="_blank">
							<img src="<?php echo $block->getViewFileUrl('images/demo.png'); ?>" alt="vendor panel logo">
							</a>
						<?php endif;?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="ced_vendor_before_login_wrapper">
	<div class="ced_vendor_before_wrap clearfix">
		<div class="ced_vendor_forgot">
			
			<div class="right">
				<h3 class="ced_vendor_from_title">
					<?php echo __('Forgot Your Password ?') ?>
				</h3>
				<div class="panel_body login_form_body">
					<form class="form password forget"
					action="<?php echo $block->getForgotPasswordPostUrl(); ?>"
					method="post"
					id="form-validate"
					data-mage-init='{"validation":{}}'>
					<fieldset>
						<p><?php echo __('Please enter your email address below to receive reset link.') ?></p>
						<div class="input-box">
							<input placeholder="<?php echo __('Email Address') ?>" type="text" name="email" alt="email" id="email_address" class="form-control input-text required-entry validate-email" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}" />
						</div>
						 <?= $block->getChildHtml('form_additional_info') ?>
					</fieldset>
					<div class="buttons-set">
						<p class="back-link"><a href="<?php echo $block->getLoginUrl(); ?>"><small>&laquo; </small><?php echo __('Back to Login') ?></a></p>
						<button type="submit" title="<?php echo __('Reset my password') ?>" class="button"><span><span><?php echo __('Reset my password') ?></span></span></button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
</div>
<?php if($isfooterEnable): ?>
<div class="ced_vendor_footer">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="ced_vendor_footer_links">
					<ul>
						<li>
							<a href="<?php echo $this->getBaseUrl(); ?>">
								<?php echo __('Home') ?>
							</a>
							|
						</li>
						<li>
							<a href="<?php echo $this->getBaseUrl().'contact'; ?>">
								<?php echo __('Contact') ?>
							</a>
							|
						</li>
						<!--<li>
							<a href="<?php //echo $this->getBaseUrl().'#'; ?>">
								<?php //echo __('faq') ?>
							</a>
						</li>-->
					</ul>
				</div>
			    <p><?php echo $footerContent; ?></p>
			</div>
		</div>
	</div>
</div>
<?php endif;?>