<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */
?>

<?php 
$helper = $this->helper('Ced\CsMarketplace\Helper\Tool\Image');
$logo = $helper->getStoreConfig("ced_loginsignup/header/logo",$this->getCurrentStoreId())?"ced/csmarketplace/".$helper->getStoreConfig("ced_loginsignup/header/logo",$this->getCurrentStoreId()):'';
$logoImage = $helper->getResizeImage($logo, 'logo', 190, 45);
$footerContent = $helper->getStoreConfig("ced_csmarketplace/general/footer_content",$this->getCurrentStoreId());
$isfooterEnable = $helper->getStoreConfig("ced_csmarketplace/general/enable_footer",$this->getCurrentStoreId());
?>

<div class="ced_vendor_header">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="pull-left">
					<div class="v_header_logo">
						<?php if($logo):?>
							<a href="<?php echo $this->getBaseUrl(); ?>" target="_blank">
								<img src="<?php echo $logoImage ?>" alt="vendor panel logo">
							</a>
						<?php else:?>
							<a href="<?php echo $this->getBaseUrl(); ?>" target="_blank">
								<img src="<?php echo $block->getViewFileUrl('images/demo.png'); ?>" alt="vendor panel logo">
							</a>
						<?php endif;?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="ced_vendor_before_login_wrapper">
	<div class="ced_vendor_before_wrap clearfix">
		<div class="ced_vendor_login">
			<div class="right">
				<h3 class="ced_vendor_from_title">
					<?php echo __('Vendor Login') ?>
				</h3>
				<div class="panel_body login_form_body">
					<form class="form form-login" id="login-form" method="post" 
						action="<?php echo $block->getPostActionUrl() ?>" data-mage-init='{"validation":{}}'>
						<?php echo $block->getBlockHtml('formkey'); ?>
						<fieldset>
							<div class="col2-set">
								<div class="col-2 registered-users">
									<div class="content">
										<p><?php echo __('If you have vendor account, sign in with your email address') ?></p>
										<div class="form-group input-box">
											<input type="email" name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" id="email" class="form-control input-text required-entry validate-email" placeholder="<?php echo __('Email Address') ?>" title="<?php echo __('Email Address') ?>" data-validate="{required:true, 'validate-email':true}" />
										</div>
										<div class="form-group input-box"><input type="password" name="login[password]" class="form-control input-text required-entry validate-password" placeholder="<?php echo __('Password') ?>" id="pass" title="<?php echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}" />
										</div>
										<div class="clearfix">
											<div class="checkbox">
												<input name="remember" type="checkbox" id="remember" value="<?php echo __('Remember Me'); ?>">
												<label for="remember">
													<?php echo __('Remember Me'); ?>
												</label>
											</div> 
											<a href="<?php echo $block->getForgotPasswordUrl(); ?>" class="f-right forgotpass">
												<?php echo __('Forgot Your Password?') ?>
											</a>
										</div>
										<button type="submit" class="button" title="<?php echo __('Login') ?>" name="send" id="send2">
											<span><span><?php echo __('Login') ?></span></span>
										</button>
									</div>
								</div>
							</div>
							<div class="vendor_exitance">
								<?php echo __('Do not have vendor account ?') ?>
								<a href="#" class="new_venor"><?php echo __('Create vendor account') ?></a>
							</div>
						</fieldset>
					</form>
				</div>
				<div class="panel_body sign_up_form_body">
					<?php echo $block->getChildHtml('ced_vendorsociallogin_login');?>
				</div>
			</div>
		</div>
	
		<div class="ced_vendor_register clearfix">
			<div class="right">
				<h3 class="ced_vendor_from_title"><?php echo __("Create Vendor Account")?></h3>
				<div class="panel_body sign_up_form_body">
					<?php echo $block->getChildHtml('customer_form_register') ?>
				</div>
				<div class="panel_body sign_up_form_body">
					<?php echo $this->getChildHtml('ced_vendorsociallogin_login');?>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	<?php $minicart = [
		'shoppingCartUrl' => '',
		'checkoutUrl' => '',
		'updateItemQtyUrl' => '',
		'removeItemUrl' => '',
		'imageTemplate' => '',
		'baseUrl' => ''
	]; ?>
	window.checkout = <?php echo \Zend_Json::encode($minicart); ?>;
	require([
		'jquery',
		'mage/mage',
		'checkoutbalance',
		'captcha'
		], function($){
			$(document).ready(function(){
				$(".new_venor").click(function(){
					$('.ced_vendor_login').fadeOut(1);
					$(".ced_vendor_register").fadeIn(1000);
				});
				$(".axisting_venor").click(function(){
					$('.ced_vendor_register').fadeOut(1);
					$(".ced_vendor_login").fadeIn(1000);
				});
			});
		});
</script>
<?php if($isfooterEnable): ?>
<div class="ced_vendor_footer">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="ced_vendor_footer_links">
					<ul>
						<li>
							<a href="<?php echo $this->getBaseUrl(); ?>">
								<?php echo __('Home') ?>
							</a>
							|
						</li>
						<li>
							<a href="<?php echo $this->getBaseUrl().'contact'; ?>">
								<?php echo __('Contact') ?>
							</a>
							|
						</li>
						<!--<li>
							<a href="<?php //echo $this->getBaseUrl().'#'; ?>">
								<?php //echo __('faq') ?>
							</a>
						</li>-->
					</ul>
				</div>
				<p><?php echo $footerContent; ?></p>
			</div>
		</div>
	</div>
</div>
<?php endif;?>