<?php
$quote_data = $block->getQuoteData();
$customer_data = $block->getCustomerData();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); 
$address = $block->getCustomerAddress();
?>
<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?php echo __('Address And Shipping Information');?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-shipping-address">
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo __('Shipping Address')?></span>
                <div class="actions"></div>
            </div>
            <address class="admin__page-section-item-content"><?php echo $customer_data->getName();?><br>
                <?php echo $address['street']; ?><br>
                <?php echo $address['city']; ?>,  <?php echo $address['state']; ?>, <?php echo $address['pincode']; ?><br>
                <?php echo $address['country']; ?><br>
                T: <?php echo $address['telephone']; ?>
            </address>
        </div>
        <div class="admin__page-section-item order-shipping-info">
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo __("Shipping Information");?></span>
                </div>
                <div class="admin__page-section-item-content">
                    <div class="shipping-description-wrapper">

                        <div class="shipping-description-title"><?php echo __("Shippment Method Selected:");?><?php echo $quote_data->getShipmentMethod();?></div>
                        <div class="shipping-description-content">
                            <?php echo __("Total Shipping Charges:");?>
                            <span class="price"><?php echo $priceHelper->currency($quote_data->getShippingAmount(), true, false)?></span>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</section>
<style>
.order-shipping-address{
    width: 50%;
    float: left;
}
.order-shipping-info{
    float: left;
    width: 50%;
}
</style>