<?php
/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category    Ced
  * @package     Ced_CsOrder
  * @author   	 CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license      http://cedcommerce.com/license-agreement.txt
  */
?>
<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $csOrderHelper = $objectManager->get('Ced\CsOrder\Helper\Data');
    $register = $objectManager->get('Magento\Framework\Registry');
    $vorder = $register->registry('current_vorder');
?>
<form id="edit_form" method="post" action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>">
    <?php echo $block->getBlockHtml('formkey')?>
    <?php  $_order = $block->getCreditmemo()->getOrder() ?>

    <?php echo $block->getChildHtml('order_info') ?>

    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?php /* @escapeNotVerified */ echo __('Payment &amp; Shipping Method') ?></span>
        </div>
        <div class="admin__page-section-content">
        <?php if (!$_order->getIsVirtual()): ?>
        <div class="admin__page-section-item order-payment-method">
        <?php else: ?>
        <div class="admin__page-section-item order-payment-method order-payment-method-virtual">
        <?php endif; ?>

            <?php /* Billing Address */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Payment Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="order-payment-method-title"><?php echo $block->getChildHtml('order_payment') ?></div>
                <div class="order-payment-currency">
                    <?php /* @escapeNotVerified */ echo __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?>
                </div>
                <div class="order-payment-additional">
                    <?php echo $block->getChildHtml('order_payment_additional'); ?>
                </div>
            </div>
        </div>

        <?php if (!$_order->getIsVirtual()): ?>
        <div class="admin__page-section-item order-shipping-address">
            <?php /* Shipping Address */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Shipping Information') ?></span>
            </div>
            <div class="admin__page-section-item-content shipping-description-wrapper">
                <div class="shipping-description-title"><?php echo $block->escapeHtml($vorder->getShippingDescription()) ?></div>
                <div class="shipping-description-content">
                    <?php /* @escapeNotVerified */ echo __('Total Shipping Charges'); ?>:
                    
                    <?php if ($this->helper('Magento\Tax\Helper\Data')->displaySalesPriceInclTax($block->getSource()->getStoreId())): ?>
                        <?php $_excl = $block->displayShippingPriceInclTax($vorder); ?>
                    <?php else: ?>
                        <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
                    <?php endif; ?>
                    <?php $_incl = $block->displayShippingPriceInclTax($vorder); ?>

                    <?php /* @escapeNotVerified */ echo $_incl; ?>
                    <?php if ($this->helper('Magento\Tax\Helper\Data')->displaySalesBothPrices($block->getSource()->getStoreId()) && $_incl != $_excl): ?>
                        (<?php /* @escapeNotVerified */ echo __('Incl. Tax'); ?> <?php /* @escapeNotVerified */ echo $_incl; ?>)
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <?php endif; ?>
        </div>
    </section>

    <div id="creditmemo_item_container">
        <?php echo $block->getChildHtml('order_items') ?>
    </div>
</form>
