<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>

<?php $_order = $this->getOrder() ?>
  <div class="order-items order-details table-responsive">
		<table id="my-products-table" class="data-table table table-bordered table-hover table-striped">
        <col width="1"/>
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
            <tr class="headings">
                <th class="head"><?php echo __('Product') ?></th>
                <th class="head"><span class="nobr"><?php echo __('Original Price') ?></span></th>
                <th class="head"><?php echo __('Price') ?></th>
                <th class="a-center head"><?php echo __('Qty') ?></th>
                <th class="head"><?php echo __('Subtotal') ?></th>
                <th class="head"><span class="nobr"><?php echo __('Tax Amount') ?></span></th>
                <th class="head"><span class="nobr"><?php echo __('Discount Amount') ?></span></th>
                <th class="last head"><span class="nobr"><?php echo __('Row Total') ?></span></th>
            </tr>
        </thead>
        <tfoot>
       	<?php echo $block->getChildHtml('order_totals') ?>
       	<?php echo $block->getChildHtml('earn') ?>
       </tfoot>
         <?php 		
		$vorder = $block->_objectManager->get('Magento\Framework\Registry')->registry('current_vorder');
		$_items = $block->_objectManager->get('Ced\CsMarketplace\Model\Vorders')->load($vorder->getId())->getItemsCollection(); ?>
        
        <?php $i=0;foreach ($_items as $_item):?>
            <?php if ($_item->getParentItem()) continue; else $i++;?>
            <tbody class="<?php echo $i%2?'even':'odd' ?>">
                <?php echo $block->getItemHtml($_item) ?>
                <?php echo $block->getItemExtraInfoHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
</table>
  </div>