<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author 		CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<!-- <button style="line-height: 1.2em; float: right;" class="button btn btn-primary uptransform" onclick="window.location='<?php //echo $this->getUrl('teammember/account/edit',array('_secure'=>true,'teammemberid'=>$this->session->getTeamMemberId())); ?>';" title="Edit" type="button">
				<span>
					<span><?php echo __('Edit') ?></span>
				</span>
			</button> -->
<div class="">
	<div class="block block-dashboard-info">
		<div class="block-title">
			<strong>
				<?php echo __('dashboard') ?>
			</strong>
		</div>
		<div class="block-content">
			<div class="box teammember-profile-information">
				<strong class="box-title">
					<span>
						<?php echo __('Profile Information') ?>
					</span>
				</strong>
				<div class="box-content">
					<p>
						<strong><?php echo __('Name:') ?></strong>
						<span><?php echo $block->getTeamMember()->getName() ?></span>	<br>
						
						<strong><?php echo __('Email:') ?></strong>
						<span><?php echo $block->getTeamMember()->getEmail() ?></span>	<br>
						<div class="logo-wrapper">
							<strong class="pulls-left"><?php echo __('Logo:') ?></strong>
							<span><img src="<?php echo $block->getImageSrc().$block->getTeamMember()->getLogo() ?>" id="profile_picture_image" title="" alt="" class="small-image-preview v-middle" width="" height=""><span/>
						</div>
						
							
					</p>
				</div>
			</div>
			<div class="box teammember-address-information">
				<strong class="box-title">
					<span>
						<?php echo __('Address Information') ?>
					</span>
				</strong>
				<div class="box-content">
					<strong><?php echo __('Address::') ?></strong>
					<span><?php echo $block->getTeamMember()->getAddress() ?></span>	<br>
					
					<strong><?php echo __('City::') ?></strong>
					<span><?php echo $block->getTeamMember()->getCity() ?></span>	<br>
					
					<strong><?php echo __('Contact::') ?></strong>
					<span><span/>	<?php echo $block->getTeamMember()->getContactNo() ?><br>
				</div>
			</div>
		</div>
	</div>
	<div class="ced-body-panel" style="margin-top:10px;">
		<!-- <div class="panel panel-default">
			<div class="panel-heading uptransform" style="line-height:31px;font-weight:bold;padding:4px 15px;font-size:17px;">
				<?php echo __('Profile Information') ?>
				
			</div>
			<div style="clear:both"></div>
			<div class="panel-body ced-teammember-dashboard">
				<div class="welcome-msg">
					<strong><?php echo __('Name:') ?></strong>
					<span><?php echo $block->getTeamMember()->getName() ?><span/>	<br>
					
					<strong><?php echo __('Email:') ?></strong>
					<span><?php echo $block->getTeamMember()->getEmail() ?><span/>	<br>
					
					<strong><?php echo __('Logo:') ?></strong>
					<span><img src="<?php echo $block->getImageSrc().$block->getTeamMember()->getLogo() ?>" id="profile_picture_image" title="" alt="" class="small-image-preview v-middle" width="200px" height="200px"><span/>	<br>
				</div>
	       </div>
		</div> -->

	<!-- <div class="panel panel-default" style = "float:right;">
			<div class="panel-heading" style="line-height:31px;font-weight:bold;padding:4px 15px;font-size:17px;">
				<?php echo __('Address Information') ?>
				
			</div>
			<div style="clear:both"></div>
			<div class="panel-body">
				<div class="welcome-msg">
					<strong><?php echo __('Address::') ?></strong>
					<span><?php echo $block->getTeamMember()->getAddress() ?><span/>	<br>
					
					<strong><?php echo __('City::') ?></strong>
					<span><?php echo $block->getTeamMember()->getCity() ?><span/>	<br>
					
					<strong><?php echo __('Contact::') ?></strong>
					<span><span/>	<?php echo $block->getTeamMember()->getContactNo() ?><br>
				</div>
	       </div>
	</div> -->
	</div>
	<div class="buttons-set">
    	<p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo __('Back') ?></a></p>
	</div>
</div>