<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>

<script>
require([
    "jquery",
    "jquery/ui"
], function($){

//<![CDATA[
    $.extend(true, $, {
        calendarConfig: {
            dayNames: <?php echo $days['wide']?>,
            dayNamesMin: <?php echo $days['abbreviated']?>,
            monthNames: <?php echo $months['wide']?>,
            monthNamesShort: <?php echo $months['abbreviated']?>,
            infoTitle: "<?php echo __('About the calendar');?>",
            firstDay: <?php echo $firstDay?>,
            closeText: "<?php echo __('Close');?>",
            currentText: "<?php echo __('Go Today'); ?>",
            prevText: "<?php echo __('Previous');?>",
            nextText: "<?php echo __('Next');?>",
            weekHeader: "<?php echo __('WK'); ?>",
            timeText: "<?php echo __('Time');?>",
            hourText: "<?php echo __('Hour');?>",
            minuteText: "<?php echo __('Minute');?>",
            dateFormat: $.datepicker.RFC_2822,
            showOn: "button",
            showAnim: "",
            changeMonth: true,
            changeYear: true,
            buttonImageOnly: null,
            buttonImage: null,
            showButtonPanel: true,
            showWeek: true,
            timeFormat: '',
            showTime: false,
            showHour: false,
            showMinute: false
        }
    });

    enUS = <?php echo $enUS?>; // en_US locale reference
//]]>

});
</script>
