<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\Options */
?>
<fieldset class="fieldset">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Manage Options (values of your attribute)') ?></span></legend>
    <div id="manage-options-panel">
        <table class="admin__control-table">
            <thead>
                <tr id="attribute-options-table">
                    <th class="col-draggable"></th>
                    <th class="col-default control-table-actions-th"><?php /* @escapeNotVerified */ echo __('Is Default') ?></th>
                    <th class="col-default control-table-actions-th"><?php /* @escapeNotVerified */ echo __('Values') ?></th>
                    <?php
                  //  $storelist = $block->getStores();
                   // foreach ($storelist as $_store):
                        ?>
                        <th><?php /* @escapeNotVerified */ //echo __($_store->getName()) ?></th>
                    <?php // endforeach;
                   // $storetotal = count($storelist) + 3;
                    ?>
                    <th class="col-delete">&nbsp;</th>
                </tr>
            </thead>
            <tbody data-role="options-container" class="ignore-validate"></tbody>
            <tfoot>
            <tr>
                <th colspan="<?php /* @escapeNotVerified */ //echo $storetotal; ?>" class="validation">
                    <input type="hidden" class="required-dropdown-attribute-entry" name="dropdown_attribute_validation"/>
                </th>
            </tr>
            <tr>
                <th colspan="<?php /* @escapeNotVerified */ echo $storetotal=0; ?>" class="col-actions-add">
	                   <td class="col-default control-table-actions-cell">
	                	   <input type="radio" name="radio"/>
	                   </td>
	                   <td class="col-default control-table-actions-cell">
	                	   <input type="text" name="text"/>
	                   </td>
       			</th>
            </tr>
            </tfoot>
        </table>
        <input type="hidden" id="option-count-check" value="" />
    </div>
   
    <?php
 /*  $values = [];
    foreach($block->getOptionValues() as $value) {
        array_push($values, $value->getData());
    } */
    ?>
    <script type="text/x-magento-init">
      
    </script>
</fieldset>
