
<!-- /**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsRma
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */ -->
 <form id="chat_form" method="post" novalidate="novalidate" enctype="multipart/form-data" data-mage-init='{"validation": {}}'>
  <div id="comments_block" class="edit-order-comments">
      <div class="order-history-block" id="history_form">
          <div class="admin__field">
              <label for="history_comment" class="admin__field-label">
                  <?php echo __('Chat Section') ?>
              </label>
              <div class="admin__field-control">
                  <textarea name="comment"
                            rows="3"
                            cols="15"
                            id="history_comment"
                            class="admin__control-textarea" data-validate="{required:true}"></textarea>

              </div>
              <div class="admin__field-control">
                  <span><?php echo __('Attch Your File')?></span><br>
                  <input type="file" name="rma_file">
              </div>
          </div>
          <div class="admin__field">
              <div class="order-history-comments-actions">
                  <button class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" title="Save" type="submit" id="save_butn" 
                    style="float: none;" onclick="chatForm('<?php echo $block->getSubmitUrl()?>')">
                      <span><span><?php echo __('Send Message') ?></span></span>
                  </button>
              </div>
          </div>
      </div>
      <?php echo $block->getBlockHtml('formkey')?>
  </div>
</form>
<?php echo $block->getChildHtml('admin_rma_history')?>
<?php echo $block->getChildHtml('admin_rma_notification')?>  
<script>
  require(
    ['jquery'],
    function($) {
        window.chatForm = function (url) {
            $('#chat_form').attr('action',url);
            $('#chat_form').submit();
        };
    });
</script>

