<!-- /**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsRma
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */ -->
<?php  $notification = $block->getRmaNotificationData();?>
<div class="ui-wrapper order-items">
    <ul class="note-list">
    <?php foreach ($notification as $_item):?>
        <li class="note-list-item">
            <span class="note-list-date"><strong><?php  echo $block->formatDate($_item->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></strong></span>
            <span class="note-list-time"><strong><?php  echo $block->formatTime($_item->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></strong></span>
            <?php if ($_item->getNotificationMessage()): ?>
                <div class="note-list-comment"><?php echo $block->escapeHtml($_item->getNotificationMessage(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?></div>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
