<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<div class="row">
<div class="col-md-12" style="margin-top:10px;">
	<div class="panel panel-default">
		<div class="panel-heading col-md-12" style="text-transform: uppercase;font-weight:bold;padding:4px 15px;">
			<div  style="line-height:31px;font-size:17px;display:inline;text-transform: uppercase;">
			<?php echo __('Products Report') ?>  
			</div>
         </div>
 	<div class="panel-body">
 <?php echo $this->getChildHtml('vproductsReport2.list') ?>
<br/>
<br/>
<div class="col-md-12" id="csmarketplace-vreports-vproducts">
 <?php echo $this->getChildHtml('vproductsReport3.list') ?>
</div>
</div>
</div>
</div>
</div>