<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author      CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php  $_order = $this->getOrder();?>
<?php $currentVendor = $this->getVendor();?>
<table cellspacing="0" cellpadding="0" border="0" width="650"
    style="border: 1px solid #EAEAEA;"
    summary="<?php echo __('Items Ordered') ?>">
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA"
                style="font-size: 13px; padding: 3px 9px"><?php echo __('Product Name') ?></th>
            <th align="left" bgcolor="#EAEAEA"
                style="font-size: 13px; padding: 3px 9px"><?php echo __('SKU') ?></th>
            <th align="center" bgcolor="#EAEAEA"
                style="font-size: 13px; padding: 3px 9px"><?php echo __('Qty') ?></th>
            <th align="right" bgcolor="#EAEAEA"
                style="font-size: 13px; padding: 3px 9px"><?php echo __('Price') ?></th>
        </tr>
    </thead>
    <?php $sum=0; foreach ($_order->getAllItems() as $_item): ?>
    <?php if($_item->getVendorId() != $currentVendor->getId()) continue;?>
    <tbody>
        <td align="left" 
                style="font-size: 13px; padding: 3px 9px"><?php echo $_item->getName()?></td>
        <td align="left"
                style="font-size: 13px; padding: 3px 9px"><?php echo $_item->getSku()?></td>
        <td align="center" 
                style="font-size: 13px; padding: 3px 9px"><?php echo $_item->getQtyOrdered()?></td>
        <td align="right" 
                style="font-size: 13px; padding: 3px 9px"><?php echo $_item->getRowTotal()?></td>
        <?php 
        $sum+=$_item->getRowTotal();
        ?>        
    </tbody>
    <?php endforeach; ?> 
    <tbody>
        <td align="left" bgcolor="#EAEAEA"
                ><?php echo __('SubTotal')?></td>
        <td align="right" bgcolor="#EAEAEA"
                ><?php echo $sum?></td>        
    </tbody>  
</table>
    
