<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsProductReview
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile

?>
<div class="messages">
    <div class="message message-notice message-in-rating-edit">
        <div><?php /* @escapeNotVerified */ echo __('Please specify a rating title for a store, or we\'ll just use the default value.'); ?></div>
    </div>
</div>

<?php echo $block->getFormHtml() ?>
