<?php
/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category    Ced
  * @package     Ced_CsOrder
  * @author   	 CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license      http://cedcommerce.com/license-agreement.txt
  */
?>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$vendorId = $objectManager->get('Magento\Customer\Model\Session')->getVendorId();
$vProducts = $objectManager->get('Ced\CsMarketplace\Model\Vproducts');
?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary order-invoice-tables">
        <thead>
            <tr class="headings">
                <th class="col-product"><span><?php /* @escapeNotVerified */ echo __('Product') ?></span></th>
                <th class="col-price"><span><?php /* @escapeNotVerified */ echo __('Price') ?></span></th>
                <th class="col-qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></th>
                <th class="col-subtotal"><span><?php /* @escapeNotVerified */ echo __('Subtotal') ?></span></th>
                <th class="col-tax"><span><?php /* @escapeNotVerified */ echo __('Tax Amount') ?></span></th>
                <th class="col-discount"><span><?php /* @escapeNotVerified */ echo __('Discount Amount') ?></span></th>
                <th class="col-total last"><span><?php /* @escapeNotVerified */ echo __('Row Total') ?></span></th>
            </tr>
        </thead>
        <?php $_items = $block->getCreditmemo()->getAllItems() ?>
        <?php $i = 0; foreach ($_items as $_item): ?>
		<?php
		if ($vProducts->getVendorIdByProduct($_item->getProductId())!= $vendorId) {
		       continue;
        } ?>
				
            <?php if ($_item->getOrderItem()->getParentItem()) {
            continue;
        } else {
            $i++;
        } ?>
            <tbody class="<?php /* @escapeNotVerified */ echo $i%2 ? 'even' : 'odd' ?>">
                <?php echo $block->getItemHtml($_item) ?>
                <?php echo $block->getItemExtraInfoHtml($_item->getOrderItem()) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
