<?php 
/**
  * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * https://cedcommerce.com/license-agreement.txt
  *
  * @category    Ced
  * @package     Ced_CsMultiSeller
  * @author      CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (https://cedcommerce.com/)
  * @license      https://cedcommerce.com/license-agreement.txt
  */
 
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$helper = $objectManager->get('Ced\CsMultiSeller\Helper\Data');

$title = $this->getTitle();
$is_in_stock="-1";
//print_r($objectManager->get('\Magento\Framework\Registry')->registry('current_product_edit')->getData());die;
$_product = $this->getVproduct()?$this->getVproduct():$objectManager->get('\Magento\Framework\Registry')->registry('current_product_edit');
//print_r($_pro->getName());die;

$checkstatus=$this->getCheckStatus();


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$stock = $objectManager->get('\Magento\CatalogInventory\Api\StockRegistryInterface')->getStockItem(
            $this->getRequest()->getParam('id'),
            $_product->getStore()->getWebsiteId()
        );
//print_r($stock->getData());die;
$stockitem = $stock;

if($_product->getId()){
	$name = $_product->getName();
	$sku = $_product->getSku();
	if($checkstatus==\Ced\CsMarketplace\Model\Vproducts::APPROVED_STATUS){
		$status = $_product->getStatus();
	}
	$qty=$stockitem->getQty();
	if($_product->getId()){
		$is_in_stock = $stockitem->getIsInStock();
	}
	$price=$_product->getPrice();
}

?>
<?php //echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form
	action="<?php echo $this->getSaveUrl();?>"
	enctype="multipart/form-data" method="post"
	id="edit-form" role="form">
	<input type="hidden" name="id" id="product_id"
			value="<?php echo $this->getRequest()->getParam('id','')?>"/>
<div class="row">
<div class="col-md-12" style="margin-top:10px;">
	<div class="panel panel-default">
		<div class="panel-heading col-md-12 uptransform" style="font-weight:bold;padding:4px 15px;">
			<div class="col-md-6 panel_product_heading" style="line-height:31px;font-size:17px;">
			<?php echo $title;if($name) echo " - ".$name; ?>
			</div>
			<div class="buttons-set col-md-6 buttons_scb" style="text-align:right;">				
				<button class="button btn btn-success uptransform product-button" title="Save" type="submit" id="save_butn"
					style="float: none;">
					<span><span><?php echo __('Save') ?></span></span>
				</button>
				<button type="reset" style="float: none;" class="uptransform button btn btn-warning product-button">
					<span><span><?php echo __('Cancel') ?></span></span>
				</button>
				<button style="float: none;" type="button" onCLick="if(confirm('<?php echo __('Are you sure?') ?>'))window.location='<?php echo $this->getDeleteUrl($_product)?>'" title="<?php echo __('Delete')." ".__('Product') ?>" class="uptransform button btn btn-danger product-button delete-button"><span><span><?php echo __('Delete') ?></span></span></button>
				<button style="float: none;" type="button" onCLick="window.location='<?php echo $this->escapeUrl($this->getBackUrl()) ?>'" title="<?php echo __('Back') ?>" class="button btn btn-info uptransform product-button back-button"><span><span><?php echo __('Back') ?></span></span></button>		
			</div>
		</div>
		<div class="panel-body panel-min-height panel-min-height-ak">
		<div class="col-md-12">
			<br/>
			<div style="clear:both;"></div>
			<div class="form-group col-md-6"><label class="required"><em>*</em><?php echo __('SKU') ?></label>:
				<div style="clear:both"></div>
				<div class="input-box col-md-6" style="padding-left:0">
					<input name="product[sku]" id="sku"  type="text" value="<?php echo $sku;?>" class="form-control required-entry input-text" />
				</div>
				<div id="skuavailable" style="line-height:2.3em; display:none;" >
						<span class="sku-success-msg skuavailable">&nbsp;<?php echo __('SKU Available') ?></span>
				</div>
				<div id="skunotavailable" style="line-height:2.3em; display:none;">
						<span class="sku-error-msg skunotavailable">&nbsp;<?php echo __('SKU Already Exist') ?></span>
				</div>
				<div style="clear:both"></div>
			</div>
				
			<div class="form-group col-md-6">
				<label class="required"><em>*</em><?php echo __('Price') ?></label>:
				<div class="input-box form-group input-group price-imput-box ced_currency_setting">
					<div class="wrap-in-grp">
						<span class="input-group-addon"><?php $currency_code = $objectManager->get('Magento\Store\Model\Store')->load($_product->getStoreId())->getBaseCurrencyCode(); echo $objectManager->get('\Magento\Framework\Locale\Currency')->getCurrency($currency_code)->getSymbol(); ?></span>
						<input  type="text" name="product[price]" value="<?php if($price!='') echo $price;?>" id="price" class=" form-control required-entry validate-number validate-zero-or-greater  input-text" />
						<div class="clear"></div>
					</div>
				</div>
			</div>
			
			<div class="form-group col-md-6"><label class="required"><em>*</em><?php echo __('Stock Availability') ?></label>:
				<div class="input-box">
					<select id="is_in_stock" class="form-control select required-entry"
						name="product[stock_data][is_in_stock]">
						<option <?php echo $is_in_stock=="-1"?"selected":" "?> value="-1"><?php echo __('--Please Select--'); ?></option>
						<option <?php echo $is_in_stock==1?"selected":" "?> value="1"><?php echo __('In Stock'); ?></option>
						<option <?php echo $is_in_stock==0?"selected":" "?> value="0"><?php echo __('Out of Stock'); ?></option>
					</select>
				</div>
			</div>
			
			<div class="form-group col-md-6">
				<label class="required"><em>*</em><?php echo __('Stock') ?></label>:
				<div class="input-box">
					<input  type="text" name="product[stock_data][qty]" value="<?php echo $qty;?>" id="qty" class="form-control required-entry validate-number input-text" />
				</div>
			</div>
			
			<?php if($checkstatus==\Ced\CsMarketplace\Model\Vproducts::APPROVED_STATUS){?>
			<div class="form-group col-md-6">
					<label class="required"><em>*</em><?php echo __('Status') ?></label>:
					<div class="input-box">
						<select id="is_in_stock" class="form-control select  required-entry"
						name="product[status]">
							<option <?php echo $status==\Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED?"selected":""?>  value="<?php echo \Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED?>"><?php echo __('Enable'); ?></option>
							<option <?php echo $status==\Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_DISABLED?"selected":""?>  value="<?php echo \Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_DISABLED?>"><?php echo __('Disable'); ?></option>
						</select>
					</div>
			</div>
				<?php }?>
			<div style="clear:both;"></div>
			<p class="required"><?php echo __('* Required Fields') ?></p>

</div>
</div>
</div>
</div>
</div>
</form>
<?php //Mage::getSingleton('customer/session')->setFormError(false)->setProductFormData(array());?>
<script type="text/javascript">
require([
     	"jquery",
     	"mage/mage"
     ], function($){

	jQuery('#sku').change(function(){
		var sku=jQuery('#sku').val();
		var url = "<?php echo $this->getUrl('*/*/checksku',array('_secure'=>true,'id'=>1)); ?>";
		
		//alert(url);
		var skulength=sku.length;
		if(skulength==0){
			alert("<?php echo __("SKU can't be empty") ?>");
					jQuery('#skuavailable').css('display','none');
					jQuery('#skunotavailable').css('display','none');
		}
		else{
			jQuery.ajax({
				url: url,
				type: "POST",
				data: {sku:sku},
				dataType: 'html',
				success:function($data){
					$data=JSON.parse($data);
					if($data.result==1){
						jQuery('#skuavailable').css('display','block');
						jQuery('#skunotavailable').css('display','none');
					}
					else{
						jQuery('#skunotavailable').css('display','block');
						jQuery('#skuavailable').css('display','none');
						jQuery("#sku").attr('value','');
					}
				}
			});
		}
	});
	var dataForm = $('#edit-form');
			
			dataForm.mage('validation', {
			
				
			}).find('input:text').attr('autocomplete', 'off');
     });


</script>
<style>
.ced_currency_setting .input-group-addon {
  display: inline-block;
  float: left;
  height: 34px;
  padding-right: 20px;
  padding-top: 10px;
}

.ced_currency_setting .input-text {
  display: inline-block !important;
  padding: 4px !important;
  width: 89% !important;
}

.ced_currency_setting {
  width: 100%;
}
</style>