<?php
 /**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsProduct
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile
?>
<div id="<?php echo $block->getHtmlId() ?>" class="admin__grid-massaction">
    <?php if ($block->getHideFormElement() !== true):?>
    <form action="" id="<?php echo $block->getHtmlId() ?>-form" method="post">
    <?php endif ?>
        <div class="admin__grid-massaction-form">
            <?php echo $block->getBlockHtml('formkey')?>
            <select
                id="<?php echo $block->getHtmlId() ?>-select"
                class="local-validation admin__control-select">
                <option class="admin__control-select-placeholder" value="" selected><?php /* @escapeNotVerified */ echo __('Actions') ?></option>
                <?php foreach ($block->getItems() as $_item): ?>
                    <option value="<?php /* @escapeNotVerified */ echo $_item->getProductId() ?>"<?php echo($_item->getSelected() ? ' selected="selected"' : '')?>><?php /* @escapeNotVerified */ echo $_item->getLabel() ?></option>
                <?php endforeach; ?>
            </select>
            <span class="outer-span" id="<?php echo $block->getHtmlId() ?>-form-hiddens"></span>
            <span class="outer-span" id="<?php echo $block->getHtmlId() ?>-form-additional"></span>
            <?php echo $block->getApplyButtonHtml() ?>
        </div>
    <?php if ($block->getHideFormElement() !== true):?>
    </form>
    <?php endif ?>
    <div class="no-display">
    <?php foreach ($block->getItems() as $_item): ?>
        <div id="<?php echo $block->getHtmlId() ?>-item-<?php /* @escapeNotVerified */ echo $_item->getProductId() ?>-block">
            <?php echo $_item->getAdditionalActionBlockHtml() ?>
        </div>
    <?php endforeach; ?>
    </div>

    <div class="mass-select-wrap">
        <select id="<?php echo $block->getHtmlId() ?>-mass-select" data-menu="grid-mass-select">
            <optgroup label="<?php /* @escapeNotVerified */ echo __('Mass Actions')?>">
                <option disabled selected></option>
                <option value="selectVisible">
                    <?php /* @escapeNotVerified */ echo __('Select Visible') ?>
                </option>
                <option value="unselectVisible">
                    <?php /* @escapeNotVerified */ echo __('Unselect Visible') ?>
                </option>
            </optgroup>
        </select>
        <label for="<?php echo $block->getHtmlId() ?>-mass-select"></label>
    </div>

<script>
    require(['jquery'], function($){
        'use strict';
        $('#<?php echo $block->getHtmlId() ?>-mass-select').change(function () {
            var massAction = $('option:selected', this).val();
            switch (massAction) {
                case 'selectVisible':
                    return <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.selectVisible();
                    break
                case 'unselectVisible':
                    return <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.unselectVisible();
                    break
            }
            this.blur();
        });

    });

    <?php if (!$block->getParentBlock()->canDisplayContainer()): ?>
        <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.setGridIds('<?php /* @escapeNotVerified */ echo $block->getGridIdsJson() ?>');
    <?php endif; ?>
</script>
</div>
