<?php/**
  * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category    Ced
  * @package     {{#Package#}}
  * @author      CedCommerce Core Team <connect@cedcommerce.com>
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://cedcommerce.com/license-agreement.txt
  *//** * @category   	Ced * @package    	Ced_SocialLogin * @author		CedCommerce Magento Core Team <connect@cedcommerce.com> */?><div class="ced-sociallogin-container ced-sociallogin-container-checkout">
    <?php if($this->_currentBlock->facebookEnabled()): ?>
    <div class="ced-sociallogin-login-facebook">
        <h3><?php echo __('Facebook Connect') ?></h3>
        <p><?php echo __('You can continue using your <strong>Facebook</strong> account.') ?></p>
        <?php echo $this->getChildHtml('ced_sociallogin_checkout_facebook_button'); ?>
    </div>
    <?php endif; ?>
</div>