<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_RequestToQuote
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<?php
$poModel = $this->getCollection();
if(isset($poModel) && $poModel->count()>0){?>
	<form action="<?php echo $this->getUrl('carttoquote/myquotes/massdelete');?>" method="post">
		<table class="data-table" id="my-orders-table">
			<thead>
				<tr>
					<th><?php echo __('PO Increment Id');?></th>
					<th><?php echo __('Quote Increment Id');?></th>
					<th><?php echo __('Vendor');?></th>
					<th><?php echo __('Quote Updated Qty');?></th>
					<th><?php echo __('Quote Updated Price');?></th>
					<th><?php echo __('PO Qty');?></th>
					<th><?php echo __('PO Price');?></th>
					<th><?php echo __('Created At');?></th>
					<th><?php echo __('Status');?></th>	
					<th><?php echo __('Action');?></th>			

				</tr>
			</thead>
			<tbody>
		<?php
		foreach($poModel as $value){
			//print_r($poModel->getData());die;

			?>
				<tr>
						<td><?php echo $value->getPoIncrementId(); ?></td>
						<td><?php echo $value->getQuoteIncrementId(); ?></td>
						<td><?php echo $block->getVendorName($value->getVendorId());?>
						</td>
						<td><?php echo $value->getQuoteUpdatedQty() ?></td>
						<td><?php echo $value->getQuoteUpdatedPrice() ?></td>
						<td><?php echo $value->getPoQty() ?></td>
						<td><?php echo $this->_objectManager->create('Magento\Framework\Pricing\Helper\Data')->currency($value->getPoPrice(), true, false); ?></td>
						<td><?php echo $value->getCreatedAt() ?></td>
						<td><?php
							//if(!empty($value->getStatus())){

								switch ($value->getStatus()) {

									case '0': echo "<span style='color:orange'>Pending</span>";
										break;
									case '1': 
									 		  echo "<a href='".$this->getUrl('requesttoquote/quotes/addtocart', ['id'=>$value->getQuoteId(), 'po_incId'=>$value->getPoIncrementId()])."'>Add To Cart</a>";
										break;
									case '2': echo "<span style='color:red'>Declined</span>";
										break;
									case '3': echo "<span style='color:green'>Ordered</span>";
										break;
									default:
											echo "<span style='color:orange'>Pending</span>";
										break;
								}
							//} ?>
						</td>
						<td>
							<a class="action action-edit" href="<?php echo $this->getUrl('requesttoquote/customer/editpo/', ['poId'=>$value->getId()]); ?>" /><span><?php echo __('View') ?> </span>
						</td>

			   </tr>
		<?php }?>
			</tbody>
		</table>
	</form>
<?php if ($block->getPagerHtml()): ?>
<div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif; ?>
<?php }else{?>
<h3><?php echo __('No PO available.');?></h3>
<?php }?>
<style type="text/css">
	.column.main > form {
    overflow-x: auto;
}
.data-table tr {
    border-bottom: 1px solid #ccc;
}
.data-table tr td, .data-table tr th {
    padding: 10px 15px;
    vertical-align: middle;
}
</style>