<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_gifts = $block->getOrders();

 ?>
<?php echo $block->getChildHtml('info');?>
<?php if ($_gifts && count($_gifts)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-groupgifts-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Group Gifts') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Gift Id#') ?></th>
                    <th scope="col" class="col reciever_email"><?php /* @escapeNotVerified */ echo __('Receiver Email') ?></th>
                    <th scope="col" class="col gift_status"><?php /* @escapeNotVerified */ echo __('Group Status') ?></th>
                    <th scope="col" class="col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_gifts as $_gift): ?>
                    <tr>
                        <td data-th="<?php echo $block->escapeHtml(__('Gift Id #')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $_gift->getId() ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Reciever Email')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $_gift->getGiftReceiverEmail(); ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <span class="nobr"> 
                                <a href="<?php echo $this->getViewUrl($_gift) ?>"><?php echo __('View') ?></a>
                            </span>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have no groups !.'); ?></span></div>
<?php endif ?>
