<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_gifts = $block->getOrders();

 foreach ($_gifts as $_gift) {
      $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
      $_last = $block->getlastOrders($_gift)->getFirstItem(); 
      $group_data=$block->customized( $_gift);
      $user=$block->guestuser($_gift);
      if($group_data==1)
      {
           
            foreach( $user->getData() as $value ){

            try{     $model= $objectManager->get('Ced\GroupBuying\Model\Guest')->load($value['id']);
                     if($model->getRequestApproval()!=1){  
                     $model->setData('request_approval',4);
                     $model->save();}
                       
                }catch (\Magento\Framework\Exception\LocalizedException $e) {
                             echo $e->getMessage();
                             
                                                                             }
                 }
      }
}     

 
                       
                   
?>
<?php echo $block->getChildHtml('info');?>
<?php if ($_gifts && count($_gifts)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-groupgifts-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Group Gifts') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Group Id#') ?></th>
                    <th scope="col" class="col reciever_email"><?php /* @escapeNotVerified */ echo __('Request From') ?></th>
                    <th scope="col" class="col gift_status"><?php /* @escapeNotVerified */ echo __('Request Status') ?></th>
                    <th scope="col" class="col gift_status"><?php /* @escapeNotVerified */ echo __('Action') ?></th>
                    <th scope="col" class="col gift_status"><?php /* @escapeNotVerified */ echo __('Message') ?></th>
                    <th scope="col" class="col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_gifts as $_gift): ?>
                    <tr>

                       <?php $_lastone=$block->getlastoneOrders($_gift['groupgift_id'])
                          
                       ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Group Id #')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $_gift['groupgift_id'] ?></td>
                        <?php if ($_gift->getGuestEmail()!=$_lastone['gift_receiver_email']): ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Sender Email')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $_lastone['gift_receiver_email'] ?></td>
                        <?php endif ?>
                        <?php if ($_gift->getGuestEmail()==$_lastone['gift_receiver_email']): ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Sender Email')) ?>" class="col date"><?php /* @escapeNotVerified */ echo "Admin" ?></td>
                        <?php endif ?>
                        <?php if (($_gift->getRequestApproval()==0)&&($_gift->getGuestEmail()!=$_lastone['gift_receiver_email'])): ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <span class="nobr">
                                <a  href="<?php echo $this->getEditUrl($_gift) ?>"><?php echo __('Accept') ?></a>
                                <span> / </span>
                                <a  href="<?php echo $this->getViewUrl($_gift) ?>"><?php echo __('Deny') ?></a>
                            </span>
                        </td>
                        <?php endif ?>
                        <?php if (($_gift->getRequestApproval()==0)&&($_gift->getGuestEmail()==$_lastone['gift_receiver_email'])): ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <span class="nobr">
                              <a href="<?php echo $this->getPurchaseUrl($_gift) ?>"><?php echo __('Purchase Request') ?></a>
                            </span>
                        </td>
                        <?php endif ?>

                        <?php if ($_gift->getRequestApproval()==1): ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <span class="nobr">
                               <?php echo __('Denied') ?>
                            </span>
                        </td>
                        <?php endif ?>

                        <?php if ($_gift->getRequestApproval()==2): ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <span class="nobr">
                              <a href="<?php echo $this->getPurchaseUrl($_gift) ?>"><?php echo __('Purchase Request') ?></a>
                            </span>
                        </td>
                        <?php endif ?>

                        <?php if ($_gift->getRequestApproval()==3): ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <span class="nobr">
                              <?php echo __('Wait Until .....Gather Requirement') ?> 
                            </span>
                        </td>
                        <?php endif ?>

                        <?php if (($_gift->getRequestApproval()==4)&&($_gift->getPayStatus()==0)): ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <span class="nobr">
                              <a href="<?php echo $this->getPaid($_gift) ?>"><?php echo __('Pay Now') ?></a>
                            </span>
                        </td>
                        <?php endif ?>

                        <?php if ($_gift->getPayStatus()==1): ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <span class="nobr">
                              <?php echo __('Paid') ?> 
                            </span>
                        </td>
                        <?php endif ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Group View')) ?>" class="col actions">
                            <span class="nobr"> 
                                <a href="<?php echo $this->getProductView($_gift) ?>"><?php echo __('View') ?></a>
                            </span>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Message')) ?>" class="col actions">
                            <span class="nobr"> 
                                <p><?php echo $this->getGroupMessage($_gift) ?></p>
                            </span>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have no Request !.'); ?></span></div>
<?php endif ?>

