<?php
/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category    Ced
  * @package     Ced_CsOrder
  * @author   	 CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license      http://cedcommerce.com/license-agreement.txt
  */
 
?>
<?php
$vorder = $this->getVorder();
$_order  = $this->getOrder();
$_source = $this->getSource();
$_fullInfo  = $this->getFullTaxInfo();
$localeCurrency = $this->_objectManager->get('Magento\Framework\Locale\Currency');
?>
<div class="order-totals"><table width="100%" cellspacing="0">
    <colgroup><col>
    <col width="1">
            </colgroup><tfoot>
        <tr class="0">
            <td class="label">
                <strong><?php echo  __('SubTotal')?></strong>
            </td>
            <td class="emph">
                <strong><span class="price"><?php echo  $block->displayPrices($_order,$vorder->getBaseOrderTotal(),$vorder->getOrderTotal(),false,''); ?></span></strong>
            </td>
        </tr>
        <?php if($this->_objectManager->get('Ced\CsOrder\Helper\Data')->canShowShipmentBlock($vorder)){ ?>
        <tr class="1">
            <td class="label">
                <strong><?php echo  __('Shipping & Handling')?></strong>
            </td>
            <td class="emph">
                <strong><span class="label"><?php echo $block->displayPrices($_order,$vorder->getBaseShippingAmount(), $vorder->getShippingAmount(), false, ' ');  ?></span></strong>
            </td>
        </tr>
        <tr class="2">
            <td class="label">
                <strong><?php echo  __('Grand Total (Earned)')?></strong>
            </td>
            <td class="emph">
                <strong><span class="price"><?php echo  $block->displayPrices($_order,$vorder->getBaseOrderTotal()+$vorder->getBaseShippingAmount(),$vorder->getOrderTotal()+$vorder->getShippingAmount(),false,''); ?></span></strong>
            </td>
        </tr>
        <?php }else{ ?>    
        <tr class="2">
            <td class="label">
                <strong><?php echo  __('Grand Total (Earned)')?></strong>
            </td>
            <td class="emph">
                <strong><span class="price"><?php echo  $block->displayPrices($_order,$vorder->getBaseOrderTotal(),$vorder->getOrderTotal(),false,''); ?></span></strong>
            </td>
        </tr>
        <?php    } ?>
        
        <tr class="3">
            <td class="label">
                <strong> <?php echo  __('Commission Fee')?></strong>
            </td>
            <td class="emph">
                <strong><span class="price"><?php echo $block->displayPrices($_order,$vorder->getShopCommissionBaseFee(), $vorder->getShopCommissionFee(), false, ' ');  ?></span></strong>
            </td>
        </tr>
                            <tr class="2">
            <td class="label">
                <strong><?php echo  __('Net Earned')?></strong>
            </td>
            <td class="emph">
                <strong><span class="price">
                    
                    <?php echo $block->displayPrices($_order,$vorder->getBaseOrderTotal()-$vorder->getShopCommissionBaseFee(), $vorder->getOrderTotal()-$vorder->getShopCommissionFee(), false, ' ');  ?>
                   </span></strong>
            </td>
        </tr>
      </tfoot>
    </table>
</div>
