<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author 		CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<?php list($formHtml,$html) = $this->getSearchFormHtml(); ?>
<?php echo $formHtml; ?>
<div id="order-items">
	<?php echo $html; ?>
</div>
<div id="order-errors"></div>
<br/>
<div id="order-search" class="csmarketplace-order-search-items" style="display:none">
	<?php echo $this->getLayout()->createBlock('Ced\CsTransaction\Block\Adminhtml\Vpayments\Edit\Tab\Addorder\Search')->setTemplate('Ced_CsTransaction::vpayments/edit/tab/addorder/search.phtml')->toHtml(); ?>
</div>