<?php
/**
  * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category  Ced
  * @package   Ced_CsImportExport
  * @author    CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license      http://cedcommerce.com/license-agreement.txt
  */

// @codingStandardsIgnoreFile
?>
<div class="entry-edit fieldset" id="import_validation_container" style="display:none;">
    <div class="entry-edit-head legend">
        <span class="icon-head head-edit-form fieldset-legend"
            id="import_validation_container_header"><?php /* @escapeNotVerified */ echo __('Validation Results'); ?></span>
    </div><br>
    <div id="import_validation_messages" class="fieldset"><!-- --></div>
</div>
<script>
require(['jquery', 'Magento_Ui/js/modal/alert', 'prototype'], function(jQuery){
//<![CDATA[
    varienImport.resetSelectIndex('entity'); // forced resetting entity selector after page refresh
//]]>

});
</script>
