<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_RequestToQuote
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<?php  
$item_info = $this->getItemInfo();
$totals = $this->getTotals();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');

$subtotal = 0;


    ?>
<table bgcolor="FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650" style="border:1px solid #E0E0E0;" summary="<?php echo __('Products') ?>">
    <thead>
        <tr>
            <th style="font-size:13px;padding:3px 9px" bgcolor="#EAEAEA" align="left"><?php echo __('PO Id') ?></th>
            <th style="font-size:13px;padding:3px 9px" bgcolor="#EAEAEA" align="left"><?php echo __('Product Name') ?></th>
            <th style="font-size:13px;padding:3px 9px" bgcolor="#EAEAEA" align="left"><?php echo __('SKU') ?></th>
            <th style="font-size:13px;padding:3px 9px" bgcolor="#EAEAEA" align="center"><?php echo __('Qty') ?></th>
            <th style="font-size:13px;padding:3px 9px" bgcolor="#EAEAEA" align="right"><?php echo __('Subtotal') ?></th>
        </tr>
    </thead>
    <tbody  bgcolor="#F6F6F6">
    <?php $i=0;?>
    <?php if(!empty($item_info)):?>
        <?php foreach ($item_info as $key => $item): 
                $product_model = $objectManager->create('Magento\Catalog\Model\Product');
        ?>
            <tr align="left" 
                style="font-size: 13px; padding: 3px 9px" <?php echo $i%2 ? ' bgcolor="#EAEAEA"' : '#F6F6F6' ?> class="border">
                <td style="font-size:11px;padding:3px 9px;border-bottom:1px dotted #cccccc" align="left" valign="top"><?php echo $item['po_id'];?></td>
                <td style="font-size:11px;padding:3px 9px;border-bottom:1px dotted #cccccc" align="left" valign="top"><a href="<?php echo $product_model->load($item['prod_id'])->getProductUrl()?>" title="<?php echo $item['name'];?>"><?php echo $item['name'];?></a></td>
                <td style="font-size:11px;padding:3px 9px;border-bottom:1px dotted #cccccc" align="left" valign="top"><?php echo $item['sku'];?></td>
                <td style="font-size:11px;padding:3px 9px;border-bottom:1px dotted #cccccc" align="center" valign="top"><?php echo $item['qty'];?></td>
                <td style="font-size:11px;padding:3px 9px;border-bottom:1px dotted #cccccc" align="right" valign="top"><?php echo $item['price'];?></td>
                <!--
                <td class="number"><?php // echo $product->getStockItem()->getQty();?></td>
                <td class="number">
                <?php 
                /* $WebsiteName=array();
                    foreach($product->getWebsiteIds() as $websiteId){
                        if($websiteId!=0)
                            $WebsiteName[]=$this->_objectManager->get('Magento\Store\Model\Website')->load($websiteId)->getName();
                    } 
                    echo implode(',',$WebsiteName);      */
                ?>
                
                </td>
                -->
            </tr>
            <?php $i++;?>
        <?php endforeach; ?>
    <?php endif;?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="4" style="padding:3px 9px" align="right">Subtotal </td>
            <td style="padding:3px 9px" align="right">
                <span><?php echo $priceHelper->currency($totals['subtotal'], true, false);?></span>
            </td>
        </tr>
        <tr>
            <td style="padding-bottom:3px;padding-left:9px;padding-right:9px;padding-top:3px" colspan="4" align="right">
                <div><strong>Shipping &amp; Handling </strong></div>
            </td>
            <td style="padding-bottom:3px;padding-left:9px;padding-right:9px;padding-top:3px" colspan="4" align="right">
                <strong><?php echo $priceHelper->currency($totals['shipping'], true, false);?> </strong>
            </td>
        </tr>
        <tr>
            <td colspan="4" style="padding:3px 9px" align="right">Grand Total </td>
            <td style="padding:3px 9px" align="right">
                <span><?php echo $priceHelper->currency($totals['grandtotal'], true, false);?></span>
            </td>
        </tr>
    </tbody>
</table>
