<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div id="popup-mpdal">
    <?php
        $args = $block->getModules();
?>
<h1 class="page-heading">
    <?php echo __('Invalid License') ?>
</h1>
<?php if(strlen($args) > 0) { ?>
    <p><?php echo __('For Following Module(s):')?> <?php echo $args; ?></p>
<?php } ?>
<p><?php echo __('In order to use these module(s) you have to '); ?>
<a id="activate" href="<?php echo $this->getUrl('adminhtml/system_config/edit/section/cedcore/'); ?>" title="<?php echo __('Activate'); ?>"><?php echo __('Activate'); ?></a>
<?php echo __(' these module(s) before use.') ?></p>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: '',
                buttons: [{
                    text: $.mage.__('Activate'),
                    class: '',
                    click: function () {
                        /*this.closeModal();*/
                        window.location='<?php echo $this->getUrl('adminhtml/system_config/edit/section/cedcore/'); ?>';
                     
                    }
                }]
            };

            var popup = modal(options, $('#popup-mpdal'));

            $('#popup-mpdal').modal('openModal');
        }
    );
</script>


