<?php 
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Vbadges
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
 <style>
.vshop-left-cat-filter {margin-left:10px;padding: 5px;}
</style>
<div class="block block-layered-nav">
	<div class="block-title">
        <strong><span><?php echo __('VENDOR BADGES') ?></span></strong>
    </div>
    <div class="block-content">
        <dl id="narrow-by-list2">
            <dt>
            <?php 
                $badges=$block->getshopbadges();
                if(sizeof($badges["order"])>0){
                	foreach($badges["order"] as $key=>$value){
                		if($value!=""){
                			echo '<img src="' .$value. '" width="150px" height="150px" >';
                		}
                	}
                }
                if(sizeof($badges["review"])>0){
                	foreach($badges["review"] as $key=>$value){
                		if($value!=""){
                			echo '<img src="' .$value. '" width="150px" height="150px" >';
                		}
                	}
                }
            ?>
            </dt>
        </dl>
    </div>
</div>