<?php
/**
  * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category    Ced
  * @package     {{#Package#}}
  * @author      CedCommerce Core Team <connect@cedcommerce.com>
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://cedcommerce.com/license-agreement.txt
  */

/**
 * @category   	Ced
 * @package    	Ced_SocialLogin
 * @author 		CedCommerce Magento Core Team <connect@cedcommerce.com>
 */
?>
<div class="clearer">
    <a href="<?php echo $this->escapeUrl($this->getButtonUrl()); ?>">
			<div class="ced-sociallogin-linkedin-inner <?php echo $this->getButtonClass(); ?>">
			</div>
    </a>    
</div>
