<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_RequestToQuote
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

?>

<?php

$quoteData = $block->getQuoteData();
$quoteItems = $block->getItems();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$chatshistory = $objectManager->create('Ced\RequestToQuote\Model\Message')->getCollection()->addFieldToFilter('quote_id',$block->getQuoteId());

?>


<main id="anchor-content" class="page-content">
    <div class="page-main-actions">    
        <div class="page-actions-placeholder"></div>
        <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
            <div class="page-actions-inner" data-title="New Invoice">
                <div class="page-actions-buttons">
                    <button id="back" title="Back" type="button" class="action-default scalable back" onclick="setLocation('<?php echo $block->getBackUrl(); ?>')">
                        <span><?php echo __("Back");?></span>
                    </button>
                    <button id="reset" title="Reset" type="button" class="action-default scalable reset" onclick="setLocation('<?php echo $block->getBackUrl(); ?>')">
                        <span><?php echo __("Cancel");?></span>
                    </button>
                    <?php if(($quoteData['status']=='2' || $quoteData['status']=='5' || $quoteData['status']=='6') && $quoteData['remaining_qty']){ ?>
                    <button id="reset" title="Create PO" type="button" class="action-default scalable reset" onclick="setLocation('<?php echo $block->getPOUrl(); ?>')">
                        <span><?php echo __("Create PO");?></span>
                    </button>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
    
    <div id="page:main-container" class="page-columns"><div class="admin__old"><div id="container" class="main-col">
        <form id="edit_form" class="order-invoice-edit" method="post" action="<?php echo $block->getSaveUrl(); ?>" novalidate="novalidate">
        <div><input name="form_key" value="T6gm0xCNkRBl8hOX" type="hidden"></div>

        <section class="admin__page-section order-view-account-information">
            <div class="admin__page-section-title">
                <span class="title"><?php echo __("Quote & Account Information");?></span>
            </div>
            <div class="admin__page-section-content">
                <div class="admin__page-section-item order-information">
                    <div class="admin__page-section-item-title">
                        <span class="title">
                            <span><?php echo __("Quote #");?><?php echo $block->getQuoteIncrementId();?></span>
                            <input type="hidden" name="id" value="<?php echo $block->getQuoteId();?>" />
                                <span>(The quote email was sent)</span>
                        </span>
                    </div>
                    <div class="admin__page-section-item-content">
                        <table class="admin__table-secondary order-information-table">
                            <tbody>
                                <tr>
                                    <th><?php echo __("Quote Date");?></th>
                                    <td><?php echo $block->getQuoteCreatedAt();?></td>
                                </tr>
                                <tr>
                                    <th><?php echo __("Current Quote Status");?></th>
                                    <td><span id="order_status"><?php echo $block->getQuoteStatus();?></span></td>
                                </tr>
                                <tr>
                                        <th><?php echo __("Quote Created From");?></th>
                                        <td><?php echo $block->getStoreDetails();?></td>
                                </tr>
                                <tr>
                                    <th><?php echo __("Quoted Original Quantity");?></th>
                                    <td><?php echo $quoteData['quote_total_qty'];?></td>
                                </tr>
                                <tr>
                                    <th><?php echo __("Quoted Original Price");?></th>
                                    <td><?php echo $block->getCurrencyCode();?><?php echo $quoteData['quote_total_price'];?></td>
                                </tr>
                                <tr>
                                    <th><?php echo __("Comment");?></th>
                                    <td><?php echo $quoteData['comments'];?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="admin__page-section-item order-account-information">
                    <div class="admin__page-section-item-title">
                        <span class="title"><?php echo __("Account Information");?></span>
                        <div class="actions"></div>
                    </div>
                    <div class="admin__page-section-item-content">
                        <table class="admin__table-secondary order-account-information-table">
                            <tbody><tr>
                                <th><?php echo __("Customer Name");?></th>
                                <td>
                                    <a href="<?php echo $block->getCustomerUrl().'id/'.$block->getCustomerId() ;?>" target="_blank">
                                        <span><?php echo $block->getCustomer($block->getCustomerId())->getName();?></span>
                                    </a>
                                    <input type="hidden" name="customer_id" value="<?php echo $block->getCustomerId();?>">
                                </td>
                            </tr>
                            <tr>
                                <th><?php echo __("Customer Email");?></th>
                                <td><a href="mailto:<?php echo $block->getCustomer($block->getCustomerId())->getEmail();?>"><?php echo $block->getCustomer($block->getCustomerId())->getEmail();?></a></td>
                                <input type="hidden" name="customer_email" value="<?php echo $block->getCustomer($block->getCustomerId())->getEmail();?>">
                            </tr>
                            <tr>
                                <th><?php echo __("Customer Group");?></th>
                                <td><?php echo $block->getCustomerGroup($block->getCustomerId());?></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>

    <section class="admin__page-section order-addresses">
        <div class="admin__page-section-title">
            <span class="title"><?php echo __("Address And Shipping Information");?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-billing-address">
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo __("Shipping Address");?></span>
                </div>
                <address class="admin__page-section-item-content"><?php echo $block->getCustomer($block->getCustomerId())->getName();?><br>

                    <?php $address = $block->getCustomerAddress();?><?php echo $address['street'] ?><br>
                    <?php echo $address['city'] ?>,  <?php echo $address['state'] ?>, <?php echo $address['pincode'] ?><br>
                    <?php echo $address['country'] ?> <br>
                    <?php echo __("T");?>: <?php echo $address['telephone'] ?>
                </address>
            </div>

            <div class="admin__page-section-item order-shipping-address">
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo __("Shipping Information");?></span>
                </div>
                <div class="admin__page-section-item-content">
                    <div class="shipping-description-wrapper">
                        <div class="shipping-description-title"><?php echo __("Shippment Method Selected:");?><?php echo $block->getShippingMethod();?>
                        </div>
                        <div class="shipping-description-content">
                            <?php echo __("Total Shipping Charges:");?>
                            <span class="price"><?php echo $block->getCurrencyCode();?><?php echo $block->getShippingAmount();?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?php echo __("Quoted Items:");?></span>
        </div>
        <div class="admin__page-section-content grid">
            <div class="admin__table-wrapper">
                <table class="data-table admin__table-primary order-invoice-tables" id ="edit-order-table">
                    <thead>
                        <tr class="headings">
                            <th class="col-product"><span><?php echo __("Product:");?></span></th>
                            <th class="col-status"><span><?php echo __("Item Stock:");?></span></th>
                            <th class="col-price-original"><span><?php echo __("Actual Price:");?></span></th>
                            <th class="col-price"><span><?php echo __("Quoted Price:");?></span></th>
                            <th class="col-price"><span><?php echo __("Updated Unit Price:");?></span></th>
                            <th class="col-ordered-qty"><span><?php echo __("Quoted Qty:");?></span></th>
                            <th class="col-ordered-qty"><span><?php echo __("Updated Quote Qty:");?></span></th>
                            <th class="col-subtotal"><span><?php echo __("Subtotal:");?></span></th>
                            <th class="col-total last"><span><?php echo __("Row Total");?></span></th>
                        </tr>
                    </thead>
                <tbody class="even">
                    <?php 
                    $total = 0;
                    foreach ($quoteItems->getData() as $value) {
                        $product_id = $value['product_id'];
                        $product = $block->getProduct($product_id);
                        $unitprice = $block->getProductIndividualPrice($product_id); 
                        $subtotal = 0;
                        if($value['remaining_qty']) {
                            $subtotal = $value['remaining_qty'] * $value['unit_price']; 
                        }elseif($value['remaining_qty'] === '0'){
                            $subtotal = 0;
                        }else{ 
                            $subtotal =  $value['quote_updated_qty'] * $value['unit_price']; 
                        }
                        $qty_to_po = 0;
                        if($value['remaining_qty']) {
                            $qty_to_po = $value['remaining_qty']; 
                        }elseif($value['remaining_qty'] === '0'){
                            $qty_to_po = 0;
                        }else{
                            $qty_to_po = $value['quote_updated_qty']; 
                        }
                        $qty_already_poed = 0;
                        if($value['remaining_qty']){
                            $qty_already_poed =  $value['quote_updated_qty'] - $value['remaining_qty'];
                        }elseif($value['remaining_qty'] === '0'){
                            $qty_already_poed = $value['quote_updated_qty'];
                        }else{
                            $qty_already_poed = 0;
                        }
                        $total += $subtotal;


                        ?>
                        <input id="product[<?php echo $product_id;  ?>]" value="<?php echo $product_id;  ?>" type="hidden">
                        <tr>
                            <td class="col-product">
                                <div id="order_item_2_title" class="product-title"><?php echo $product->getName();  ?>
                                </div>
                                <div class="product-sku-block">
                                    <span>SKU:</span> <?php echo $product->getSku();  ?>
                                </div>
                            </td>
                            <td class="col-price-original"><span><?php echo $block->getProductStock($product_id);  ?></span>
                            </td>
                            <td class="col-price-original"><span><?php echo $block->getCurrencyCode();  ?></span><span class="price"><?php echo $product->getPrice();  ?></span>
                            </td>

                            <td class="col-price">
                                <div class="price-excl-tax">
                                    <span><?php echo $block->getCurrencyCode();  ?></span><span class="price"><?php echo $value['updated_price'];  ?></span>
                                </div>
                            </td>

                            <td class="col-price">
                                <div class="price-excl-tax">
                                    <span><?php echo $block->getCurrencyCode(); ?>
                                    <input id="updateprice[<?php echo $product_id;  ?>]" class="input-text admin__control-text qty-input po-price-updated common currency numbersOnly" name="unitprice[<?php echo $product_id;  ?>]" value="<?php echo $value['unit_price'];  ?>" type="text" <?php if($quoteData['status'] > \Ced\RequestToQuote\Model\Quote::QUOTE_STATUS_PROCESSING){?> readonly <?php }?>></span>
                                </div>
                            </td>

                            <td class="col-ordered-qty">
                                <table class="qty-table">
                                    <tbody>
                                        <tr>
                                            <th><?php echo __("Quantity to PO"); ?> :</th>
                                            <td class="col-qty-invoice">
                                                <input id="quantity_to_po[<?php echo $product_id;  ?>]" class="input-text admin__control-text qty-input qty-field-po common numbersOnly" name="quoteproducts[<?php echo $product_id;  ?>]" value="<?php echo $qty_to_po; ?>" type="text" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')"  <?php if($quoteData['status'] > \Ced\RequestToQuote\Model\Quote::QUOTE_STATUS_PROCESSING){?> readonly <?php }?>>
                                            </td>
                                        </tr>
                                        <tr>
                                            <th><?php echo __(" Quantity Already POed"); ?> :</th>
                                            <td><b><?php echo $qty_already_poed;  ?></b></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                            <td class="col-price">
                                <div class="price-excl-tax">
                                    <span class="price" id="quote_qty"></span><span><?php echo $value['quote_updated_qty'];  ?></span>
                                </div>
                            </td>
                            <td class="col-qty">
                                <div class="price-excl-tax">
                                    <span><?php echo $block->getCurrencyCode();  ?></span>
                                    <input class="input-text admin__control-text qty-input subtotal-po currency numbersOnly" name="subtotal[<?php echo $product_id;  ?>]"  type="text"  readonly value="<?php echo $subtotal;?>">
                                </div>
                            </td>

                            <td class="col-subtotal">
                                <div class="price-excl-tax">
                                    <span><?php echo $block->getCurrencyCode();  ?></span>
                                    <input id="rowtotal" class="input-text admin__control-text qty-input row-total common currency numbersOnly" name="row_total[<?php echo $product_id;  ?>]"  type="text" value="<?php echo $subtotal; ?>" readonly>
                                </div>
                            </td>
                        </tr>
                        <?php }?>
                    </tbody>
                </table>
            </div>
        </div>
    </section>



    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?php echo __("Messaging section"); ?> </span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-comments-history">
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo __("Chat History"); ?></span>
                </div>
                <div id="history_form" class="admin__page-section-item-content order-history-form">
                    <div class="admin__field">

                        <div class="viewhistory">
                            <input id="showhistory" type="button" value="<?php echo __("View Message History"); ?>">
                        </div>
                        <div class="message_history">
                            <?php if($chatshistory && count($chatshistory)>0 && !empty($chatshistory->getData())){
                            ?>
                                <ul class="note-list">
                                    <?php foreach ($chatshistory as $_chathistory){?>
                                        <?php if($_chathistory->getSentBy()=='Admin'){ ?>
                                            <li class="purchaseorder-left-chat-column">
                                                <span class="purchaseorder-left-chat-column-date"><?php  echo $this->formatDate($_chathistory
                                                        ->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></span>
                                                <span class="purchaseorder-left-chat-column-date"><?php  echo $this->formatTime($_chathistory
                                                        ->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></span>
                                                <span class="separator">|</span>
                                                <span class="purchaseorder-left-chat-column-sender">
                                                    <strong><?php //?></strong>
                                                </span>
                                                <?php if ($_chathistory->getMessage()){ ?>
                                                    <div class="purchaseorder-left-chat-column-chat"><?php echo $this->escapeHtml($_chathistory->getMessage(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?>

                                                    </div>
                                                <?php } ?>
                                            </li>
                                        <?php } elseif($_chathistory->getSentBy()=='Vendor'){?>
                                                <li class="purchaseorder-right-chat-column" style="background: #9dc5e7">
                                                    <span class="purchaseorder-right-chat-column-date"><?php  echo $this->formatDate($_chathistory
                                                            ->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></span>
                                                    <span class="purchaseorder-right-chat-column-date"><?php  echo $this->formatTime($_chathistory
                                                            ->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></span>
                                                    <span class="separator">|</span>
                                                    <span class="separator">Sent By: Vendor</span>
                                                    <span class="purchaseorder-right-chat-column-sender">
                                                        <strong><?php //?></strong>
                                                    </span>
                                                    <?php if ($_chathistory->getMessage()){ ?>
                                                        <div class="purchaseorder-left-chat-column-chat"><?php echo $this->escapeHtml($_chathistory->getMessage(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?>

                                                        </div>
                                                    <?php } ?>
                                                </li>

                                            <?php }else{  ?>
                                            <li class="purchaseorder-right-chat-column" >
                                                <span class="purchaseorder-right-chat-column-date"><?php  echo $this->formatDate($_chathistory->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></span>
                                                <span class="purchaseorder-right-chat-column-time"><?php  echo $this->formatTime($_chathistory
                                                        ->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></span>
                                                <span class="separator">|</span>
                                                <span class="separator">Sent By: Customer</span>

                                                <?php if ($_chathistory->getMessage()){ ?>
                                                    <div class="note-list-comment"><?php echo $this->escapeHtml($_chathistory->getMessage(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?>

                                                    </div>
                                                <?php } ?>
                                            </li>

                                        <?php } ?>
                                    <?php } ?>
                                </ul>
                            <?php } ?>
                        </div>

                        <label for="invoice_comment_text" class="admin__field-label">
                            <span><?php echo __("Send a message"); ?></span>
                        </label>
                        <div class="admin__field-control">
                            <textarea id="invoice_comment_text" name="message" class="admin__control-textarea" rows="2" cols="5"></textarea>
                        </div>
                    </div>
                </div>
            </div>

            <div id="invoice_totals" class="admin__page-section-item order-totals">
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo __("Quote Totals"); ?></span>
                </div>
                <div class="admin__page-section-item-content order-totals-actions">
                    <table class="data-table admin__table-secondary order-subtotal-table">

                        <tfoot>
                        <tr class="col-0">
                            <td class="label">
                                <strong><?php echo __("Grand Total");?></strong>
                            </td>
                            <td>
                                <span><?php echo $block->getCurrencyCode();?></span>
                                <span><input class="input-text admin__control-text " type="text" id="grandtotalofpo" name="grandtotalofpo" readonly value="<?php echo $total;?>" /></span>
                            </td>
                        </tr>

                        <tr class="col-3">
                            <td class="label">
                                <strong><?php echo __("Total Due");?></strong>
                            </td>
                            <td>
                                <span><?php echo $block->getCurrencyCode();?></span>
                                <span><input class="input-text admin__control-text " type="text" id="totaldue" name="totaldue" readonly value="<?php echo $total + $quoteData->getShippingAmount()?>" /></span>
                            </td>
                        </tr>
                        <tr class="col-3">
                            <td class="label">
                                <strong><?php echo __("Status");?></strong>
                            </td>
                            <td>
                            <?php 
                            $status = $quoteData->getStatus();
                            $quote_status = $block->getQuoteStatusArray();
                            //print_r($quote_status);die;
                            if($status >= 2){
                                echo '<input type="hidden" name="status" value="'.$status.'" />';
                                echo '<span>'.$quote_status[$status].'</span>';
                            }else{
                                unset($quote_status[4], $quote_status[5], $quote_status[6], $quote_status[7]);
                                echo '<select name="status" class="admin__control-select">';
                                foreach ($quote_status as $key => $value) {
                                    ?>
                                    <option value="<?php echo $key;?>" <?php if($key == $status){?>selected<?php }?>><?php echo $value->getText();?></option>
                                <?php } 
                            }?>
                            </td>
                        </tr>
                        </tfoot>

                        <tbody>
                        <tr class="col-0">
                            <td class="label"><?php echo __("Subtotal");?></td>
                            <td>
                                <span><?php echo $block->getCurrencyCode();?></span>
                                <span><input class="input-text admin__control-text " type="text" id="subtotalofpo" name="subtotalofpo" readonly value="<?php echo $total;?>" /></span>

                            </td>
                        </tr>

                        <tr class="col-1">
                            <td class="label"><?php echo __("Shipping & Handling");?></td>
                            <td>
                                <span><span class="input-text admin__control-text price" id="shiping_and_handling"><span><?php echo $block->getCurrencyCode();?></span><?php echo $quoteData->getShippingAmount();?></span>
                                <input type="hidden" id="shiping_and_handling_charges" value="<?php echo $quoteData->getShippingAmount();?>"></span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <?php if($status != 3){?>
                    <div class="actions">
                        <button id="submit" title="Save Quote" type="submit" class="action-default scalable save submit-button primary" >
                            <span><?php echo __("Save Quote"); ?></span>
                        </button>
                    </div>
                    <?php }?>
                </div>
            </div>
        </div>
    </section>
</form>
<script type="text/javascript">

    require(['jquery'], function($) {

        $("#edit-order-table").on('keyup', '.qty-field-po',function(){
            var data =new Array();
            var shipping = $('#shiping_and_handling_charges').val();
            var qty = $(this).val();
            var price = $(this).parents('tr').find('.po-price-updated').val();
            $(this).parents('tr').find('.subtotal-po').val(qty*price);
            $(this).parents('tr').find('.row-total').val(qty*price);
            $(this).parents('table').find('input.common').each( function(index){
                data.push($(this).val());
            });
            var sum=0;
            for(var i=0;i<data.length;i+=3){
                sum += parseFloat(data[i+2]);
            }
            var total = parseFloat(sum)+parseFloat(shipping);
            $('#subtotalofpo').val(sum.toFixed(2));
            $('#grandtotalofpo').val(total.toFixed(2));
            $('#totaldue').val(total.toFixed(2));


        });


        $("#edit-order-table").on('keyup', '.po-price-updated',function(){
            var data =new Array();
            var shipping = $('#shiping_and_handling_charges').val();
            var price = $(this).val();
            var qty = $(this).parents('tr').find('.qty-field-po').val();
            $(this).parents('tr').find('.subtotal-po').val(qty*price);
            $(this).parents('tr').find('.row-total').val(qty*price);

            $(this).parents('table').find('input.common').each( function(index){
                data.push($(this).val());
            });

            var sum=0;
            for(var i=0;i<data.length;i+=3){

                sum += parseFloat(data[i+2]);
            }

            var total = parseFloat(sum)+parseFloat(shipping);
            $('#subtotalofpo').val(sum.toFixed(2));
            $('#grandtotalofpo').val(total.toFixed(2));
            $('#totaldue').val(total.toFixed(2));
        });

        $(document).ready(function(){
            $('.message_history').hide();
            $('#showhistory').on('click', function(event) {

                $('.message_history').toggle();
            });
        });

        $(".numbersOnly").keydown(function (e) {
        // Allow: backspace, delete, tab, escape, enter and .
        if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
             // Allow: Ctrl+A, Command+A
            (e.keyCode === 65 && (e.ctrlKey === true || e.metaKey === true)) || 
             // Allow: home, end, left, right, down, up
            (e.keyCode >= 35 && e.keyCode <= 40)) {
                 // let it happen, don't do anything
                 return;
        }
        // Ensure that it is a number and stop the keypress
        if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
            e.preventDefault();
        }
    });

    });



</script>

<style>
    .currency{
        display: inline-block;
        width: 90% !important;
    }
    .note-list .purchaseorder-left-chat-column {
        background: #f3f3df none repeat scroll 0 0;
        float: left;
        margin-top: 10px;
        padding: 5px;
        width: 60%;
    }
    .note-list .purchaseorder-right-chat-column {
        background: #d3d3d3 none repeat scroll 0 0;
        float: right;
        margin-top: 10px;
        padding: 5px;
        width: 55%;
    }
    .message_history {
        max-height: 250px;
        overflow-y: auto;
        padding: 10px;
    }
    .admin__field-control textarea {
        height: auto;
        margin-bottom: 20px;
    }
    .note-list li {
        list-style: outside none none;
    }
    .order-totals .order-subtotal-table input, .order-totals .order-subtotal-table select {
        width: 90%;
    }
    .viewhistory {
        margin-bottom: 20px;
    }
    .viewhistory > input {
        background: #35302C none repeat scroll 0 0;
        border: medium none;
        color: #fff;
        padding: 5px 20px;
    }
</style>
</div></div>
    </div>
</main>
