<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_RequestToQuote
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info */ ?>
<?php $quotes = $block->getItems(); ?>
<div class="admin__table-wrapper">
	<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php echo __("Quoted Items"); ?></span>
    </div>
    <div class="admin__table-wrapper">
	    <table class="data-table admin__table-primary edit-order-table">
	        <thead>
	            <tr class="headings">
	                <th class="col-product"><span><?php echo __("Product"); ?></span></th>
	                <th class="col-price-original"><span><?php echo __("Unit Price");?></span></th>
	                <th class="col-price"><span><?php echo __("Quoted Price");?></span></th>
	                <th class="col-ordered-qty"><span><?php echo __("Qty Requested");?></span></th>
	                <th class="col-subtotal"><span><?php echo __("Subtotal");?></span></th>                
	            </tr>
	        </thead>
	        <tbody class="even">
	          	
	          	<?php foreach ($quotes->getData() as $value) {
	          		$product_id = $value['product_id'];
	          		$product = $block->getProduct($product_id); ?>

		          	<tr>
		          		<td class="col-product"><div id="order_item_2">
		    			<div id="order_item_2_title" class="product-title"><?php echo $product->getName();  ?>
		    			</div>
		    			<div class="product-sku-block">
		        			<span>SKU:</span> <?php echo $product->getSku();  ?></div>

		        		</div>
		        		</td>
	                    <td class="col-price-original"><span class="price"><?php echo $product->getPrice();  ?></span></td>
	                    <td class="col-price">
	    					<div class="price-excl-tax">
	        
	        					<span class="price"><?php echo $value['price'];  ?></span>
	            			</div>
						</td>
	                    <td class="col-ordered-qty">
		                    <table class="qty-table">
						    	<tbody>
							    	<tr>
								        <th><?php echo __("Updated"); ?> :</th>
								        <td class="col-qty-invoice">
            								<input class="input-text admin__control-text qty-input" style="width: 20%; padding: 0.6rem 1rem; line-height: 1.3; box-sizing: inherit;" name="quoteproducts[<?php echo $product_id;  ?>]" value="<?php echo $value['quote_updated_qty']; ?>" type="text">
        								</td>
							    	</tr>
							    	<tr>
							            <th><?php echo __("Requested"); ?> :</th>
							            <td><b><?php echo $value['product_qty']; ?></b></td>
							        </tr>
						    	</tbody>
					    	</table>
						</td>
	                    <td class="col-subtotal">
						    <div class="price-excl-tax">
						        <span class="price"><?php echo $value['price'];  ?></span>
						    </div>
						</td>
					</tr>
	          	<?php }?>
	        </tbody>
	    </table>
	</div>
</section>
</div>


