<?php
/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category    Ced
  * @package     Ced_CsOrder
  * @author   	 CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license      http://cedcommerce.com/license-agreement.txt
  */
?>
<div class="row">
		<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>
<div class="row">
<div class="col-lg-12">
    <h1 class="icon-head head-products page-header"><?php echo Mage::helper('csorder')->__('Shipment List') ?>
    <div style="float:right" class="content-buttons-placeholder" style="width: 0px; height: 14px;">
    	<p class="content-buttons form-buttons">
    	<?php echo $this->getButtonsHtml() ?>
    	</p>
    </div>
    </h1>
    <div style="clear:both;"></div>     
</div>
</div>
<?php echo $this->getChildHtml('store_switcher');?>
<div>
    <?php echo $this->getGridHtml() ?>
</div>

<script type="text/javascript">
	var BLANK_URL = '<?php echo $this->getJsUrl() ?>blank.html';
	var BLANK_IMG = '<?php echo $this->getJsUrl() ?>spacer.gif';
	var BASE_URL = '<?php echo Mage::getUrl('*') ?>';
	var SKIN_URL = '<?php echo $this->getSkinUrl() ?>';
	var FORM_KEY = '<?php echo $this->getFormKey() ?>';
	//alert(BLANK_URL+'=>'+BLANK_IMG+'=>'+BASE_URL+'=>'+SKIN_URL+'=>'+FORM_KEY);
	
</script>
