<?php  /**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 *
 */
?>
<?php $isLogin = $this->_getSession()->isLoggedIn();?>

<?php if(!$isLogin ){?>
	<button id="bt-loginamazon" class="bt-login-social" alt="<?php echo __('Login by Amazon') ?>" title="<?php echo __('Login by Amazon') ?>" onclick="LoginWithAmazon()" href="javascript:void(0);">
	<span><span><?php echo __('Amazon Sign in') ?></span></span>
</button>
<div id="amazon-root"></div>
<script type="text/javascript">
/*<![CDATA[*/
window.onAmazonLoginReady = function() {
    amazon.Login.setClientId('<?php echo $this->getAmazonCustomerKey(); ?>');
};
(function(d) {
    var a = d.createElement('script'); a.type = 'text/javascript';
    a.async = true; a.id = 'amazon-login-sdk';
    a.src = 'https://api-cdn.amazon.com/sdk/login1.js';
    d.getElementById('amazon-root').appendChild(a);
})(document);

function LoginWithAmazon() {
    options = { scope : 'profile postal_code', response_type: 'token' };
    amazon.Login.authorize(options, function(response) {
        if ( response.error ) {
            alert('oauth error ' + response.error);
            return;
        }
        document.location.href="<?php echo $this->getUrl('sociallogin/sociallogin/amazonlogin')?>?token=" + response.access_token;
    });
}
require([
                'prototype' 
                ], function  () {
                    
                        var button = $('bt-loginamazon');
                        if(button!==undefined && button!==null) {
                        button.onclick = function() {
                            LoginWithAmazon();
                            return false;
                        };
                    }
                });


</script>

   
<?php }?>