<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<?php //echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="row">
<div class="col-md-12" style="margin-top:10px;">
<?php echo $this->getChildHtml('info') ?>  
<div class="order-details col-md-12">
    <?php echo $this->getChildHtml('order_items') ?>  
</div>
<div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo __('Back to Orders') ?></a></p>
</div>
</div>
</div>
</div>
</div>
</div>